### ISSUE TITLE
org-agenda-custom commands extra blank line

### ISSUE THREAD

**Issue by measpear** [alphapapa/org-super-agenda#10]
When using the org-super-agenda with org-agenda-custom commands extra blank line occurs before the org-super-agenda :name property (due to overriding header variable ?). 
Is is possible to prevent this ? 

For example, using the following code snippet, extra blank line occurs before Projects heading.
(let ((org-agenda-custom-commands
       '(("u" "Super view"
          ((agenda "" ((org-super-agenda-groups
                        '((:name "Today"
                                 :time-grid t)))))
           (todo "" ((org-agenda-overriding-header "")
                     (org-super-agenda-groups
                      '((:name "Projects"
                               :children todo)
                        (:discard (:anything t)))))))))))
  (org-agenda nil "u"))
<img width="504" alt="untitled" src="https://user-images.githubusercontent.com/2395948/29334578-8b373dca-8210-11e7-957a-0f11191b4859.png">

**Comment by alphapapa** [comment]
Hi,

What you're seeing is an empty `org-agenda-overriding-header`.  It's not possible to control that from this package.  If you set it to an empty string, Org will insert a blank line.  If you set it to `nil`, it will insert a predefined header.

It wouldn't be unreasonable to ask that Org implement a way to disable the overriding header.  Maybe you could suggest this on the org-mode mailing list.  :)  It would be a simple change to, e.g. make it skip inserting the headers if it was set to `'none` or something like that.

**Comment by measpear** [comment]
Hi,
Thanks for the patch. What i had in my mind is to use org-super-agenda without name property. This way by setting overriding-header as "Projects" i think that i can prevent blank line in org-super-agenda custom-commands use cases.

But your solution is better this way.

**Comment by alphapapa** [comment]
Oh, well, I think we can do that too.  I'll look into it.  Thanks.

**Comment by alphapapa** [comment]
I think that should do it.  :)
