### ISSUE TITLE
[Question] How to eliminate "Other Items"?

### ISSUE THREAD

**Issue by DSMasterson** [alphapapa/org-super-agenda#101]
Based on one of the examples, I built this:

(setq org-agenda-custom-commands
      '(("z" "Super View"
	 ((agenda "a" ((org-agenda-span 'day)
		       (org-super-agenda-groups
			'(
			  (:name "Today"
				 :time-grid t
				 :date today
				 :todo "TODAY"
				 :scheduled today
				 :order 1)
			  (:name "Past Due"
				 :deadline past
				 :order 2)
			  )
			)))
	  (alltodo "b" ((org-agenda-overriding-header "")
	  		(org-super-agenda-groups
	  		 '(
	  		   (:name "Next to do"
	  			  :todo "NEXT"
	  			  :order 1)
	  		   (:name "Important"
	  			  :tag "Important"
	  			  :priority "A"
	  			  :order 6)
	  		   (:name "Due Today"
	  			  :deadline today
	  			  :order 7)
	  		   (:name "Due Soon"
	  			  :deadline future
	  			  :order 8)
	  		   (:name "Overdue"
	  			  :deadline past
	  			  :order 10)
			   (:name "Phone"
				  :todo "PHONE"
				  :order 12)
	  		   (:name "Meetings"
	  			  :todo "MEETING"
	  			  :order 15)
	  		   (:name "Waiting"
	  			  :todo "WAITING"
	  			  :order 20)
	  		   (:name "Trivial"
	  			  :and (:anything 1 :discard 1)
	  			  :order 90)
	  		   )
	  		 )))
	  (alltodo "c" ((org-agenda-overriding-header "")
	  		(org-super-agenda-groups
	  	       	 '(
	  	       	   (:name "Others"
	  	       		  :auto-category 1
	  	       		  :order 25)
	  	       	   )
	  	       	 )))
	  ))))
 In the "Trivial" section, I'm trying to discard all the leftover TODOs (I'll pick them up in the categories in the next section), but the "Other Items" list is still produced.  What am I missing?

**Comment by alphapapa** [comment]
Please see the `:discard` selector in the manual.
