### ISSUE TITLE
Configurable empty lines between groups

### ISSUE THREAD

**Issue by mz-pdm** [alphapapa/org-super-agenda#102]
org-super-agenda puts an empty line before each group. Screen space is precise, it would be nice if one could define whether to put an empty line there before the group or not.
The empty lines can be removed in org-agenda-finalize-hook as a workaround, but it's not very clean and elegant.

**Comment by alphapapa** [comment]
Please see option `org-super-agenda-header-separator`.

**Comment by mz-pdm** [comment]
Right, it works well for me, thank you.
