### ISSUE TITLE
Agenda groups with :name none should respect org-super-agenda-header-separator

### ISSUE THREAD

**Issue by floscr** [alphapapa/org-super-agenda#105]
Super Agenda groups with the property `:name none` right now render as an empty line.

This should respect the `org-super-agenda-header-separator`.

If it would be set to an empty string, we could skip the line overall.

This issue is coming up for me, in this case:

<img width="135" alt="Screenshot 2019-09-05 at 17 09 06" src="https://user-images.githubusercontent.com/1898374/64354648-1efd3980-d000-11e9-9304-178d4066631b.png">

Where my first group has no name and I've set `(org-super-agenda-header-separator "")` but I still get the whitespace.

**Comment by alphapapa** [comment]
Hi Florian,

Thanks for reporting this.  That should fix it.  Please let me know how it works for you.

**Comment by MattCantor** [comment]
Hi all! What would be the way to force the prior behavior, where a group with keyword ':name' set to the symbol 'none' and '(org-super-agenda-header-separator)' set to '"\n"' renders as an empty line?

I've tried variations of setting:

- keyword ':name' to an empty string
- '(org-super-agenda-header-separator)' to an empty string
- '(org-super-agenda-header-separator)'to 32 (ascii for 'space')
- '(org-agenda-header-prefix)' to '"\n"'

Love ricing my org-super-agenda! Thanks for everything @alphapapa
