### ISSUE TITLE
Can you control the sorting order of :auto-group ?

### ISSUE THREAD

**Issue by igoralmeida** [alphapapa/org-super-agenda#106]
Hi, with `:auto-group` ([example](https://github.com/alphapapa/org-super-agenda/blob/master/examples.org#automatically-by-group)), is it possible to change the [apparently] alphabetical order?

And since `examples.org` mentions that this might be obsoleted, how would this work with `:auto-property`? The way I understand it, all it does is allow me to change `:agenda-group:` to something else. Am I missing something?

**Comment by alphapapa** [comment]
Hi,

> Hi, with :auto-group (example), is it possible to change the [apparently] alphabetical order?

No, if there are certain groups you want to appear first, you should select them in separate groups

> And since examples.org mentions that this might be obsoleted, how would this work with :auto-property? The way I understand it, all it does is allow me to change :agenda-group: to something else. Am I missing something?

`:auto-group` is essentially a partially-applied `:auto-property`.  There's no reason for it to exist since `:auto-property` was made, so I'll probably remove it someday.
