### ISSUE TITLE
Installation error in spacemacs: Package 'emacs-26.1' is unavailable

### ISSUE THREAD

**Issue by ngm** [alphapapa/org-super-agenda#107]
I get the following error when trying to install:

> (Spacemacs) --> installing package: org-super-agenda@dotfile... [1/1]
> (Spacemacs) Error: 
An error occurred while installing org-super-agenda (error: (error Package ‘emacs-26.1’ is unavailable))

I have added org-super-agenda into the `dotspacemacs-additional-packages '()` section of .spacemacs config.

- OS: Linux Mint
- Emacs: 25.2.2
- spacemacs: develop branch, v0.300.0

**Comment by alphapapa** [comment]
I feel like your problem report contains the answer.  ;)

**Comment by ngm** [comment]
:D 

Has the required Emacs version bumped up to 26.1?  It's listed as 25.1 everywhere I could think to check...

**Comment by ngm** [comment]
Oh it looks like the ts library on which org-super-agenda depends needs 26.1 - https://melpa.org/#/ts

I guess that's probably where the underlying error is coming from?

**Comment by ngm** [comment]
To confirm - all fine with the install when upgraded to 26.2 (via ppa:kelleyk/emacs).

(Well.. I've got a different error with org-agenda now - https://stackoverflow.com/questions/54580647/org-agenda-wrong-number-of-arguments-error - but nothing to do with org-super-agenda!)

**Comment by ngm** [comment]
Closing as resolved by upgrading to 26.2 - could be handy to update the minimum requirements in the README and melpa though.

Also thanks for the awesome package!

**Comment by alphapapa** [comment]
> Closing as resolved by upgrading to 26.2 - could be handy to update the minimum requirements in the README and melpa though.

Thanks, will do.

> Also thanks for the awesome package!

Thanks for the kind words.  Glad it's useful to you.

I just posted this, which you might also find useful: https://www.reddit.com/r/emacs/comments/d1xiag/orgql_new_helmorgql_command/
