### ISSUE TITLE
Make space before header optional or customizable?

### ISSUE THREAD

**Issue by kandiu** [alphapapa/org-super-agenda#108]
Hello, great package!

I was wondering if it is possible to customize the space before the headers. I know where to modify the line in the source code. In fact, I changed this line (273) `(setq s (concat " " s))` to this `(setq s (concat "" s))`, the line inside ` org-super-agenda--make-agenda-header` function. I don't understand very well elisp, so I don't know if there is a better way to change that line. Anyway, I still have to re-evalute the function everytime I restart emacs.

Is there a better way to achieve the same result?
Thank you!

**Comment by alphapapa** [comment]
The hard-coded space could be changed to a customizable prefix option.  I probably won't get to it soon, but I'll put it on the to-do list.

You could put your modified version of the function in your init file.  e.g.:

```el
(use-package org-super-agenda
  :config
  (defun org-super-agenda--make-agenda-header ...))
```

Or you could use something like `el-patch` to modify it.

**Comment by max6166** [comment]
FYI: Removing the leading space in the group headers fixed origami-mode for me.
