### ISSUE TITLE
Is it possible to disable org super agenda tag inheritance for a single group?

### ISSUE THREAD

**Issue by codygman** [alphapapa/org-super-agenda#110]
Given org file:

```
* Misc
** TODO that thing I keep putting off  :3MustDoThingsToday:
    SCHEDULED: <2019-09-21>
*** TODO figure out how to do the thing
     SCHEDULED: <2019-09-21>
```

And org super agenda config:

```
(setq org-super-agenda-groups
        '(
          (:name "3 Things I'm Doing Today No Matter What"
                 :and (
                       :tag ("3ThingsToday")
                       :scheduled today))))
```

I get something like this:

```
3 Things I'm Doing Today No Matter What
2019-09-21     TODO that thing I keep putting off  :3MustDoThingsToday:
2019-09-21     TODO figure out how to do the thing  :3MustDoThingsToday:
```

When I desired:

```
3 Things I'm Doing Today No Matter What
2019-09-21     TODO that thing I keep putting off  :3MustDoThingsToday:
```

I don't see a clear way of doing this since it looks like `org-super-agenda--get-tags` gets all tags per the setting of `org-agenda-use-tag-inheritance`.

Is there a way to let bind `org-agenda-use-tag-inheritance` to nil while doing that grouping to achieve this affect?

I have a workaround that depends on only tagging things `3MustDoThingsToday` based on their level being 2 in the meantime:

```
(setq org-super-agenda-groups
        '(
          (:name "3 Things I'm Doing Today No Matter What"
                 :and (
                       :tag ("3ThingsToday")
                       :pred (lambda (item) (string-equal (get-text-property 0 'level item) "  "))
                       :scheduled today))))
```

Actually this won't work for me for long since I'll probably soon want to include sub project items in `3ThingsIMustDoToday` so I hope there is another way to accomplish this.

**Comment by alphapapa** [comment]
There's no way to do that, and I don't plan to add one, because it would add significant complexity for little benefit.  For your own use, you could probably hack it in without too much difficulty, but the code that processes groups is pretty ugly, so...have fun.  :)
