### ISSUE TITLE
Possible to suppress default date separators in weekly agenda?

### ISSUE THREAD

**Issue by FTWynn** [alphapapa/org-super-agenda#111]
Hello alphapapa and thank you for this wonderful tool!

I'm trying to generate a weekly DONE agenda for a few categories and munge them into markdown for easy copy/pasting into another tool.  The easiest way I can think of to do this is to use a weekly agenda, but then the categories are split across the default day headers.

Is there a way to suppress these so that the whole week is grouped once instead of by day?

**Comment by alphapapa** [comment]
Thanks for the kind words.

To do that with the regular Org Agenda would require filtering by timestamp ranges.  I don't remember if that's possible; you could check the manual and the Worg site about that.

Instead, I recommend using `org-ql`.  A query like this would show you a nice list:

    (org-ql-search (org-agenda-files)
      '(and (done)
            (closed :from -7 :to 0)))

You could adjust it by e.g. replacing the `-7` or `0` with specific timestamps, apply groups (it supports `org-super-agenda` groups with the `:super-groups` argument, apply sorting, etc.

**Comment by FTWynn** [comment]
This is great! Thank you! I have one org-ql I'll post over there.
