### ISSUE TITLE
Category headers throw errors when major/minor leader key in Spacemacs is pressed

### ISSUE THREAD

**Issue by fabrik42** [alphapapa/org-super-agenda#112]
Hi!
First of all, thank you for this great package! I am using it every day!

I am not an Emacs expert, so I hope my explanation makes sense. 

Most of my day, I use a super agenda with scheduled tasks for this day that looks like this:

<img width="435" alt="_Org_Agenda__org" src="https://user-images.githubusercontent.com/223822/67117989-3e34dc80-f1e4-11e9-89b7-a75e1e507091.png">

The problem is that I can't use the spacemacs leader keys when the cursor is over a line that represents one of super agenda's generated category headers.

It is very irritating, because normally you can use these commands from every buffer. It also works with the single lines of the agenda entries or blank lines, only the category headers cause errors.

`,` causes `user-error: Command not allowed in this line`
`SPACE` or `TAB` causes `command-execute: Wrong type argument: commandp, spacemacs-cmds`

I was not able to find a fix for this, but would be happy to help!

Best,
Christian

**Comment by alphapapa** [comment]
Hi Christian,

I'm glad this package is useful to you.

I don't use Spacemacs or EVIL, so I can't offer specific support for them.  Other users have mentioned similar problems, so you may find help by searching older issue reports here.  Also, the package `evil-collection` tries to work around such issues; if necessary, you might report this issue there, and they might be able to add a fix in it.

In general, the issue is the keymaps, which you can adjust in your config.  So, e.g. you could just set the header keymap in this package to nil.

**Comment by alphapapa** [comment]
By the way, thanks for sharing the screenshot.  I'm curious, where does that pushpin come from?  Is it an emoji, or a composed-region, or...?

**Comment by fabrik42** [comment]
Hi! Thank you for the hints, I am still not sure where the error originates from. It is kind of strange since this only happens for headlines generated by super-agenda, not by headlines in standalone agendas.


The pushpin is just an emoji! :) I basically only use one "work day" agenda that is described [here](https://emacs.christianbaeuerlein.com/my-org-config.html#org2434ad7).

**Comment by alphapapa** [comment]
> Hi! Thank you for the hints, I am still not sure where the error originates from. It is kind of strange since this only happens for headlines generated by super-agenda, not by headlines in standalone agendas.

The headers made by `org-super-agenda` use a different keymap:

```el
(defvar org-super-agenda-header-map (copy-keymap org-agenda-mode-map)
  "Keymap applied to agenda group headers.
This is initialized to a copy of `org-agenda-mode-map'; changes
made to that map after this variable is defined will not be
included.  This map is useful for binding commands which apply
only with point on the group headers (e.g. use `origami' to fold
group headings by binding a key to `origami-toggle-node' in this
map).")
```

**Comment by bleggett** [comment]
Can confirm that with `evil-mode` and `evil-org-agenda` the following fixes this issue:

`(setq org-super-agenda-header-map nil)`

**Comment by fabrik42** [comment]
Yes, this works for me as well!
