### ISSUE TITLE
startup error: `accessor-init` is void

### ISSUE THREAD

**Issue by vchudnov** [alphapapa/org-super-agenda#114]
I am trying org-super-agenda for the first time, and when I install it or then try to run it, I get the error:
`org-super-agenda.el:113:1:Error: Symbol’s value as variable is void: accessor-init`

The referenced line is `(require 'ts)`.

What could be causing this?

**Comment by alphapapa** [comment]
You need to delete old package versions from your Emacs config and reinstall the correct ones.

**Comment by vchudnov** [comment]
No luck so far. Oh well. I'm using emacs 26.3, in case that matters.
