### ISSUE TITLE
Override "Other items" heading name?

### ISSUE THREAD

**Issue by rieje** [alphapapa/org-super-agenda#116]
I am creating a simple agenda view which is the default agenda view followed by a group containing the todo keyword "NEXT". I set this group to the `:order 100` to make it appear *after* everything else (i.e. after the "Other items" which has the default order of `:99`). This works; however, is it possible to override the "Other items" heading name, which appears to be built-in? Doesn't really make sense for my particular situation where "Other items" is everything except those in the "NEXT" group.

**Comment by alphapapa** [comment]
There's already a setting for this.  Please see the customization options.
