### ISSUE TITLE
insert icons in headings using `all-the-icons`?

### ISSUE THREAD

**Issue by xeijin** [alphapapa/org-super-agenda#117]
If there's another way to do this that my inexperience means I'm missing, happy to be corrected.

From what I can see the keywords that display text (like `:name` only accept strings/characters, not a function that returns a string.

This means that when I try and insert an icon from [all-the-icons](https://github.com/domtronn/all-the-icons.el) I instead get an error (as it's insertion function returns a string with text properties).

The icon sets actually have different faces (which are different physical font files) so I can't simply re-define the face: `org-super-agenda-header`. 

Would it be possible to amend `:name` so we can add a little iconography :) ?

**Comment by xeijin** [comment]
I've tried a few variations (including format, below):

```lisp
(:name (format "%s due this week\n" (all-the-icons-insert-faicon "pulse"))
           :order 1
           ;:sort '(deadline)
           :deadline t
           )
```
gives me the error:

`org-super-agenda--group-items: Wrong type argument: characterp, format`

**Comment by xeijin** [comment]
think I have managed it (albeit not pretty)

the following:

```lisp
:title #(" Pulse Agenda " 0 1
  (rear-nonsticky t display
                  (raise -0.24)
                  font-lock-face
                  (:family "github-octicons" :height 1.2)
                  face
                  (:family "github-octicons" :height 1.2)))
                 
  :super-groups
  '(
    ;:sort '(deadline todo)
    (:name #(" due this week\n" 0 1
             (rear-nonsticky t display
                             (raise -0.24)
                             font-lock-face
                             (:family "FontAwesome" :height 1.2)
                             face
                             (:family "FontAwesome" :height 1.2)))
           :order 1
           :deadline t
           )
```

will produce:

![image](https://user-images.githubusercontent.com/291385/68413634-83668180-0186-11ea-9303-474fbf333233.png)

feel free to close if you think this suffices/is appropriate

**Comment by alphapapa** [comment]
The value of `org-super-agenda-groups` is not evaluated, so if you want to use a function's return value in it, you should construct the list either without using `quote`, or  you should use backquoting and unquoting/splicing.

Or, as you cleverly discovered, you can use the `read`able form of a string with text-properties.

Note that in your earlier comment:

> An example using format (I've tried other variations too): gives me the error:

>     org-super-agenda--group-items: Wrong type argument: characterp, format

> However with the :title keyword it does seem to work:

The `:super-groups` argument is passed to `org-super-agenda`, while the `:title` argument to `org-ql-search` is handled by `org-ql`.  They don't have the same semantics.
