### ISSUE TITLE
Reversing the group order of :auto-ts

### ISSUE THREAD

**Issue by akirak** [alphapapa/org-super-agenda#118]
Hi,

I would like to use `:auto-ts`, but it seems to display oldest items first.

Is it possible to reverse the order of groups generated by `:auto-ts`? That is, I want to build an agenda where latest items are shown first, but how can I do that?

`:auto-ts` group is defined as follows, so it would be possible to reverse the display order by somehow inversing `ts<` function. Is there any other way to reverse the order?

```emacs-lisp
(org-super-agenda--def-auto-group ts
  ...
  :key-sort-fn (lambda (a b)
                 (ts< (get-text-property 0 'org-super-agenda-ts a)
                      (get-text-property 0 'org-super-agenda-ts b))))
```

**Comment by alphapapa** [comment]
You could copy the group definition, change the name, and use `ts>`.

**Comment by akirak** [comment]
Thanks.
