### ISSUE TITLE
cannot 'report clock' in super agenda.

### ISSUE THREAD

**Issue by Kinneyzhang** [alphapapa/org-super-agenda#119]
I have customed my GTD agenda using 'org-super-agenda' and it's pretty good. But when I try to run command 'org-clock-report', it doesn't work. Is there some solutions?

**Comment by alphapapa** [comment]
You haven't given me any information to go on.  I don't know what "it doesn't work" means.  And that command is not an agenda command.

**Comment by Kinneyzhang** [comment]
Oh, I've solved the issue, I try to use 'org-clock-report' in org agenda, but it doesn't work. Actually, the right command is 'org-agenda-clockreport-mode'. Thanks for your attention!
