### ISSUE TITLE
MELPA package broken

### ISSUE THREAD

**Issue by bssb** [alphapapa/org-super-agenda#12]
When I installed org-super-agenda from MELPA, it also pulled in the org-20170814 package, which I guess is some dev snapshot version. I wasn't able to get super agenda to work until I deleted this package. I think you can probably remove org as a dependency, since it comes with modern Emacs versions.

**Comment by bssb** [comment]
Nevermind, I think I was using it incorrectly. My bad.

**Comment by alphapapa** [comment]
Well, it depends on Org 9, but Org 8 is still present in a lot of supported Linux distro versions which still have Emacs 24.  So if you are still on Org 8, it will pull in Org 9 from ELPA.  Or, if you use `org-plus-contrib`, it will pull in `org`, but that's a limitation of how `package.el` works.  Hopefully someday `package.el` will be able to handle this better.  Thanks.
