### ISSUE TITLE
best way to customise buffer header-line?

### ISSUE THREAD

**Issue by xeijin** [alphapapa/org-super-agenda#120]
@alphapapa, following on from: https://github.com/alphapapa/org-ql/issues/51 

I wrote the following function to advise `org-ql-view--header-line-format`, stripping out what I don't need from the original buffer `header-line`:

```lisp
(defun +xeijin/org-ql-header (buffers-files query &optional title)
"Return customised header-line-format for BUFFERS-FILES and QUERY.
  Intended as a replacement the function `org-ql-view--header-line-format'."

  (let* ((title (if title
                    (concat (propertize "" 'face 'org-agenda-structure)
                            title " ")
                  "")))
    title))
```

I'm then using it in the following wrapper function for `org-ql-search`:

```lisp
(defun +xeijin/org-ql-search (&rest args)
  "Customise `org-ql-search' with a re-defined header-line and heading faces."

  (let ()
    (unwind-protect
        (progn
          (advice-add 'org-ql-view--header-line-format :override #'+xeijin/org-ql-header)
          (apply #'org-ql-search args)
          (advice-remove 'org-ql-view--header-line-format #'+xeijin/org-ql-header))

      (advice-remove 'org-ql-view--header-line-format #'+xeijin/org-ql-header))))
```

This works fine but as soon as I refresh with `org-ql-view-refresh` it reverses my changes.

I guess this means I need to advise `org-ql-view-refresh` too, but before I do, is there a cleaner way to do this?

I know I could simply overwrite the defun for `org-ql-view--header-line-format`, but I do like to keep the usual header-line details when I'm executing ad-hoc queries.

**Comment by alphapapa** [comment]
Before we get into details, does this issue have anything to do with `org-super-agenda`?  If not, we should talk about it on the `org-ql` repo.

**Comment by xeijin** [comment]
I think you'd suggested we discuss further in `org-super-agenda` in my original ticket, happy to re-raise there if appropriate though.
