### ISSUE TITLE
Add Example which demonstrates how to compose org-super-agenda-groups

### ISSUE THREAD

**Issue by jonathanabennett** [alphapapa/org-super-agenda#123]
Since org-super-agenda-groups is just a list, it can be composed using backquotes and splicing. But this process isn't immediately obvious to someone unfamiliar with elisp. We should include at least 1 example demonstrating this.

**Comment by alphapapa** [comment]
I generally don't want to go this far in the documentation.  I feel like explaining Lisp is out-of-scope for this project.  It is true that some Emacs/Org users who start using this package don't already know how to work with Lisp lists, but that doesn't make it appropriate to explain Lisp here.

Probably, at most, I would add a sentence somewhere saying something like, "`org-super-agenda-groups` is a Lisp form which is a list of lists.  To learn how Lisp lists work, consult the Emacs Lisp manual, or this handy guide: http://..."
