### ISSUE TITLE
how to group filtered tasks by category?

### ISSUE THREAD

**Issue by midas0441** [alphapapa/org-super-agenda#126]
I am filtering tasks by certain criteria (e.g., `:todo "NEXT"`). I want the results to display grouped by category. I tried to use `:auto-category t`, but I can't seem to get that to work on only the filtered tasks. When I use `:auto-category t`, it seems to show *all* tasks.

Is it possible to apply `:auto-category` on only filtered tasks? Is there an example?

**Comment by midas0441** [comment]
apologies if this is not the right place to post this kind of question (or feature request?).

**Comment by alphapapa** [comment]
The primary function of org-super-agenda is to group tasks, not filter them, so generally you should use org-agenda searches or org-ql to do that.  However, you can use the `:discard` selector as a filter to prevent entries from being passed to later selectors, and then `:auto-category` should do what you want.

**Comment by midas0441** [comment]
Very clever. I think I see what you mean. I look forward to trying it tonight.

Apologies for posting the question here. I tried Stackexchange but became impatient.

**Comment by Gahamelas** [comment]
Hi @midas0441, I am exactly trying to do that. Did you manage and how? Thanks! :))

**Comment by alphapapa** [comment]
@Gahamelas Please see this FAQ entry: https://github.com/alphapapa/org-super-agenda#why-are-some-items-not-displayed-even-though-i-used-group-selectors-for-them  If you need more information, please see Reddit r/emacs and r/orgmode, where this issue has been discussed and answered a few times.
