### ISSUE TITLE
auto-group not working?

### ISSUE THREAD

**Issue by gluincth** [alphapapa/org-super-agenda#13]
Hi

First thanks for the super-agenda. I am currently experimenting with this. I tried the auto-group feature, but apparently it is not working for me. All items are sorted into other items.
For tracking I used a simple init file (attached) 
[init_debug.txt](https://github.com/alphapapa/org-super-agenda/files/1237322/init_debug.txt)

and an org file from the examples (grandiose plans etc.)

My org version  is Org mode version 9.0.9 (9.0.9-82-gb862c2-elpa) and org-super-agenda the latest from elpa (org-super-agenda-20170816.1459).

If I could help tracking this down, I'll do so, although I do not yet know how to do a backtrace...

**Comment by alphapapa** [comment]
Hi, did you remember to activate `org-super-agenda-mode`?

**Comment by gluincth** [comment]
Hi
yes I did. It must be running since I get a group "Other Items" where all todos from the test file are collected. Could it have something to do with inheritance? I noticed that for the **:tag** selector  to work (in another test) I had to switch _org-agenda-use-tag-inheritance_ to true.

**Comment by alphapapa** [comment]
Well, the property inheritance should be set automatically.  What is the value of `org-super-agenda-properties-inherit`?

Does the `auto-category` selector work?

**Comment by alphapapa** [comment]
Well, it turns out that the problem is that you're using `:auto-group` while the selector is `:auto-groups` (note the `s`).  :)  I guess I should add an alias for this, because even I didn't notice the problem for a while.

On the plus side, this spurred me to add a testing framework.  :)

**Comment by alphapapa** [comment]
I added a warning, so now if you use an invalid selector you'll get an error in the minibuffer.  Could you please test it and let me know if the warning works for you? Thanks.

**Comment by gluincth** [comment]
Hi 

yes, warning works and after adding the missing s to the selector auto-grouping also works. 
The documentation and examples should be updated to say autogroup**s**.

Thanks!

**Comment by alphapapa** [comment]
Thanks, I did not notice that the docs were wrong too!
