### ISSUE TITLE
Nice underscores line above the headings

### ISSUE THREAD

**Issue by 123unix** [alphapapa/org-super-agenda#134]
How do you do them?
They're not appearing out of the box as seen in the screenshots :-)

Thanks!

**Comment by alphapapa** [comment]
Use `M-x customize-apropos-faces RET org RET` to customize the appearance of headers and other text.

In the future, please use other forums, like /r/emacs or /r/orgmode, to ask questions like this, so other users can offer help and benefit from answers.
