### ISSUE TITLE
Make header in `:auto-parent` compatible with `org-agenda-goto`

### ISSUE THREAD

**Issue by haji-ali** [alphapapa/org-super-agenda#137]
I have my agenda setup with `:auto-parent`.
Right now, when I press `tab` or `RET` on a header I get the error `Command not allowed in this point`. I believe it's because the header does not have an `org-marker` property. Is there a way to easily add this property so that I can navigate to the parent node easily?

**Comment by alphapapa** [comment]
Yes, the string returned by the group selector could easily be propertized with a marker: https://github.com/alphapapa/org-super-agenda/blob/ab9c335f9738853c52aae9b946f50e8b6c46a1e0/org-super-agenda.el#L990

**Comment by haji-ali** [comment]
Thanks for this. Unfortunately, that did not quite work.
I did this

```
(org-super-agenda--def-auto-group parent "their parent heading"
  :key-form (org-super-agenda--when-with-marker-buffer (org-super-agenda--get-marker item)
              (when (org-up-heading-safe)
                (propertize (org-get-heading 'notags 'notodo)
                            'org-marker (org-super-agenda--get-marker item)))))
```
which correctly propertized the header with a marker. However, `org-agenda` uses `org-get-at-bol` to get the `org-marker` property from the beginning of the line. `org-super-agenda` concatenates spaces with different properties to the header.

One way to solve this would be to change
 https://github.com/alphapapa/org-super-agenda/blob/ab9c335f9738853c52aae9b946f50e8b6c46a1e0/org-super-agenda.el#L284

to something like
```
(setq s (propertize (org-no-properties (concat " " s)) (text-properties-at 0 s)))
```
Other `concat` calls in `org-super-agenda` could also benefit from such a change.

**Comment by alphapapa** [comment]
Hmm, okay.  The function `org-super-agenda--make-agenda-header` should probably be modified to preserve the properties of its string argument and ensure that the final string returned has all of them applied to all of it.

**Comment by dustinlacewell** [comment]
I looked into this. It turns out that the properties are not being overridden or anything. `org-agenda-switch-to` checks `org-get-at-bol` for `org-marker`. This fails because org-super-agenda does a `(concat " ")` call when constructing the heading.

A simple change to `org-super-agenda--make-agenda-header` copies the text properties from the incoming string to the whole out-going string. I'll submit a PR.

**Comment by alphapapa** [comment]
This should be fixed in https://github.com/alphapapa/org-super-agenda/commit/e3c5685f144787bbc0e734a5e2f4fced5cc588f4.  @haji-ali Please let me know if it works for you.  Thanks to both of you!

**Comment by haji-ali** [comment]
Just test it and the new fix seems to work as expected. Thanks!
