### ISSUE TITLE
Having no tag is considered as a tag in :auto-tags

### ISSUE THREAD

**Issue by pranavtifr** [alphapapa/org-super-agenda#142]
![image](https://user-images.githubusercontent.com/30164619/76295307-64196580-62da-11ea-8707-6e31775a7373.png)
It would be nicer if it moves on to the other conditions further down instead of considering it as a tag

**Comment by alphapapa** [comment]
Thanks for catching that.  Please let me know if this fixes it for you.

**Comment by pranavtifr** [comment]
Thanks a lot. This fixes it.

Great work on the package btw.

**Comment by alphapapa** [comment]
Thanks.  Please let me know if you find any other issues like this.
