### ISSUE TITLE
Can I disable the display of "Other items"?

### ISSUE THREAD

**Issue by Alexander-Miller** [alphapapa/org-super-agenda#145]
Hi there,

I am trying to create a super-agenda view inspired by this screenshot: https://github.com/nmartin84/.doom.d/blob/master/attachments/doom.png. My goal is to have one large agenda view split into one private and one work sub-group. The current test setup looks like this:

```Elisp
(let ((org-agenda-custom-commands
          '(("z" "Test View"
             ((todo "" ((org-agenda-overriding-header "Private Stuff")
                        (org-agenda-files (list (concat std::org-dir "/Privat.org")))
                        (org-super-agenda-groups
                         '((:todo "INBOX" :name "Inbox")
                           (:todo "NEXT" :name "Tasks")))))
              (todo "" ((org-agenda-overriding-header "Work Stuff")
                        (org-agenda-files (list (concat std::org-dir "/NT.org")))
                        (org-super-agenda-groups
                         '((:todo "INBOX" :name "Inbox")
                           (:todo "NEXT" :name "Tasks"))))))))))
     (org-agenda))
```
That works, but all the items that don't fit in either group are put at the end as "Other items". That includes headlines with a todo status like HABIT that I only want to see in my weekly agenda view, and not in these task lists. 

Is it possible to configure the filters or groups so I only see what is matched and the rest is ignored?

**Comment by alphapapa** [comment]
See `:discard`.

**Comment by Alexander-Miller** [comment]
Got it. For posterity, the solution looks like this:

```Elisp
(org-super-agenda-groups
                         '((:todo "INBOX" :name "Inbox")
                           (:todo "NEXT" :name "Tasks")
                           (:discard (:anything))))
```
