### ISSUE TITLE
More complicated logical expressions

### ISSUE THREAD

**Issue by jcguu95** [alphapapa/org-super-agenda#148]
I struggle from seeing all the things on my agenda, including the most important habits I need to do every day and the fun habits I'd like to practice if I have more time left. I can get around this by setting two agendas, with one excluding the fun habits. However, I will have to remember to only open the 'must-do' agenda, finish it, and then open the 'fun' agenda.

The goal is to have one and only one agenda! And `super-agenda` seems to be close to what I want!

Is it possible to set the super agenda, so that the fun entries (or entries with [#C] priority) show up only when there's nothing important (entries with [#A] priority) undone today?

**Comment by alphapapa** [comment]
Note that this package only groups entries that have been selected by the Agenda or org-ql.

What you're asking for is rather complex, as it would require making one Agenda block conditional on another, which is not supported by any existing code that I know of.

Something similar was mentioned recently here: https://www.reddit.com/r/orgmode/comments/gavqdz/question_about_checking_if_todos_of_a_certain/

Or you could just put the "fun" entries at the bottom of your agenda.

**Comment by jcguu95** [comment]
I see. Sounds like this should be hacked at the `org-agenda` level. Thank you.

**Comment by jcguu95** [comment]
Thank you so much for your generous pointer. I have worked out a specific example that works for me. If you'd like this go into the example section, please let me know. (P.S. I'm an elisp noob and style isn't good.)

```
;;; auxiliary functions
(defun my/extract-time-info-from-agenda-item (agenda-item)
  "Extract date and time-of-day from an org-agenda item as a text
  with properties. For an entry on 2020-12-20 11:59pm, for
  example, the output will be ((20 12 2020) 2359)"
  (let ((date        (get-text-property 1 'date        agenda-item))
        (time-of-day (get-text-property 1 'time-of-day agenda-item)))
    (list date time-of-day)))

(defun my/agenda-item-time (agenda-item)
  "Extract time from org-agenda item AGENDA-ITEM."
  (let* ((time  (my/extract-time-info-from-agenda-item agenda-item))
         (time-of-day (car (cdr time)))

         (year  (nth 2 (car time)))
         (month (nth 1 (car time)))
         (day   (nth 0 (car time)))
         (hour   (if time-of-day
                     (/ time-of-day 100)
                     nil))
         (minute (if time-of-day
                     (% time-of-day 100)
                     nil)))
  (make-decoded-time :year   year
                     :month  month
                     :day    day
                     :hour   hour
                     :minute minute)))

(defun my/agenda-item-hour (agenda-item)
  (nth 2 (my/agenda-item-time agenda-item)))

(defun my/agenda-item-minute (agenda-item)
  (nth 1 (my/agenda-item-time agenda-item)))

(defun my/X-minutes-away (agenda-item)
  (let* ((h     (my/agenda-item-hour agenda-item))
         (m     (my/agenda-item-minute agenda-item))
         (now   (decode-time (current-time)))
         (now-h (nth 2 now))
         (now-m (nth 1 now)))
    (if (and h m)
        (+ (* 60 (- h now-h)) (- m now-m))
        nil)))

(defun my/within-N-minutes-p (N agenda-item)
  (let ((X (my/X-minutes-away agenda-item)))
    (message (format "checking N: %s ; X: %s" N X))
    (if X
        (> N X)
        nil)))
```

```
  (setq org-super-agenda-groups
     '((:name "In three hours."
        :pred (lambda (org-entry) (my/within-N-minutes-p 180 org-entry)))))
```
