### ISSUE TITLE
Filtering with customized functions

### ISSUE THREAD

**Issue by jcguu95** [alphapapa/org-super-agenda#150]
Hello,

Thanks for the hard work. I have been using this for a few days, and it completes my workflow by large!

I wonder if it's possible to filter/handle headlines with customized functions? I think users can extend super-agenda a lot by themselves.

A specific example in my mind is to show the days passed since I worked on X besides it. Then I can judge by that number to see if it's urgent enough to do it.

**Comment by alphapapa** [comment]
Hi,

Thanks for the kind words, I'm glad it's useful to you.  And apologies for overlooking this.

> I wonder if it's possible to filter/handle headlines with customized functions? I think users can extend super-agenda a lot by themselves.

Have you seen the `:pred` and `:auto-map` selectors?

> A specific example in my mind is to show the days passed since I worked on X besides it. Then I can judge by that number to see if it's urgent enough to do it.

I'm not sure exactly what you mean, but that may be a matter for the `org-agenda-prefix-format` to handle rather than this package.

**Comment by jcguu95** [comment]
I see.. according to the docstring of `org-super-agenda--defgroup`

```
Each predicate is called with a single argument: the agenda item
being tested, as a string.  Agenda-related attributes will have
been applied to the string as text-properties.  Use
`describe-text-properties' in an agenda buffer to see what's
available."
```

The agenda items are tested as strings. That makes it hard to extract information of the content of the org tree. But, perhaps not all hopes are gone. I noticed that running `describe-text-properties` at points in the agenda does return a list of text properties. While the content in the org tree are not presented, the scheduled time is. However, I'm not familiar with text properties.. 

The [example for (:pred)](https://github.com/alphapapa/org-super-agenda/blob/master/examples.org#by-predicate) only shows how to match plain strings. Could you please show how to extract the day and time of the entry from the text properties? A **practical example** would be suppressing all agenda items whose scheduled time is later than 4pm.

**Comment by alphapapa** [comment]
I can't write a tutorial for you about text properties and the specific ones the Org Agenda uses.  I had to discover that information by experimentation.  You can see the results of that in the source code of this package.

**Comment by jcguu95** [comment]
@alphapapa sure, that's very helpful advice already! Thank you very much.

If I have made some specific use case work, I will report it here :)
