### ISSUE TITLE
Possible to add "in x days" or something to items?

### ISSUE THREAD

**Issue by pmiddend** [alphapapa/org-super-agenda#151]
I'm using org-super-agenda to construct a todo list. I have a group containing of items that are scheduled after today. I'd like to show a date next to these todo items. Is that possible wiht org-super-agenda?

**Comment by alphapapa** [comment]
`org-super-agenda` is intended to group items, not to change how items are formatted.  Formatting is handled by Org Agenda and `org-ql-view`.

However, you might choose to use the `:transformer` selector.  See https://github.com/alphapapa/org-super-agenda#keywords.  As well, note that `org-ql-view` displays such relative timestamps by default.
