### ISSUE TITLE
Recurring scheduled items is not placed in the right position in the time-grid

### ISSUE THREAD

**Issue by simendsjo** [alphapapa/org-super-agenda#152]
I would expect the time-grid to place the TODO items inline instead of everything at the top. Is it possible to do this somehow?

```lisp
(:name "Schedule"
       :todo t
       :time-grid t)
```

![image](https://user-images.githubusercontent.com/351519/82021798-ccdede80-968b-11ea-9027-6a5b79360389.png)

**Comment by simendsjo** [comment]
It looks like this is an issue only with items with `:STYLE: habit`. As long as I don't have this, it works:

![image](https://user-images.githubusercontent.com/351519/82025927-4d084280-9692-11ea-8c2c-bea4e064f2fa.png)

**Comment by simendsjo** [comment]
On further inspections, it seems I don't need to use `:STYLE: habit` at all for these. I thought org-habit gave me the recurring things with LAST_REPEAT etc, but seems like this is all org-mode.

This might still be a relevant issue, but I'm closing it as it's no longer an issue for me.

**Comment by simendsjo** [comment]
I'm a bit dumb... The issue seems to be that recurring items are all grouped at top

![image](https://user-images.githubusercontent.com/351519/82027187-20edc100-9694-11ea-8062-eb8430b4fbc3.png)

**Comment by alphapapa** [comment]
This package isn't intended to change the order in which items are displayed; that's intended to be controlled by Org Agenda.  However, some selectors use hash tables to group items, and in that case, ordering is not guaranteed.

**Comment by simendsjo** [comment]
So it's a bug in org-agenda or something that can be tweaked there? I'll see if I can find out what's causing this "group at top" for recurring items.

**Comment by simendsjo** [comment]
Asked in r/orgmode: https://www.reddit.com/r/orgmode/comments/gk7pq6/get_repeating_entries_inline_at_the_correct/
