### ISSUE TITLE
org-super-agenda-header-separator not filling header width

### ISSUE THREAD

**Issue by Gahamelas** [alphapapa/org-super-agenda#157]
I can't make the org-super-agenda-header-separator have the width of your headers (see: [image](https://github.com/alphapapa/org-super-agenda/blob/master/images/screenshots/screenshot-after.png)).

I read that for `org-super-agenda-header-separator`

> If a string, a newline is added.  If a character, it is repeated
> to fill window width, and a newline is added

I am setting therefore 

`(setq org-super-agenda-header-separator "_")`

but this only shows one "_" symbol followed by the name of the group header and it does not expand to group header width. What am I doing wrong? Thank you.

**Comment by alphapapa** [comment]
You are setting it to a string, not a character.  In Elisp, a character is specified as an integer or with the `?`-prefixed syntax.

**Comment by Gahamelas** [comment]
Thanks. So how should I type it so it is a character and so I get it formatted like in the image I referenced above?
I have tried:

```
(setq org-super-agenda-header-separator "?_")
(setq org-super-agenda-header-separator "?_")
(setq org-super-agenda-header-separator ?)
(setq org-super-agenda-header-separator ?_)
```

Unsuccesfully.
Thanks, 
GM

**Comment by alphapapa** [comment]
As I said, If you used the customization system instead of setq, it would help ensure you do this correctly.  If you won't do as I recommend, then I can't help you any further, and you should refer to the Elisp manual for character syntax.

**Comment by Gahamelas** [comment]
I wouldn't like to use the customization system because I want to have all my customizations in my init file for moving easily when I move to a new laptop. I am just asking for help, it wouldn't cost you too much to tell me what the syntax is. I am a newbie in Emacs.

**Comment by Gahamelas** [comment]
I am talking about a personal init file.

**Comment by alphapapa** [comment]
So am I.

I don't mean to be rude, but if you don't believe me or trust the advice I am giving, why are you asking me?
