### ISSUE TITLE
Using with the stable orgmode version (>9.0)

### ISSUE THREAD

**Issue by rogorido** [alphapapa/org-super-agenda#16]
Thanks for the very impressive package. If I install org-super-agenda from MELPA, the melpa version of orgmode, which is also (as far as I know) the dev version, is installed. It is possible to install org-super-agenda without installing the melpa version of orgmode (or at least disable it from being loaded)?

**Comment by alphapapa** [comment]
I'm glad you're enjoying it.  :)  Please feel free to contribute a screenshot and example if you like; I think collecting some examples will help other users.

The package is set to depend on `org` at version `9.0` or greater.  What is the version you have installed?  It will only pull in the ELPA (note, not MELPA ;) package if you don't already have Org 9.0+.

**Comment by rogorido** [comment]
thanks for the info!

**Comment by alphapapa** [comment]
I guess your problem is solved then?  Feel free to reopen if necessary.

**Comment by doolio** [comment]
FYI, I use the `org-plus-contrib` repository

```
Org mode version 9.1 (9.1-20-ga4f139-elpaplus @ /home/doolio/.emacs.d/elpa/org-plus-contrib-20170911/)
```

yet installing your package still pulls in the ELPA package `org-20170911`.

**Comment by alphapapa** [comment]
@doolio I also use `org-plus-contrib`.  That is how `package.el` works.  It is nothing to do with `org-super-agenda`.  See discussion on the org-mode mailing list for more information.
