### ISSUE TITLE
not finding anything that isn't scheduled (or have a deadline)

### ISSUE THREAD

**Issue by r-medina** [alphapapa/org-super-agenda#160]
documentation says `:scheduled nil` selects items that have not been scheduled.
but 
```emacs-lisp
(setq org-super-agenda-groups
      '((:name "Catch All" :scheduled nil)))
```

selects nothing

is there something i am doing wrong?

**Comment by alphapapa** [comment]
Please see the FAQ in the readme.

**Comment by r-medina** [comment]
sorry about that!
