### ISSUE TITLE
interaction with the time-grid

### ISSUE THREAD

**Issue by french-maxime-he** [alphapapa/org-super-agenda#162]
First, thanks a lot, @alphapapa, for the various packages you've developed. I truly am looking forward to using them to supercharge my Org uses. There are however a few blurry areas to me, that I need to get under control before confidently making the leap.

Conceptually, the `Weekly/daily agenda` view has a structure, not only a list of items. Depending on configuration: 
- it is structured into days with various number of days shown at the same time
- within a single day, there is a time grid
- and then a **list of items** (that the `osa` present package thrives to structure)

However, it seems not clear to me that the package merely addresses the last point. In particular, the `:time-grid` keyword intrigues me. After some tests, it seems that I can interpret how things work this way:
- each **line** of the grid itself is to be considered an **item** (e.g. "8:00...... --------------")
- all **lines** will be inserted in the first (in the `org-super-agenda-groups` list) group that has non logically nested `:time-grid t`, with said items meshed in the **lines** as usual

This, of course, all depends on the interaction the package is supposed to have with the `Weekly/daily agenda` view. Is that true? Also, if it is the case, then, I guess, there is no way to have multiple time grids in a single day?

Thanks again

**Comment by alphapapa** [comment]
Hi,

Thanks for the kind words.  I hope these packages are useful to you.

I'm not sure what you're asking here.  As the readme says, this package only groups items that are gathered by Org Agenda or `org-ql`.  You may want to experiment with those tools alone before adding the grouping provided by org-super-agenda.
