### ISSUE TITLE
org-agenda-sorting-strategy is applied to every selector separately

### ISSUE THREAD

**Issue by Alexander-Miller** [alphapapa/org-super-agenda#166]
As the documentation says there is an implicit `or` between every selector of a group. So I would have assumed that the items that are matched by these selectors would be sorted as a whole/remain sorted as they were. Instead every selector grabs its own matched items and the results are concatenated, thus losing the original sorting.

For example consider the following org file (with schedule dates adjusted appropriately, today needs to be today for the example to work)

```
* TODO [#A] Today Prio 1
SCHEDULED: <2020-09-13 So>
* TODO [#B] Today Prio 2
SCHEDULED: <2020-09-13 So>
* TODO [#A] Past Prio 1
SCHEDULED: <2020-09-12 Sa>
* TODO [#B] Past Prio 2
SCHEDULED: <2020-09-12 Sa>
```

Say you want to see all these tasks under a "Today" group, so you match those that are scheduled either in the past or today. You also want to sort them by priority. So you create an agenda view like this:

```Elisp
("x" "TEST"
      ((alltodo
        ""
        ((org-agenda-sorting-strategy '(priority-down))
         (org-agenda-files '("~/Documents/Test.org"))
         (org-super-agenda-groups
          '((:name "Test" :scheduled past :scheduled today)))))))
```

The expected result is to see the tasks sorted by priority:

```
 Test
  Test:       TODO [#A] Today Prio 1
  Test:       TODO [#A] Past Prio 1
  Test:       TODO [#B] Today Prio 2
  Test:       TODO [#B] Past Prio 2
```

Instead the agenda looks like this:

```
 Test
  Test:       TODO [#A] Past Prio 1
  Test:       TODO [#B] Past Prio 2
  Test:       TODO [#A] Today Prio 1
  Test:       TODO [#B] Today Prio 2
```

I've looked around the code, and the best I could do is the following diff. It's a brute-force solution, but it's the best I could do on my own - it looks like fixing this without an extra `sort` call would need serious changes to the way selectors work, so they can all be applied at once to a list of items (with something like `-any?`), removing the need for appending, and thus sorting.

```diff
modified   org-super-agenda.el
@@ -796,7 +796,7 @@ The string should be the priority cookie letter, e.g. \"A\".")
                  for custom-section-name = (plist-get filter :name)
                  for order = (or (plist-get filter :order) 0)  ; Lowest number first, 0 by default
                  for (auto-section-name non-matching matching) = (org-super-agenda--group-dispatch all-items filter)
-
+                 do (setf matching (sort matching #'org-entries-lessp))
                  ;; Transformer
                  for transformer = (plist-get filter :transformer)
                  when transformer

```

At any rate if you think the simple solution is good enough I can open a PR (that would also include hiding it behind a customization variable).

**Comment by alphapapa** [comment]
Hi,

Yes, this is a limitation of the current design: `org-agenda` (or `org-ql`, as the case may be) does the sorting before `org-super-agenda` sees any items, and sorting is not reapplied afterward.

That's a nice solution you came up with.  I agree that it probably should not be applied by default, for two reasons: 1) it would reduce performance (substantially in the case of hundreds or thousands of items), and 2) when used with `org-ql`, it wouldn't apply the `org-ql` sorting method.

A customization variable would probably work, allowing users who need it to select it.  If you want to make a PR for it, I'd appreciate that.  Please explain in the option's docstring that it may reduce performance noticeably, and that it will have no effect when used with results from `org-ql`.  Also, please try to add a test to ensure that the new feature works properly.  If you explore the test harness, it shouldn't be too hard to figure it out, but let me know if you need help.

Thanks.

**Comment by Alexander-Miller** [comment]
> it would reduce performance (substantially in the case of hundreds or thousands of items)

Only matched items are sorted. I don't know about you, but IMHO an agenda with thousands of entries is missing the point. By a long shot. Also based on my experience with treemacs the sorting part is fairly cheap, IO and display are what's expensive.

Sorting a million random strings takes 3.2 seconds on my fairly week laptop. How long would it take to parse and group a million line agenda? Scaling that down to a relatively more realistic 50000 gets the time down to merely 100ms. I think we're in the green.

Benchmark used:
```Elisp
(defconst nums (->> (number-sequence 1 1000000) (--map (random 10000)) (-map #'number-to-string)))
(benchmark-run-compiled 1
  (sort nums #'string>))
```

> If you explore the test harness, it shouldn't be too hard to figure it out, but let me know if you need help.

First question: What am I doing wrong? 

```
[λ]-(am@am-laptop)-(/home/am/.emacs.d/straight/repos/org-super-agenda)-(timestamp-group)
❯❯❯ cask exec test/run --debug
DEBUG: ARGS:  --debug --
DEBUG: Remaining args: 
DEBUG: Local time: Mo 14. Sep 20:01:35 CEST 2020
DEBUG: UTC: Mo 14. Sep 18:01:35 UTC 2020
DEBUG: TESTING...
Org version: 9.4
Symbol’s function definition is void: org-super-agenda--test-load-results

```

**Comment by alphapapa** [comment]
> Only matched items are sorted. I don't know about you, but IMHO an agenda with thousands of entries is missing the point. By a long shot. Also based on my experience with treemacs the sorting part is fairly cheap, IO and display are what's expensive.

`org-super-agenda` is not used only to group items in daily/weekly agenda views.  `org-agenda` and `org-ql` provide searching tools that can return any number of entries.  When I search across all of my Org files for `emacs`, I get thousands of entries.  When I use grouping to help me sort through them, this package groups thousands of entries.

> Sorting a million random strings takes 3.2 seconds on my fairly week laptop. How long would it take to parse and group a million line agenda? Scaling that down to a relatively more realistic 50000 gets the time down to merely 100ms. I think we're in the green.

Were it a simple matter of sorting strings, we'd be in the green.  However, it's not.  Please see the implementation of `org-entries-lessp`, and maybe you'll get an idea of what we're dealing with.

> First question: What am I doing wrong?

Nothing--you uncovered a mistake in the `run` script, where I apparently didn't rename a symbol that I renamed in the `test.el` file.  I'll fix that.  Thanks.

**Comment by Alexander-Miller** [comment]
> I'll fix that. Thanks.

:+1: 

> Please see the implementation of org-entries-lessp, and maybe you'll get an idea of what we're dealing with.

Been there already while debugging this, and while it's a pretty large block for every comparison only a few comparisons will actually be made, and the work needed to do them is often just extraction of text properties and follow-up comparison. It's not quite the same as just comparing string, but I don't think it's that much worse.

But let's measure instead or arguing.  Here's a quick benchmark:

```Elisp
(defconst test-entries
  (-let [entries (apply 'org-agenda-get-day-entries
                        "~/Documents/Org/Privat.org" '(9 14 2020) '(:closed :todo :deadline :scheduled :timestamp :sexp))]
    (dotimes (_ 8) (setf entries (append entries entries)))
    entries))
(benchmark-run-compiled 1
  (-let [org-agenda-sorting-strategy (default-value 'org-agenda-sorting-strategy)]
    (sort test-entries #'org-entries-lessp)))
```

For me that sorts 40000 entries within 1s. 5000 entries need 100ms.

So about an order of magnitude worse than just throwing around some strings. Worse than I'd hoped, but IMO still good enough for an optional feature.

**Comment by alphapapa** [comment]
I appreciate your benchmarking, but it seems beside the point because, as I said, there is another reason to not enable the feature by default.  Is there actually an argument here?

**Comment by Alexander-Miller** [comment]
I guess not, I'm just being a bit more optimistic than you are. And I'm not saying that sorting should be on by default either the benchmarking was just as much done for my own curiosity.

The tests are working now, and sorting by default causing 11 of them to fail - that should give me enough material to figure out how the setup works. Hopefully a PR will be ready soon-ish.

**Comment by guibor** [comment]
Hi! It looks like the code changed quite a bit since this PR was proposed - but the feature request would be great!
