### ISSUE TITLE
Selector ":tag" do not working with org-agenda-show-inherited-tags equal to nil

### ISSUE THREAD

**Issue by mskorzhinskiy** [alphapapa/org-super-agenda#17]
For example if we have such file:

\* TODO Parent                                       :tag:
** TODO Children

And if we call then such code:

`
   (let ((org-agenda-show-inherited-tags nil)
          (org-super-agenda-groups '((:name "With tag"
                                          :tag "tag"))))
    (org-agenda nil "t"))
`

We will see:

With tag
TODO Parent

Other items
TODO Children

**Comment by mskorzhinskiy** [comment]
And the issue solved by stop being an idiot and fix the problem in my configuration.

**Comment by alphapapa** [comment]
:)  If you come up with a good config, please consider posting a screenshot and the code so I can add it to the examples.
