### ISSUE TITLE
Deadline and other parameters do not create "full groups"

### ISSUE THREAD

**Issue by seleveles** [alphapapa/org-super-agenda#171]
Hello, I have the following issue:
![Github](https://user-images.githubusercontent.com/23615706/97849667-28149400-1cf3-11eb-9c88-d242f22f0b7d.PNG)

1. I have this "Other items" group I would like to get rid of. From my understanding this group contains items that are not grouped in any other group. And this leads to my second issue.
2. I have category named "Due soon", in which there are two problems:
- It does not group every item with deadline from my agenda files (you can see that in "other items" group there are 5 items with a deadline and in due soon there are only 4)
- It contains duplicates from "Other items" (this bugs me the most, since the other items category should only have items that are not assigned to any other categories, and here we have duplicates).
3. Here is an another example of misgrouped item. In group "Rozpoczęte" I have items with "NEXT" keyword and in group "Luźne" I have items from specific agenda file. I would like the circled item to appear in the former group.

Please pardon me for my English, it is my second language. 

My config:
![github2](https://user-images.githubusercontent.com/23615706/97851284-788cf100-1cf5-11eb-8f37-400468e625ef.PNG)

(use-package! org-super-agenda
  :after org-agenda
  :init
  (setq org-agenda-skip-scheduled-if-done t
org-agenda-skip-deadline-prewarning-if-scheduled t
      org-agenda-skip-deadline-if-done t
      org-agenda-start-with-log-mode t
      org-agenda-include-deadlines t
      org-agenda-block-separator nil
      org-agenda-compact-blocks t
      org-agenda-start-day nil ;; i.e. today
      org-agenda-span 1
      org-agenda-start-on-weekday nil
      org-agenda-dim-blocked-tasks 'invisible
      org-super-agenda-header-map (make-sparse-keymap)
org-agenda-prefix-format '((agenda . " %i %-12:c%?-12t%-6e% s")
                                (todo . " %i %-12:c %-6e")
                                (tags . " %i %-12:c")
                                (search . " %i %-12:c")))
  (setq org-agenda-custom-commands
        '(("j" "Moja agenda"
((agenda "" ((org-agenda-span 'day)
                      (org-super-agenda-groups
                       '((:name "Today"
                                :time-grid t
                                :date today
                                :todo "TODAY"
                                :scheduled today
                                :order 1)))))
         (alltodo "" ((org-agenda-overriding-header "")
                         (org-super-agenda-groups
                          '((:name "To refile"
                             :file-path "inbox"
                             :order 1)
                            (:name "Luźne"
                             :file-path "next"
                             :order 6)
                            (:name "Due today"
                             :deadline today
                             :order 3)
                            (:name "Overdue"
                             :deadline past
                             :order 4)
                            (:name "Due soon"
                             :deadline future
                            :order 5)
                             (:name "Rozpoczęte"
                                    :todo "NEXT"
                                    :order 2)
                             (:auto-outline-path t
                              :order 50)
                             (:discard(:anything t))))))))
          ("t" "Dwa tygodnie"
           ((agenda "" ((org-agenda-span 14)
                        (org-agenda-start-day "-14d")))))
          ))
 :config
  (org-super-agenda-mode))

**Comment by alphapapa** [comment]
Hello,

Your English seems good to me.  :)

Regarding these issues: This kind of question is usually the result of misunderstanding what this package does and how it works.  Please see the [FAQ](https://github.com/alphapapa/org-super-agenda#faq) and the rest of the documentation.

If you still don't understand and don't get the results you're looking for, then I recommend simplifying your configuration down to 1 group and adding one group at a time until you understand how it works and get the desired results.

You may also find org-ql helpful for making it easier to design and save searches: https://github.com/alphapapa/org-ql

**Comment by alphapapa** [comment]
Did you solve the problem?

**Comment by seleveles** [comment]
Hello, it seems to be working correctly now. I changed the config a little bit. Unfortunately I don't understand all parameters, but I think it's ok for now.

**Comment by yelloff** [comment]
Could you please post your changes?

**Comment by seleveles** [comment]
@yelloff Sorry I cannot post exact changes (I do not use git or any other version control software), but  I will post my current config and you should be able to spot the differences. Hope it helps ;)

(setq org-agenda-custom-commands
        '(("j" "Moja agenda"
           ((agenda "" ((org-agenda-span 'day)
                        (org-super-agenda-groups
                         '((:name "Today"
                            :time-grid t
                            :date today
                            :scheduled today
                            :order 0)
                           (:name "Zaległe"
                            :order 1
                            :deadline past)
                           (:name "Terminy"
                            :order 2
                            :deadline future)))))
            (alltodo "" ((org-agenda-overriding-header "")
                         (org-agenda-dim-blocked-tasks 'invisible)
                         (org-super-agenda-groups
                          '((:name "To refile"
                             :file-path "inbox"
                             :order 1)
                            (:discard (:deadline future :deadline today :deadline past :scheduled future :scheduled today :scheduled past))
                            (:name "Rozpoczęte"
                             :todo "NEXT"
                             :order 2)
                            (:name "Luźne"
                             :file-path "next"
                             :order 4)
                            (:auto-outline-path t
                             :order 5)
                            ))))))
          ("t" "Dwa tygodnie"
           ((agenda "" ((org-agenda-span 14)
                        (org-agenda-start-day "-14d")))))
          ))
  :config
  (org-super-agenda-mode))
