### ISSUE TITLE
auto-ts with newest recurring date?

### ISSUE THREAD

**Issue by jhilker1** [alphapapa/org-super-agenda#173]
First of all, I really appreciate you making this package - it's helped me organize my agenda views tremendously. 

I am in several tabletop campaigns that happen either weekly or biweekly, and I have a current agenda view for the week ahead. Is there a way I can get org-super-agenda to show the latest date for a recurring event? I'd like to only have to add 1 timestamp per campaign, but be able to view the next time of the recurring event.

**Comment by alphapapa** [comment]
Thanks for the kind words.  I'm glad it's helpful to you.

I'm sorry, but I'm not sure what you're asking for.  You'd need to give an example with specifics.  However, keep in mind that org-super-agenda does not format items for display--it only groups them.  Formatting is controlled by org-agenda and org-ql (whichever is used).

**Comment by jhilker1** [comment]
For an example of what I mean, I had this event (names changed for privacy).

```
* Campaigns
** Pendragon with John
<2020-10-25 Sun 15:00 +1w>
```
When I use the `auto-ts` selector, it only selects the October 25 timestamp. What I'm asking is if it would be possible for it to get this upcoming date, or if I'd need to use org-ql with it (so for this week it would be the 8th).

**Comment by alphapapa** [comment]
> When I use the auto-ts selector, it only selects the October 25 timestamp.

In the example you showed me, that is the only timestamp that exists, so it is the only one that can be selected.

>  What I'm asking is if it would be possible for it to get this upcoming date, or if I'd need to use org-ql with it (so for this week it would be the 8th).

I don't mean this facetiously, but I'm not sure what you mean by "it" "getting" "this upcoming date."  I need you to use the technical terms.  :)  This is what makes me think that there may be a misunderstanding about how these tools work.  The repeater does not create a future pseudo-timestamp to be selected.

And, to be clear, as the FAQ explains, org-super-agenda does not *select* entries--it *groups* them.  org-agenda and org-ql *select* the entries to be displayed.  (Admittedly the term "select" is used in this package's jargon, but naming things is hard.)

**Comment by jhilker1** [comment]
Alright. I wasn't sure if the super-agenda could see if any event had a recurring timestamp and get the newest timestamp. I'll use org-ql. Thanks.
