### ISSUE TITLE
super-agenda defaults to 4 days earlier in schedule

### ISSUE THREAD

**Issue by rprechelt** [alphapapa/org-super-agenda#176]
When opening an agenda view using `org-super-agenda`, the default agenda view is 4 days in the past i.e. today is Thursday but the default view is for Monday (4 days earlier). On Wednesday, the default view was Sunday (also 4 days earlier).

Opening `emacs -Q`, I load `org-super-agenda` and then configure it `org-super-agenda` with:

```
(setq org-agenda-custom-commands
      '(("o" "Overview"
         ((agenda "" ((org-agenda-span 'day)
                      (org-super-agenda-groups
                       '(
                         (:name "Today"
                          :time-grid t
                          :date today
                          :order 1)
                         )))))))
```

This is the only super-agenda configuration that I specified.

Opening a non-super agenda with `M-x org-agenda` then going to the agenda view `a`, I open a day view with `d`. This opens the agenda view for the **correct** day (Thursday). The date reported in the emacs (`M-x calendar`) is also the correct day (Thursday).

Opening the super-agenda view configured above, the agenda view defaults to 4 days in the past (Monday) - I can move the agenda view forward/back as normal (with `f`/`b`) but resetting with `g` returns it to the **wrong** date. 

This is under Emacs 27.1.

Any advice on how to debug this strange issue?

**Comment by alphapapa** [comment]
As the FAQ in the readme explains, this package does not create agenda views--it only groups items that are produced by them.  I have no explanation for the behavior you've described.  The only suggestion I can give is to start tracing the source code that runs when you execute the commands that seem to do the wrong thing.

**Comment by rprechelt** [comment]
Thanks!

**Comment by alphapapa** [comment]
Please let me know if you figure out what the problem was.  I don't see how it could be caused by org-super-agenda, but stranger things have happened...

**Comment by seokbeomKim** [comment]
This is quite old but I am adding a comment for someone who has the same ask.

```
(setq org-agenda-start-day nil)
```
