### ISSUE TITLE
Feature Request - column mode

### ISSUE THREAD

**Issue by peterhoeg** [alphapapa/org-super-agenda#177]
On a widescreen monitor there is quite a lot of wasted space when viewing the agenda. It would be very neat if super-agenda could support a 2 column mode in addition to the existing layout.

**Comment by alphapapa** [comment]
Have you seen `M-x follow-mode`?

**Comment by peterhoeg** [comment]
>   Have you seen M-x follow-mode?

I didn't know about that. Does most of what I want - thank you!
