### ISSUE TITLE
Invalidating category cache

### ISSUE THREAD

**Issue by akirak** [alphapapa/org-super-agenda#182]
This issue was originally discovered in https://github.com/alphapapa/org-ql/issues/167.

`org-get-category` has is its own cache mechanism, and you have to invalidate the cache by calling `(org-refresh-category-properties)` whenever a category value is updated. I don't know whether this should be handled in `org-super-agenda.el` or in `org.el`.

**Comment by alphapapa** [comment]
I think it should be handled in Org.  If we were to clear the cache in this package, it would probably cause a severe performance regression, and it would be outside of this package's scope--it would seem like a bug in this package if it were to do that.

**Comment by akirak** [comment]
See https://github.com/alphapapa/org-ql/issues/167#issuecomment-746289486
