### ISSUE TITLE
Can I use this only for agenda view and not tags/todo views?

### ISSUE THREAD

**Issue by Fuco1** [alphapapa/org-super-agenda#19]
My "agenda" consists of the agenda view and a bunch of tag views where I display tasks to do next, projects and so on.  Right now having this package enabled replaces all the headlines with `Other items`, that's kind of annoying :)

You can see my agenda sections here: https://github.com/Fuco1/.emacs.d/blob/master/files/org-defs.el#L292

Here's an example (shortened) of the output

```
Saturday    9 September 2017

 Scheduled
  me:         Sched. 6x:  TODO Synchronizovat ledger s uctami (automaticke platby)                                             :ME:GENERAL::

 Other items
               8:00...... ----------------
              10:00...... ----------------
  me:         10:40-12:00 TODO Russian                                                                                        :ME:Langs::RU:
              12:00...... ----------------
              14:00...... ----------------
              16:00...... ----------------
              17:08...... now - - - - - - - - - - - - - - - - - - - - - - - - -
              18:00...... ----------------
────────────────────────────────────────────────────────────────────────────────────
 Other items (Should be called "Tasks to Refile")
  refile:     TODO Mathpages                                                                                             :REFILE::readlater:

 Other items (Should be called "Next tasks")
  emacs:      NEXT Dokumentacia                                                                                           :Emacs:CFG:DIRED::

 Other items (Should be called "Tasks")
  emacs:      TODO Add checker for phpstan                                                                                          :Emacs::
```

**Comment by alphapapa** [comment]
Hi Matus,

Sure, the easiest way would be to bind `org-super-agenda-groups` to `nil` in each of the `my-custom-agenda-sections`.  When that variable is nil, the agenda is not modified.  Or, of course, you could leave it nil by default, and only bind it to the group list in the part you want grouped.

**Comment by Fuco1** [comment]
Oh yes, I'll do it the other way round, let it nil by default and enable for agenda only.  I forgot that you can do those bindings there :D

It is difficult to assess "speaking".  I haven't really used German in the last two years but I can read an article in a newspaper or watch a movie without any trouble.  People usually lose the production facility first.  It would take me a month or so to get back to speed.  I only actively use 5 or so at a time.

**Comment by Fuco1** [comment]
By the way, this is pretty bomb package.  Somehow I ignored it because it seemed I can do the same with the sections but this works much better once I've tried it :)

**Comment by alphapapa** [comment]
Glad you're finding it useful.  I tried to make do with sections too, but they don't benefit from the daily/weekly aspect of the agenda, which drove me to make this.  Please let me know if you ever have any ideas to improve it.

**Comment by Fuco1** [comment]
I have tried to enable this in a specific command but that doesn't seem to work.  Binding the variable does nothing because the advice won't get updated, no?

Here's the code

```
(setq org-agenda-custom-commands
      `((" " "Quick Agenda"
         ((agenda ""
                  ((org-super-agenda-mode t))) ;; does not seem to have an effect.
          ,(cdr (assoc 'refile my-custom-agenda-sections))
          ,(cdr (assoc 'next-tasks my-custom-agenda-sections))
          ,(cdr (assoc 'tasks my-custom-agenda-sections))))))
```

**Comment by alphapapa** [comment]
Just leave the mode enabled all the time.  When `org-super-agenda-groups` is nil, it will have no effect: https://github.com/alphapapa/org-super-agenda/blob/master/org-super-agenda.el#L645

**Comment by Fuco1** [comment]
Oh I'm being silly... I've used the wrong variable :D (`-mode` instead of `-groups`).  I was really tired yesterday when I was setting this up, sorry for the noise :blush:
