### ISSUE TITLE
Is there a way to remove a tag from the displayed line?

### ISSUE THREAD

**Issue by pstray** [alphapapa/org-super-agenda#191]
I have a few blocks like (:name "Personal" :tag "personal") in my config.  Is there a way to remove the :personal: (or whatever other :tag specified) from the shown line in the buffer?

**Comment by alphapapa** [comment]
I don't understand what you mean.  In that example, the line should be displayed as simply `Personal`, no `:personal:`.

**Comment by pstray** [comment]
My agenda definitely has the tags shown, as in:

```
Important
   Todo:       Sched.131x: TODO [#A] Some old task           :work::
   Todo:       Sched. 79x: TODO [#A] Some other task         :personal::
   Todo:       Sched. 79x: TODO [#A] Yet nother task         :personal::
Work
   Todo:       Sched.102x: TODO [#B] Task 4                  :work::
   Todo:       Sched.341x: TODO Task 5                       :work::
   Todo:       Sched.340x: TODO Task 6                       :work::
```
I would like to be able to at least remove the `:work:` part from the lines under the `Work`-heading.

**Comment by alphapapa** [comment]
Oh, you're not talking about the group headers.  The format of individual items is controlled by Org Agenda.  See its customization options.

**Comment by pstray** [comment]
So 'No' then, no way to customize display of individual items under a header in that way?

**Comment by alphapapa** [comment]
Maybe you're looking for the `:transformer` selector.  See the readme: https://github.com/alphapapa/org-super-agenda#group-selectors

**Comment by pstray** [comment]
Not the easiest thing to use, since the string passes has an insane amount of properties on it... but I did manage to make something that seems to work.. only thing now is that other tags present in the line looses their colors.

**Comment by alphapapa** [comment]
Maybe you're modifying the string in a way that deletes the face properties.  Please see the Elisp manual section about text properties.
