### ISSUE TITLE
:priority not working

### ISSUE THREAD

**Issue by rcornelmas** [alphapapa/org-super-agenda#192]
- Trying to use priority to define groups into my super-agenda didn't work it passes all the items to next filters but the priority filter never fires
- Found in the super-agenda.el this function
"defsubst org-super-agenda--get-priority-cookie"
tested  in the scratch buffer with a dummy string containing a priority cookie it worked perfect.
- To work around  used :regexp in org-super-agenda-groups with letter of the priority  helped to group according.

**Comment by pstray** [comment]
This works just as expected in my config:
`(:name "Important" :priority "A")`

**Comment by rcornelmas** [comment]
> This works just as expected in my config:
> `(:name "Important" :priority "A")`

i am using Doom with Emacs 27 ..  still it is not working may be its something related to doom i am still investigating

**Comment by rcornelmas** [comment]
(use-package! org-super-agenda
  :after org-agenda
  :init
  (setq org-agenda-skip-scheduled-if-done t
      org-agenda-skip-deadline-if-done t
      org-agenda-include-deadlines t
      org-agenda-block-separator nil
      org-agenda-compact-blocks t
      org-agenda-start-day nil ;; i.e. today
      ;org-agenda-span 1
      org-agenda-start-on-weekday nil)
:init
(add-to-list 'org-agenda-custom-commands
`("v" "VSuper View"
         ((agenda "" ((org-agenda-span 'day)
                      (org-super-agenda-groups
        '(
                (:name "Important"
                 :priority "A"
                 :face (add-face-text-property start end '(:foreground "orange"))
                 )
                ))))))
             )
:config
  (org-super-agenda-mode))

**Comment by dangirsh** [comment]
This recently stopped working for me in Doom. Please let me know if you find the issue @rcornelmas . It was working in January for me, and broke after a doom + package update.

**Comment by dangirsh** [comment]
Regexp workaround:

```
(:regexp "\\[#A\\]")
(:regexp "\\[#B\\]")
(:regexp "\\[#C\\]")
```

**Comment by alphapapa** [comment]
As far as I know the priority selector does work.  If it doesn't, please open a new issue and be sure to list the versions of the software involved.  Thanks.
