### ISSUE TITLE
Group items by top level heading

### ISSUE THREAD

**Issue by FredrikMeyer** [alphapapa/org-super-agenda#193]
Is there a way to group items by their top level heading?

I.e say my org file is something like this:
```org 
* Header 1
** Child 1
** Child 2
* Header 2
** Child 3
```

Now I use `:auto-outline-path`, but that creates one group per header, not one per top level header.

I saw the example [here](https://github.com/alphapapa/org-super-agenda/blob/master/examples.org#projects), but I'm not sure if I understand it, or if it can be used for this.

Thanks!

**Comment by alphapapa** [comment]
What about `:auto-parent`?

**Comment by FredrikMeyer** [comment]
Thanks for the answer!

That's _almost_ what I want. Expanding on my example above, what I'd want to see this:
Given this:
```
* Header 1
** Child 1.1
*** Child 1.1.1
*** Child 1.1.2
** Child 1.2
* Header 2
** Child 2.1
```
I'd like to see this:
```
* Header 1
** Child 1.1
** Child 1.2
* Header 2
** Child 2.1
```

So I only want to see direct children of the main headlines.

I almost worked this by doing `:auto-group`, but this still includes level 2 children. I see there is `:auto-property` as well, but I don't know if there is way to only inherit properties one level.

**Comment by alphapapa** [comment]
Although it's possible (e.g. using `:pred` with a predicate of your own), it's questionable whether org-super-agenda is the best way to achieve this.  It would probably be better to exclude headings deeper than level 2 in the first place.  That would be easy with org-ql.

**Comment by FredrikMeyer** [comment]
Aha, I didn't know about org-ql!

I see they have an example for filtering agenda views in their README. Thanks for pointing me in the right direction.

**Comment by alphapapa** [comment]
Note that that "they" is me.  ;)

**Comment by FredrikMeyer** [comment]
Aha! Great work on both :D
