### ISSUE TITLE
Remove "category:" prefix with :auto-category?

### ISSUE THREAD

**Issue by jonpalmisc** [alphapapa/org-super-agenda#194]
Hi - I'm really liking super agenda so far, but I was wondering if it is possible to remove this "Category: " prefix (highlighted in yellow) when using the `:auto-category` option. If this is a trivial question, I apologize - I'm new to Emacs and I couldn't find anything about it in the repo docs.

![image](https://user-images.githubusercontent.com/41548458/112042278-b8763880-8b1d-11eb-8fa3-5adc65f2f570.png)

**Comment by alphapapa** [comment]
You could set each group header manually using `:name`.  See https://github.com/alphapapa/org-super-agenda#keywords

Welcome to Emacsland!

**Comment by jonpalmisc** [comment]
I tried that, and that works if the groups are defined explicitly - but if I use the auto category feature, :name has no effect it seems.

________________________________

**Comment by alphapapa** [comment]
Oh, of course, how silly of me.

Well, the easiest solution would be for you to copy the `:auto-category` selector definition and define your own that doesn't add `Category: ` to the heading.  Just a matter of copy-and-paste.

**Comment by jonpalmisc** [comment]
Awesome, I’ll try that. I appreciate your help!

________________________________

**Comment by jonpalmisc** [comment]
Works like a charm, feel free to close.
