### ISSUE TITLE
:scheduled nil  not collecting unscheduled items

### ISSUE THREAD

**Issue by rnikoopour** [alphapapa/org-super-agenda#196]
Hey all,

Thanks for creating `org-super-agenda` I love how much control I have via this plugin.

I'm using the following configuration 
```
(setq org-super-agenda-groups '((:name "Unscheduled" :scheduled nil)
				(:name "Work" :category ("work"))
				(:name "Habits" :habit)))
```

My understanding from the docs is that all unscheduled items would be aggregated under the group "Unscheduled".  However, when I use this configuration this doesn't show up.  I've tried checking day and week views but it still didn't show.

Could I get guidance on how to make the unscheduled items appear under that section?

**Comment by alphapapa** [comment]
I just tested this and it works for me.  Maybe something has changed in a newer version of Org than I'm using.  I'm still using 9.0.5 in my main config.

Please try this:

1.  Put point on the heading of an unscheduled item in your file.
2. Evaluate `(org-entry-get (point) "SCHEDULED")`.  If the result is not `nil`, something has changed in Org.  You can see the relevant code here: https://github.com/alphapapa/org-super-agenda/blob/f5e80e4d0da6b2eeda9ba21e021838fa6a495376/org-super-agenda.el#L495

**Comment by AtomicNess123** [comment]
When you say "Put point on the heading of an unscheduled item in your file", what do you mean?

**Comment by alphapapa** [comment]
*Point* is a technical term in Emacs.  Please see https://www.gnu.org/software/emacs/manual/html_node/emacs/Glossary.html

If you did it right and got nil, then I don't know what the problem is.  Try creating a minimal working example that reproduces the problem in a clean Emacs configuration.

**Comment by ccesare** [comment]
I believe I'm having the same problem. Org is v9.5, and evaluating `(org-entry-get (point) "SCHEDULED")` on an unscheduled item returns `nil`. I've got `(setq org-super-agenda-groups '((:name "Unscheduled" :scheduled nil)))` in my config.

**Comment by alphapapa** [comment]
I can't reproduce this on Emacs 29.4 with Org 9.7.5 and org-super-agenda from `master`.  AFAICT it works fine.
