### ISSUE TITLE
Nested auto-parents?

### ISSUE THREAD

**Issue by iliakur** [alphapapa/org-super-agenda#198]
Hi!

Thanks for the library, I use it every day.

Would it be easy to add an option to the `auto-parent` grouper to include the full path to the parent heading? I often have projects with sub-projects which then contain to-dos and for those cases it would be helpful to get all the context without having to explicitly specify the project inside the sub-project headline.

Thanks in advance for your time!

**Comment by alphapapa** [comment]
Hi,

Thanks, I'm glad to hear it's useful to you.

IIUC what you want is already implemented with the `:auto-outline-path` selector.

**Comment by iliakur** [comment]
I totally missed that selector, I tried it out and it's what I was looking for. Thanks!

**Comment by proudot** [comment]
Following up, is it possible for :auto-outine-path to add the file name ? My project are all associated to a single file, right now I use auto-parents to see all the task subtree in all my files, but I cannot see what subtree belong to what file.
