### ISSUE TITLE
Newbie to org-super-agenda and Emacs

### ISSUE THREAD

**Issue by NovaViper** [alphapapa/org-super-agenda#199]
Hey guys! I'm brand new to Emacs and I'm wondering how I can setup my org-agenda to display my org college planner in a manner like this:

- Today header should have a grid like normal org-agenda, but it displays the classes I have to go to today, as well as any assignments/projects/tests or anything else that is due today.
- Important tasks header are next, these should be things that I mark with a high priority
- Due next header will be tasks/events that are upcoming
- Assignments tab will hold all of my daily assignments
- Projects header will hold all upcoming projects
- Tests will hold all of my test dates, these are really important
- Events will hold extra-curricular actives and holidays
- Other will hold other stuff like reminders and such

Particularly, I plan on having an org file each of general category (which will be `Classes.org`, `Assignments.org` , `Events.org`, `Personal.org`). Classes will hold all information regarding when my classes start, and what days do I attend them. Assignments will hold project info and class assignments Events will hold general school events and extra-curricular stuff. And Personal will hold everything else.

Additionally, I'm confused on how to setup the Classes file particularly because my classes do not repeat everyday, but every other day (like Monday, Wednesday, and Friday; Monday and Wednesday; Tuesday and Thursday) and some occur on the same day twice but have different times (these are classes with lecture and labs). My schedule's this 
![image](https://user-images.githubusercontent.com/7191115/128801728-3261ceff-dd0a-429c-ac6e-c77e13fb6c9f.png)

**Comment by alphapapa** [comment]
"Guys" is just me, the author of org-super-agenda.

This issue tracker is intended for bug reports, feature requests, etc.  It is not a public discussion forum in which to ask for general help.  For that, please use an appropriate place, like old.reddit.com/r/emacs+orgmode, the org-mode mailing list, etc.

Generally, I'd recommend that you glance at this classic how-to guide before posting questions like this: http://catb.org/~esr/faqs/smart-questions.html

Thanks.
