### ISSUE TITLE
Please help me with org-agenda!

### ISSUE THREAD

**Issue by zaen323** [alphapapa/org-super-agenda#20]
I know it is not really the most preferred place to ask this, but after seeing Mr.alphapapa's passionate way of dealing with the issues, i decided to anyway...

Problem:
With day-view, I don't see any TODOs showing under the today's time-grid (with org-super-agenda-mode, that's the 'Today' group).
 
After two weeks of yelling at the computer (comment this, uncomment that, blaming org-projectile(lol), etc...), 
I found out, that of course i wouldn't be seeing it, it's the bloody day view, it only shows the TODOs that are scheduled for the day!!!

So, what shall I do to show the TODOs underneath the time-grid, just as the screenshots show?

Google tells me to customize org-agenda-custom-commands, yet I can't even bind a key to it, because I am using spacemacs, so there's literally no keys left to bind. 
Maybe that's the real problem after all? but there is a successful spacemacs setup in the screenshots (the first one i think), how was it done?
Or the solution is not org-agenda-custom-commands, but something else entirely?

Many thanks in advance.

PS: I will post some screenshots after solving this! i promise!

**Comment by alphapapa** [comment]
Hi,

> So, what shall I do to show the TODOs underneath the time-grid, just as the screenshots show?

What TODOs do you mean?  As you noted, the `org-agenda-list` command only shows TODOs that have a scheduled or deadline date set.  And what screenshots do you mean?

> Google tells me to customize org-agenda-custom-commands, yet I can't even bind a key to it, because I am using spacemacs, so there's literally no keys left to bind.

Bind a key to what?  `org-agenda-custom-commands` is a variable, not a command.  Try `M-x customize-option RET org-agenda-custom-commands RET`.

> but there is a successful spacemacs setup in the screenshots (the first one i think), how was it done?

It's just the Spacemacs theme, not Spacemacs.

> Or the solution is not org-agenda-custom-commands, but something else entirely?

If you want all todo items to be displayed under the daily agenda view, regardless of whether they're scheduled or have a deadline, you need to use a composite custom agenda command as described in the help for `org-agenda-custom-commands`.

> PS: I will post some screenshots after solving this! i promise!

Thanks!

**Comment by zaen323** [comment]
Thanks for the quick response!

I looked again the screenshots, and realized, yes, the TODO items in them are all scheduled.
> If you want all todo items to be displayed under the daily agenda view, regardless of whether they're scheduled or have a deadline, you need to use a composite custom agenda command as described in the help for org-agenda-custom-commands.
Yep. That is exactly what I want, and I apologize for the bad wording. I just want to remind myself that there are a lot of things to do besides playing games :)
> Bind a key to what?
Sorry, I was talking about the shortcut, used to invoke the command.

So... I will start messing around with org-agenda-custom-commands .. but..  
1. Would you mind sharing your org-agenda-custom-commands with me, if you are using one? I know I am supposed to figure it out myself, but before I get onto that, an example might help...
2. After I assign the key, let's say, c, for the new custom command, would I be able to call it from M-x ? I wouldn't want to have to view the custom command by pressing c everytime after calling org-agenda-list, you know.

**Comment by alphapapa** [comment]
> Would you mind sharing your org-agenda-custom-commands with me, if you are using one? I know I am supposed to figure it out myself, but before I get onto that, an example might help...

Sure, but you can find better examples elsewhere on the Internet.  I hardly ever use any of these custom commands at all.  I experimented with them, but in practice I just use the standard daily agenda view with org-super-agenda.  Note that it's not necessary to use a custom agenda command to use org-super-agenda, but you can use a custom command to use different super groups, or if you don't want super groups by default.

```
(setq
   org-agenda-custom-commands
   ;; Setting here instead of in custom-set-variables so I can preserve the comments
   (list
    (quote
     ("A" "Today"
      ;; Copied from and inspired by https://github.com/fniessen/emacs-leuven/blob/master/org-custom-agenda-views.el
      (
       ;; Agenda
       (agenda ""
               ((org-agenda-entry-types '(:timestamp :sexp  :deadline* :scheduled*))
                (org-deadline-warning-days 0)
                (org-agenda-span 'day)))
       ;; DEADLINE today
       (agenda ""
               ((org-agenda-entry-types '(:deadline))
                (org-agenda-overriding-header "Deadline")
                (org-agenda-sorting-strategy '(priority-down time-down))
                (org-agenda-span 'day)
                (org-agenda-start-on-weekday nil)
                (org-deadline-warning-days 0)
                (org-agenda-time-grid nil)))
       ;; TODAY todo items
       (todo "TODAY")
       ;; SCHEDULED for today
       (agenda ""
               ((org-agenda-entry-types '(:scheduled))
                (org-agenda-overriding-header "Scheduled")
                (org-agenda-sorting-strategy '(priority-down time-down))
                (org-agenda-span 'day)
                (org-agenda-start-on-weekday nil)
                (org-deadline-warning-days 0)
                (org-agenda-time-grid nil)
                (org-agenda-skip-function (ap/org-agenda-skip-habits t))))
       ;; Habits
       (agenda ""
               ((org-agenda-entry-types '(:scheduled))
                (org-agenda-overriding-header "Habits")
                (org-agenda-sorting-strategy '(priority-down time-down))
                (org-agenda-span 'day)
                (org-agenda-start-on-weekday nil)
                (org-deadline-warning-days 0)
                (org-agenda-time-grid nil)
                (org-agenda-skip-function (ap/org-agenda-skip-habits nil))))
       ;; Prayers
       (tags-todo "prayers"
                  ((org-agenda-overriding-header "Prayers"))
                  (expand-file-name "prayers.org" org-directory)))))
    (quote ("u" "SUPER Agenda"
            org-agenda-list ""
            ((org-agenda-span 'day)
             (org-super-agenda-groups
              '((:name "Top"
                       :time t
                       :todo "TODAY"
                       :and (:priority "A" :not (:habit t)))
                (:habit t)
                (:todo "NEXT")
                (:name "Prayers" :tag "prayers")
                (:todo ("SOMEDAY" "TO-READ" "CHECK" "TO-WATCH" "WATCHING")
                       :order 9)
                (:name "Friends/Family" :tag ("friends" "family"))
                (:name "Computer"
                       :tag ("computer" "emacs" "org"))
                (:todo "WAITING" :order 8)
                )))))
    (quote
     ("p" "By-Priority"
      ;; Copied from and inspired by https://github.com/fniessen/emacs-leuven/blob/master/org-custom-agenda-views.el
      (
       ;; Agenda
       (agenda ""
               ((org-agenda-entry-types '(:timestamp :sexp))

                (org-agenda-span 'day)))
       ;; Priority A items
       (tags-todo "+PRIORITY={A}"
                  ((org-agenda-entry-types '(:deadline))
                   (org-agenda-overriding-header "Priority A")
                   (org-agenda-sorting-strategy '(deadline-up)))
                  ;; ;;(org-agenda-span 'day)
                  ;; (org-agenda-start-on-weekday nil)
                  ;; (org-deadline-warning-days 0)
                  ;; (org-agenda-time-grid nil)
                  )


       ;; Prayers
       (tags-todo "prayers"
                  ((org-agenda-overriding-header "Prayers"))
                  (expand-file-name "prayers.org" org-directory)))))
    (quote
     ("h" "Hotlist"
      ;; tags-todo "DEADLINE<=\"<+1w>\"|PRIORITY={A}|FLAGGED"
      ((tags-todo "DEADLINE<\"<+0d>\""
                  ((org-agenda-overriding-header "OVERDUE")))
       (tags-todo "DEADLINE>=\"<+0d>\"+DEADLINE<=\"<+1w>\""
                  ((org-agenda-overriding-header "DUE IN NEXT 7 DAYS")))
       (tags-todo "DEADLINE=\"\"+PRIORITY={A}|DEADLINE>\"<+1w>\"+PRIORITY={A}"
                  ((org-agenda-overriding-header "HIGH PRIORITY")))
       (tags-todo "DEADLINE=\"\"+FLAGGED|DEADLINE>\"<+1w>\"+FLAGGED"
                  ((org-agenda-overriding-header "FLAGGED")
                   (org-agenda-skip-function
                    '(org-agenda-skip-entry-when-regexp-matches))
                   (org-agenda-skip-regexp "\\[#A\\]")))
       ;; (tags-todo "DEADLINE=\"\"+PRIORITY<>{A}+FLAGGED|DEADLINE>\"<+1w>\"+PRIORITY<>{A}+FLAGGED"
       ;;            ((org-agenda-overriding-header "...FLAGGED...")))
       )
      ((org-agenda-todo-ignore-scheduled 'future)
       (org-agenda-sorting-strategy '(deadline-up)))))))
```
> After I assign the key, let's say, c, for the new custom command, would I be able to call it from M-x ? I wouldn't want to have to view the custom command by pressing c everytime after calling org-agenda-list, you know.

You use the org-agenda dispatcher.  Please refer to the agenda section of the Org manual, which explains this in detail.

**Comment by zaen323** [comment]
Thank you for the code, it means a great deal to me.
> but since your questions are not specific to org-super-agenda, please ask in a more appropriate place, like /r/emacs, the org-mode mailing list, emacs.SE, etc. 
Never had the emacs subreddit in my mind though. It seems the best place to ask org-agenda questions. Sorry about this, will never do it again. 😢 

I guess I will close this for now, and when I'm ready to post the screenshots, i will let you know. (through the pull request right i think?) I am very grateful for you taking time off for me.

**Comment by alphapapa** [comment]
> Thank you for the code, it means a great deal to me.

I'm glad to help.  But you might want to look at, e.g. Matus Goljer's or Karl Voit's Org agenda configurations.  Matus's is on GitHub, his username is Fuco1 . Karl's is on his web site, karl-voit.at.

> Never had the emacs subreddit in my mind though. It seems the best place to ask org-agenda questions. 

You'll generally get a quick response there.  /r/orgmode is another possibility, but it's not very active in comparison.  The Org mailing list is very active, helpful, and friendly, so do check it out.  You can access it via NNTP and Gnus through GMANE too, instead of using email.

> Sorry about this, will never do it again. :cry:

Please, no need for that.  :)  I'm glad to help you, but by posting it in a more public place, you can benefit from more people helping you, a quicker response, and then other people can benefit from the responses too.

> I guess I will close this for now, and when I'm ready to post the screenshots, i will let you know. (through the pull request right i think?) I am very grateful for you taking time off for me.

You can just post them here and I'll add them.  I appreciate your offer very much.  Welcome to the Org community!  :)

**Comment by zaen323** [comment]
Fuco1 is the author of smartparens isn't he? Never had the pleasure to find out he put his init file on github too.

> The Org mailing list is very active, helpful, and friendly, so do check it out. You can access it via NNTP and Gnus through GMANE too, instead of using email.

Really! I have been thinking about creating a different email address specifically for mailing though, I will definitely try out gnus. being able to utilize mailing list is definitely an important milestone :)

> Please, no need for that. :) I'm glad to help you, but by posting it in a more public place, you can benefit from more people helping you, a quicker response, and then other people can benefit from the responses too.

Well to be honest, I just wanted to personally have your advice, since you are the author of this great repo. 😃  But yeah, you are absolutely right. 
"other people can benefit from the response too"
too bloody correct!!

Can't thank you enough for the hospitality. Someday, I wish to be as warm and welcoming as you, contributing to org (and emacs of course) ;)

**Comment by alphapapa** [comment]
> Fuco1 is the author of smartparens isn't he? Never had the pleasure to find out he put his init file on github too.

Yes, he's definitely one of the stars of the Emacs community.

> Really! I have been thinking about creating a different email address specifically for mailing though, I will definitely try out gnus. being able to utilize mailing list is definitely an important milestone :)

Gnus is a complicated beast, so expect to learn it very slowly.  I still have to look up how to do simple things like mark a thread as unread.  It is nice to use for mailing lists though, the GMANE NNTP-SMTP gateway is much nicer than receiving tons of emails.

> Well to be honest, I just wanted to personally have your advice, since you are the author of this great repo. 

Haha, well, I'm glad I could help.  :)

> Can't thank you enough for the hospitality. Someday, I wish to be as warm and welcoming as you, contributing to org (and emacs of course) ;)

You are too kind.  I am a nobody here.  :)  If you want good role models in the Emacs/Org community, I heartily recommend people like Steve Purcell (of MELPA), Carsten Dominik (original creator of Org-mode), and Sacha Chua (prolific author and unofficial Emacs "ambassador").  They are mine!  :)

**Comment by zaen323** [comment]
Aha :) thanks for the advice.

> I am a nobody here.

Oh I disagree. You are most humble, but you certainly are one of my exemplars. Look at all the projects you've got. Hard work and dedication aye? :)

Anyway, thank you so much for taking your time. Please have a nice day!!

**Comment by zaen323** [comment]
Oh wait, the time zone... nvm orz

**Comment by zaen323** [comment]
Hi there :)
I know I'm a bit late, I was trying to make org-agenda-property work but... oh no :(

After DDoSing google around,(xD) I was fortunate enough to find this article: https://blog.aaronbieber.com/2016/09/24/an-agenda-for-life-with-org-mode.html
which basically represent what I was looking for. And the ways to achieve it.

So, here you go! 
```
  (setq org-agenda-time-grid
        '((daily today require-timed)
          "----------------------"
          ()))

  (setq org-agenda-skip-scheduled-if-done t)
  (setq org-agenda-skip-deadline-if-done t)
  (setq org-agenda-include-deadlines t)
  (setq org-agenda-include-diary t)
  (setq org-agenda-block-separator nil)
  (setq org-agenda-compact-blocks t)
  (setq spacemacs-theme-org-agenda-height nil)
  (add-hook 'org-agenda-mode-hook '(lambda() (hl-line-mode 1)))


  (setq org-agenda-custom-commands (list(quote
        ("z" "Super zaen view" (
                                (agenda "" ((org-agenda-span 'day)
                                            (org-agenda-property-list '("LOCATION" "TEACHER") )
                                            (org-agenda-property-position 'where-it-fits)
                                            (org-agenda-property-separator "|" )

                      (org-super-agenda-groups
                       '((:name "Today"
                                :time-grid t
                                :date today
                                :todo "TODAY"
                                :scheduled today
                                :order 1
                                )))))
          (alltodo "" ((org-agenda-overriding-header "")
                       (org-agenda-property-list '("LOCATION" "TEACHER") )
                       (org-agenda-property-position 'where-it-fits)
                       (org-agenda-property-separator "|" )

                       (org-super-agenda-groups
                        '((:name "Next to do"
                                 :todo "NEXT"
                                 :order 1)
                          (:name "Important"
                                 :tag "Important"
                                 :priority "A"
                                 :order 6)
                          (:name "Due Today"
                                 :deadline today
                                 :order 2)
                          (:name "Due Soon"
                                 :deadline future
                                 :order 8)
                          (:name "Overdue"
                                 :deadline past
                                 :order 7)
                          (:name "Assignments"
                                 :tag "Assignment"
                                 :order 10)
                          (:name "Issues"
                                 :tag "Issue"
                                 :order 12)
                          (:name "Projects"
                                 :tag "Project"
                                 :order 14)
                          (:name "Emacs"
                                 :tag "Emacs"
                                 :order 13)
                          (:name "Research"
                                 :tag "Research"
                                 :order 15)
                          (:name "To read"
                                 :tag "Read"
                                 :order 30)

                          (:order-multi (40 (:name "Done today"
                                                   :and (:regexp "State \"DONE\""
                                                                 :log t))
                                            (:name "Clocked today"
                                                   :log t
                                                   )))
                          (:name "Waiting"
                                 :todo "WAITING"
                                 :order 20)
                          (:name "trivial"
                                 :priority<= "C"
                                 :tag ("Trivial" "Unimportant")
                                 :todo ("SOMEDAY" )
                                 :order 90)
                          (:discard (:tag ("Chore" "Routine" "Daily")))
                          ))
                       )))
         ) ; Super zaen view
        )))
```
(some note:
1. I let go of the timegrid for space saving
2. the org-agenda-property won't work
3. It's a TODO list, so "Done today" won't work (anyway to get around this?))

The idea of putting the org-super-agenda-view inside the org-custom-command-commands came from you! (It didn't work outside...) 
nevermind about the naming :D
Also, when I said
> Google tells me to customize org-agenda-custom-commands, yet I can't even bind a key to it, because I am using spacemacs, so there's literally no keys left to bind

turns out that I was actually talking about those commands you can trigger in the agenda buffer, like d for day view, or w for week, and I thought that's where I would be assigning the key ...

and the image:
![screenshot_20170929_184255](https://user-images.githubusercontent.com/13728568/31011942-08e6558c-a54b-11e7-9d82-a8ee2e890dbb.png)

(I've done working out!)

**Comment by alphapapa** [comment]
Hi again,

Thanks for sharing that.  Looks like you put a lot of work into it.

> the org-agenda-property won't work

Sorry, I don't know what you mean.  I see the variables you set up there, but I can't find those in Org, so I'm not sure they still exist.

> It's a TODO list, so "Done today" won't work (anyway to get around this?))

You need to enable log mode.  Press `l` in an agenda buffer, or you can set a variable to enable it automatically.

> The idea of putting the org-super-agenda-view inside the org-custom-command-commands came from you! (It didn't work outside...)

You just need to set `org-super-agenda-groups` globally and enable `org-super-agenda-mode`.

Thanks very much for the screenshot.  I'll add it to the examples!

**Comment by zaen323** [comment]
Oops, my apologies, I was talking about a package I found on github, (it's here: https://github.com/Malabarba/org-agenda-property btw) and, there was obviously no way that you could figure it out. (Just an excuse for being too late... xD)

> You just need to set org-super-agenda-groups globally and enable org-super-agenda-mode

Strangely enough, it just didn't work. I will have to put it in the (all-todo ... ) block. My guess though, it might be unique to spacemacs.

> You need to enable log mode. Press l in an agenda buffer, or you can set a variable to enable it automatically.

When I do that, it says you can't do it in to-do type agenda buffers... OH that means I can do it in the time-grid one! (literally just discovered this.) thanks man!

So, the new version:
![screenshot_20171001_182804](https://user-images.githubusercontent.com/13728568/31053351-634159f0-a6d6-11e7-916e-655467eaa086.png)

And its code (without the property thing, sorry again for the confusion):
  (setq org-agenda-time-grid
        '((daily today require-timed)
          "----------------------"
          ()))

  (setq org-agenda-skip-scheduled-if-done t)
  (setq org-agenda-skip-deadline-if-done t)
  (setq org-agenda-include-deadlines t)
  (setq org-agenda-include-diary t)
  (setq org-agenda-block-separator nil)
  (setq org-agenda-compact-blocks t)
  (setq spacemacs-theme-org-agenda-height nil)
  (setq org-agenda-start-with-log-mode t)
  (add-hook 'org-agenda-mode-hook '(lambda() (hl-line-mode 1)))


  (setq org-agenda-custom-commands (list(quote
        ("z" "Super zaen view" (
                                (agenda "" ((org-agenda-span 'day)
                      (org-super-agenda-groups
                       '((:name "Today"
                                :time-grid t
                                :date today
                                :todo "TODAY"
                                :scheduled today
                                :order 1
                                )))))
          (alltodo "" ((org-agenda-overriding-header "")

                       (org-super-agenda-groups
                        '((:name "Next to do"
                                 :todo "NEXT"
                                 :order 1)
                          (:name "Important"
                                 :tag "Important"
                                 :priority "A"
                                 :order 6)
                          (:name "Due Today"
                                 :deadline today
                                 :order 2)
                          (:name "Due Soon"
                                 :deadline future
                                 :order 8)
                          (:name "Overdue"
                                 :deadline past
                                 :order 7)
                          (:name "Assignments"
                                 :tag "Assignment"
                                 :order 10)
                          (:name "Issues"
                                 :tag "Issue"
                                 :order 12)
                          (:name "Projects"
                                 :tag "Project"
                                 :order 14)
                          (:name "Emacs"
                                 :tag "Emacs"
                                 :order 13)
                          (:name "Research"
                                 :tag "Research"
                                 :order 15)
                          (:name "To read"
                                 :tag "Read"
                                 :order 30)
                          (:name "Waiting"
                                 :todo "WAITING"
                                 :order 20)
                          (:name "trivial"
                                 :priority<= "C"
                                 :tag ("Trivial" "Unimportant")
                                 :todo ("SOMEDAY" )
                                 :order 90)
                          (:discard (:tag ("Chore" "Routine" "Daily")))
                          ))
                       )))
         ) ; Super zaen view
        )))

##### diff:
* removed the Done today section, since now the agenda part can handle it
* added (setq org-agenda-start-with-log-mode t)]

and last time forgot, without super mode it looks like this:
![screenshot_20171001_182843](https://user-images.githubusercontent.com/13728568/31053505-b311f87e-a6d9-11e7-99b4-d30d151d76a5.png)

Yuck! where did all these books come from?
without being organized, my brain will instantly shut it self down and play rimworld. AND THAT'S WHY I LOVE SUPER AGENDA AHAHAAHAHA
 
Cheers :)

**Comment by alphapapa** [comment]
> Oops, my apologies, I was talking about a package I found on github, (it's here: https://github.com/Malabarba/org-agenda-property btw) and, there was obviously no way that you could figure it out. (Just an excuse for being too late... xD)

Haha, no prob.  I actually have that repo starred but I had forgotten about it.

> > You just need to set org-super-agenda-groups globally and enable org-super-agenda-mode
> Strangely enough, it just didn't work. I will have to put it in the (all-todo ... ) block. My guess though, it might be unique to spacemacs.

Hmm, maybe so...

> When I do that, it says you can't do it in to-do type agenda buffers... OH that means I can do it in the time-grid one! (literally just discovered this.) thanks man!

Yep.  :)

> Yuck! where did all these books come from?  without being organized, my brain will instantly shut it self down and play rimworld. AND THAT'S WHY I LOVE SUPER AGENDA AHAHAAHAHA

LOL, yep.  I play RimWorld too!  I haven't tried it in a while, though.  Are the new updates fun?

**Comment by zaen323** [comment]
Oh I just started out fairly recently, so no idea how was it before the update. :)

**Comment by alphapapa** [comment]
@zaen323 Finally added your example.  :)  Thanks.
