### ISSUE TITLE
Excluding diary entries

### ISSUE THREAD

**Issue by promisedlandt** [alphapapa/org-super-agenda#200]
Hello,

I have a simple TODO in my main org file to send an email to my accountant on the first day of every month.
It uses `diary-date` and looks like this:
```
*** TODO Send accounting mail
    <%%(diary-date t 1 t)>
```
(I have omitted the body).

The daily portion of my super agenda shows it just fine, but it also shows up under Todos, despite my trying to discard it with ` (:discard (:scheduled t)`.
I guess that makes sense, as it does not have a `SCHEDULED:` property, but do you have any other idea how I can filter it out?

```
(setq org-agenda-custom-commands
      '(
        ("a" "Overview"
         (
          (agenda ""
                  ((org-agenda-overriding-header "Life")
                   (org-agenda-span 'day)
                   (org-super-agenda-groups
                     '(
                       (:name "Daily"
                              :anything) ; <--------- shows up fine here
                       )
                     )))
          (todo "INPROGRESS"
                ((org-agenda-overriding-header "In Progress")
                )
                )
          (todo "TODO"
                ((org-agenda-overriding-header "Quests")
                 (org-super-agenda-groups
                   '(
                     (:discard (:scheduled t)) ; <---------- Does not get discarded here
                     (:name "Immediate"
                            :priority "A"
                            )
                     (:name "High priority"
                            :priority "B"
                            :order 2
                            )
                     (:name "Low priority"
                            :priority "D"
                            :order 4
                            )
                     (:name "Eventually"
                            :priority "E"
                            :order 5
                            )
                     (:name "Normal priority" ; <---------- Gets displayed here, sadness
                            :not (:priority ("A" "B" "D" "E"))
                            :order 3
                            )
                     )
                   )))
          )
         )
        )
      )

```

**Comment by alphapapa** [comment]
You can use `:discard` with any of these selectors: https://github.com/alphapapa/org-super-agenda#normal-selectors  So just pick one that could match that entry and use it.

**Comment by promisedlandt** [comment]
Right, so `:scheduled` matcher not working is expected?
I guess I can tag all diary-date entries and discard that tag everywhere I discard scheduled, thanks.

**Comment by alphapapa** [comment]
> Right, so `:scheduled` matcher not working is expected?

Yes, since the entry is not scheduled, it shouldn't match.

> I guess I can tag all diary-date entries and discard that tag everywhere I discard scheduled, thanks.

There are probably various ways you could do it.  For one, try something like `:time-grid t`; that will probably work.  If not, you could use the `:regexp` matcher to match against `<%%`.  Tagging is another option, but probably not necessary.

**Comment by promisedlandt** [comment]
> What's the difference between entries like that and the one you want to remove? They both have diary sexps outside of an Org planning property line

It's very possible there is no difference and I have not seen them because I have not reached their particular day yet. Good to know. Either way, I prefer having those "false positives" since they are easy to identify. I will not write my todos like that anymore,  that was a very good hint :smile: : 

Thanks for the FAQ entry, I will go from multiple org agenda groups with org-super-agenda subgroups to just org-super-agenda groups.
