### ISSUE TITLE
Changing auto-parent group ordering

### ISSUE THREAD

**Issue by rychipman** [alphapapa/org-super-agenda#201]
Hello! Thank you for some amazing elisp packages! `org-ql` and `org-super-agenda` in particular practically run my life!

I have been tweaking my `org-ql` agendas, and ran into a question about `:auto-parent`. Specifically, it appears that groups generated by `(:auto-parent t)` are always ordered lexicographically by heading, and I'm wondering whether it is possible to customize this order somehow. Some initial investigation into the `org-super-agenda` code didn't turn up anything obvious.

If it matters/helps, I'm creating these groups via `org-ql-search`:
```
  (org-ql-search (org-agenda-files)
	`(and (todo)
		  (not (tags "prj"))
		  (or (scheduled :to ,day)
			  (deadline)
			  (not (scheduled))))
	:title "Planning Dashboard"
	:sort '(scheduled priority todo)
	:super-groups `((:name "Recurring Tasks"
						   :tag "recur")
					(:name "Previously Scheduled"
						   :scheduled past)
					(:name "Scheduled Today"
						   :scheduled today)
					(:name "Deadlines"
						   :deadline t)
					(:auto-parent t)))
```

**Comment by alphapapa** [comment]
Hi,

Thanks for the kind words.  I'm glad they're useful to you.

Regarding sorting, please see #166.

**Comment by rychipman** [comment]
It looks to me like #166 discusses the sorting of entries within a group; I realize now that my original message didn't make this completely clear, but what I'm trying to find a way to do is change the order of the groups themselves. The example `org-ql-search` invocation I gave above might result in an agenda like the following:
```
Recurring Tasks
 TODO A recurring task

Scheduled Today
 TODO A task scheduled for today

Project A
 TODO Some Task

Project B
 TODO Another Task

Project C
 TODO Yet Another Task
```

Here, the `Project A`, `Project B`, and `Project C` groups are the ones generated by `(:auto-parent t)`. AFAICT, these three groups will always appear in the same order. I'm trying to discover if it is possible to make them appear in a different order (perhaps ordered by priority of the parent heading or some other predicate).

Do you know if there's any way that this could be accomplished (either by using some existing org-ql/org-super-agenda feature or via some elisp hacking)?

**Comment by alphapapa** [comment]
Please see #159.  If that still isn't it, please search all issues (including closed ones) for "sort".  If you still don't find an answer, please let me know.

**Comment by rychipman** [comment]
This does answer my question -- thanks for the help!

**Comment by alphapapa** [comment]
Thanks.  FYI, my long-term plan is to improve `org-ql-view` to be more powerful (e.g. having nested groups and sorting of them).  Of course, `org-super-agenda` would remain useful for `org-agenda`, but rather than put a lot of effort into rewriting this package to add features like this, I'd rather put it into `org-ql-view` and a more powerful solution.
