### ISSUE TITLE
Show TODO checkboxes in agenda view?

### ISSUE THREAD

**Issue by shakthimaan** [alphapapa/org-super-agenda#202]
Would it be possible to show the TODO or IN_PROGRESS checkbox entries in the agenda view if the parent task is scheduled? For example:

*** Test
    SCHEDULED: <2021-08-31 Tue>
    - [  ] TODO  One
    - [  ] TODO Two
    - [  ] Three

The present agenda view only shows Test (heading), but, not One and Two. Sometimes, I don't want to necessarily create a separate heading just for a sub-task, but, would like to see what is the pending TODO or IN_PROGRESS work.

**Comment by alphapapa** [comment]
This package is not responsible for items' appearance, only for grouping them together.
