### ISSUE TITLE
org-agenda-deadline-leaders (e.g. "In %3d d.:") missing from org-super-agenda view

### ISSUE THREAD

**Issue by workcomplete** [alphapapa/org-super-agenda#205]
As the titles says, I can't get org-super-agenda to display the number of days until a future deadline. I have set DEADLINE and SCHEDULING information to appear in org-agenda-prefix-format, but nothing relating to the deadline appears. On Doom Emacs.

org-agenda-prefix-format
      '((agenda . "%?-12t% s")
       (todo . "% s")
       (timeline . " % s")
       (tags . "%s %i ")
       (search . " %i %-12:c "))`

Any pointers would be highly appreciated!

Full config below

**Comment by alphapapa** [comment]
This package has nothing to do with formatting of items.
