### ISSUE TITLE
bug on groups when I change `SCHEDULED` 

### ISSUE THREAD

**Issue by noghartt** [alphapapa/org-super-agenda#208]
I have this example of variable:
```elisp
(use-package! org-super-agenda
  :after org-agenda
  :config
  (org-super-agenda-mode)
  (setq org-super-agenda-groups
        '((:name "Today"
          :time-grid t
          :scheduled today))))
```

When I change from:

```org
* TODO Something
  SCHEDULED: <2021-10-08 Fri>
```

to:
```
* TODO Something
  SCHEDULED: <2021-10-08 Fri 15:00-15:30>
```

They change from `Other itens` to `Today`'s group on `org-agenda`. I think that it should be stay on `Other itens`, no?
If I inset any hours on this timestamp occurs the same thing, it's correct?

**Comment by alphapapa** [comment]
Please see the documentation for the `:time-grid` selector.
