### ISSUE TITLE
Spacing after final group per day

### ISSUE THREAD

**Issue by funnell** [alphapapa/org-super-agenda#209]
Hello,

I'm looking for a way to add spacing after the final group per day.
This is similar to previous issues raised (#62 #74), except that I'm not asking about adding spacing between every day (which would rightly be in org-agenda as you've pointed out).

<img width="541" alt="image" src="https://user-images.githubusercontent.com/381464/137210699-a96b5000-67b6-4eec-a7b3-dc0bcc7bab21.png">

In the above example I'm generally happy with the spacing, except I'd love to put a space or two between the final group each day and the date line that comes immediately afterwards (I know there's only one group per day in this particular screenshot).

In my head I'm thinking there could be a setting for a final group separator. What do you think? I don't know lisp or emacs very well but happy to make a pull request with some help/pointers if you're interested.

Thank you for your help and for a wonderful package!

**Comment by alphapapa** [comment]
Hi Tyler,

Sure, I don't see why we couldn't add an option to do that.  A PR would be welcome, and I'll be glad to help you along the way.  Thanks.
