### ISSUE TITLE
Recent `org-super-agenda` version errors on building agenda

### ISSUE THREAD

**Issue by 501st-alpha1** [alphapapa/org-super-agenda#21]
I attempted to update `org-super-agenda` to the latest version from GitHub today (specifically commit 00b0dbb), but after doing so, my super agendas no longer work, and I get the following error when building the agenda:

```
if: Unknown upattern `(quote none)'
```

I also get the following errors when loading `org-super-agenda`:

```
Compiler-macro error for cl--block-wrapper: (error "Unknown upattern `(quote t)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote t)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote past)'") [3 times]
Compiler-macro error for cl--block-wrapper: (error "Unknown upattern `(quote todo)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote todo)'")
Compiler-macro error for cl--block-wrapper: (error "Unknown upattern `(quote t)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote t)'")
```

but these also occur in the working version, so they may not be related.

I did a `git bisect`, and the first bad commit is b756b932245adeb950a2bd4d3f8eec983d5caf66.

Output of `M-x emacs-version`:

```
GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2017-09-12 on hullmann, modified by Debian
```

and `M-x org-version`:
```
Org mode version 9.0.5 (release_9.0.5-473-g54e107 @ /path/to/org/mode)
```

**Comment by alphapapa** [comment]
Hi,

Sorry, it requires Emacs 25.1.  I sympathize, because I also use Ubuntu/Debian stable releases, and their Emacsen tend to be older versions.  But it's not hard to build and install a deb for a newer version, and the new features available in Emacs 25 make some things much easier.  If you need some help installing a newer Emacs, I might be able to lend a hand.

**Comment by 501st-alpha1** [comment]
Okay, no prob.  I suppose I'll have to get around to doing that then. 😬  For my non-server computers, I usually try to stay on the `testing` Debian release, but I've gotten a little behind recently.  Looks like if I do upgrade to Buster [there is a package for Emacs 25](https://packages.debian.org/buster/emacs25).
