### ISSUE TITLE
Q: Escape hatch to eval some elisp to build groups?

### ISSUE THREAD

**Issue by justinabrahms** [alphapapa/org-super-agenda#211]
I'm trying to do some weird filtering (auto-property based on the PROJECT property [doable], but not if the DEFERRED_UNTIL property is in the future [much harder?]). I'm thinking it would be useful to be able to drop into elisp with something like:

```
(:and (auto-property PROJECT)
  (:discard (lambda (headline-object) ....)))
```
wherein I could define that lambda to exclude things.

Or even:

```
(:discard (lambda ...))
(auto-property PROJECT)
```

Is there a facility for this? I didn't find it from looking.

**Comment by alphapapa** [comment]
Hi,

What about the `:pred` selector?

**Comment by justinabrahms** [comment]
Finally getting around to trying this out. It seems like I get a bunch of text properties, but what I'm actually after is the org object that has various inherited properties on it. Is there a way to get there from the information passed into `:pred`?

This is what I'm seeing on an `M-x describe-text-properties` on a given headline.

<img width="848" alt="Screen Shot 2022-05-14 at 09 38 19 " src="https://user-images.githubusercontent.com/3853/168440782-1b0b45cc-c88c-4adb-a46e-1f2984c7e5b1.png">

**Comment by alphapapa** [comment]
That's the way Org Agenda works: each item is a string with various properties on it.  If you need more than what is in those properties, you'll need to use the marker to access the item at its location in its buffer.  You can see some code in this package that does that.
