### ISSUE TITLE
:auto-parent group headers have leading spaces corresponding to outline level

### ISSUE THREAD

**Issue by max6166** [alphapapa/org-super-agenda#217]
I have an agenda which uses `:auto-parent`.  The `org-super-agenda-header` for nested items is indented with a space for each outline level the original header is nested. The items listed below the group header are fine and do not have leading spaces.

The group headers created by the `:auto-category` and `:auto-property` selectors do not have this problem. 

It looks something like this
```
    Header 1
Item
Item

 Header 2
Item

     Header 3
Item
Item
Item
```

This is the custom agenda I have been testing with.
```
     ("Z" "Test" agenda "daily"
       (
         (org-agenda-prefix-format "")
         (org-super-agenda-header-prefix "")
         (org-super-agenda-groups
           '(
              (:auto-parent)
              )
           )
         )
       )
```

**Comment by alphapapa** [comment]
Thanks.  This should probably be simple to fix, but I may not have time to work on it soon.

**Comment by alphapapa** [comment]
I can't reproduce this problem using Emacs 29.4, Org 9.7.5, and org-super-agenda from `master`.
