### ISSUE TITLE
Can you use auto-catgeory half way in your groups?

### ISSUE THREAD

**Issue by DominikMendel** [alphapapa/org-super-agenda#218]
Great package, thank you for it! 

This might be more so a question rather than a bug. I would like to use something like `:auto-category` in my `org-super-agenda-groups`, but only after a certain point. 

For example, I want my "INPROGRESS"s to be normal, but everything else as a TODO to then be grouped with `:auto-category t` if able. 

```
        (:name "Currently Open"
         :todo "INPROGRESS"
         :order 1)
        (:name "Open Items"
         :todo "TODO"
         :auto-category t
         :order 2)
```
This is a simple example, but hopefully I get my point across of how I want to begin the `auto-category` halfway into my groupings. 

Any insight into this problem would be great.

**Comment by DominikMendel** [comment]
Ah, I have figured it out! Sorry. For future reference, you can add this in a `:order-multi` block. 
An example from my config:
```
        (:order-multi (3 (:auto-category t)
                       (:name "Current Tasks"
                          :todo ("INPROGRESS" "IN-REVIEW"))
                         (:name "Open Tasks"
                          :todo "TODO")))

```
Note that the `:name "..."` won't be used since the `:auto-category t` will name the groups.

**Comment by alphapapa** [comment]
Thanks for sharing the solution you found.  :)
