### ISSUE TITLE
Wrong parent headers

### ISSUE THREAD

**Issue by haji-ali** [alphapapa/org-super-agenda#231]
I believe there's a bug in `org-super-agenda--when-with-marker-buffer` that results in the wrong parent headers (among other issues) when there's a restriction on the org buffer associated with the agenda. The reason is that the buffer is not `widen`'ed before calling `goto-char`. To resolve this, consider this patch.

```patch
diff --git a/org-super-agenda.el b/org-super-agenda.el
index 9e665cd..fad3436 100644
--- a/org-super-agenda.el
+++ b/org-super-agenda.el
@@ -237,7 +237,7 @@ considerable, depending on the number of items."
     `(let ((,marker ,form))
        (when (markerp ,marker)
          (with-current-buffer (marker-buffer ,marker)
-           (save-excursion
+           (org-with-wide-buffer
              (goto-char ,marker)
              ,@body))))))
```

**Comment by alphapapa** [comment]
Thanks for the report.  I'll take a look at this when I have time.

**Comment by alphapapa** [comment]
Finally fixed.  Thanks.
