### ISSUE TITLE
Cannot find file org-super-agenda-autoloads？

### ISSUE THREAD

**Issue by Prague2049** [alphapapa/org-super-agenda#232]
Error loading autoloads: (file-missing Cannot open load file No such file or directory /Users/apple/.emacs.d/elpa/org-super-agenda-20220826.2315/org-super-agenda-autoloads).
My emacs is 28.1 and my org is 9.5.3.
The config file in init.el is as follows
;;;org-super-agenda版本
(add-to-list 'load-path "/Users/apple/.emacs.d/elpa/org-super-agenda-20220826.2315")

;;;; org-super-agenda 定义agenda review 的格式
(require 'org-super-agenda)

**Comment by alphapapa** [comment]
You have not installed the package correctly.  Use the `package-install` command.
