### ISSUE TITLE
Traces of old agenda

### ISSUE THREAD

**Issue by wjbg** [alphapapa/org-super-agenda#24]
Hi! 

Thanks for this supercharged agenda! It is exactly what I was looking for. However, I seem to have problems getting it to work properly. Or at least that is what I think. I've used tried this example:
```
(let ((org-super-agenda-groups
       '((:auto-category t))))
  (org-agenda-list))
```
As you can see I have two agenda files `overview.org` and `outlook_day.org`. The grouping works fine, but the agenda view shows traces of the standard agenda:

![image](https://user-images.githubusercontent.com/29379051/32982472-aabc963a-cc85-11e7-93cf-4bd52523b0b5.png)

Is this supposed to be the case or am I doing something wrong here?

I am using Org-mode version 9.1.2 and org-super-agenda version 2017/09/04. 

Thanks in advance!
Wouter

**Comment by alphapapa** [comment]
Hi Wouter,

I'm glad you're enjoying it!  :)

I'm sorry, I don't understand what you mean by traces of the standard agenda.  It appears to be working correctly.  Do you mean the timeline under "Other items"?  If so, you probably want to put that in a separate section.  You can use selectors to do that.  I recommend looking at the examples, which should help you figure it out.  If not, let me know exactly what you're trying to achieve and we can figure it out.

**Comment by wjbg** [comment]
Thanks for swift response!

I was indeed referring to the timeline under "Other items" and was under the impression that it would be gone if not explicitly called for via `:time-grid t`. I'll indeed put it in a separate section. Thanks and apologies for bothering you.

**Comment by alphapapa** [comment]
Not at all, always glad to hear from someone who's finding this useful.  :)  Please feel free to contribute an example once you get it configured the way you like it.
