### ISSUE TITLE
There is error -remove: Symbol’s function definition is void: s-blank-str?

### ISSUE THREAD

**Issue by Prague2049** [alphapapa/org-super-agenda#240]
When I used M+x  org-agenda, org Agenda shows the following image, which does not show my todo time plan.
<img width="499" alt="image" src="https://user-images.githubusercontent.com/86907530/216238644-dfcc3624-8bc5-4c46-8b8c-19d165ec93ba.png">
and same time there is error :-remove: Symbol’s function definition is void: s-blank-str? in the Messages buffer.
My emacs is emacs-plus@30, and org version is 9.6.1. mac 
when I set org-super-agenda-mode disable. I can get the org agenda as follow:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/86907530/216239377-2dc178ac-d8b0-41cf-b7b3-5616a8761074.png">
How to deal with this error?

**Comment by alphapapa** [comment]
That error indicates that dependency libraries are missing, which indicates that the package has not been installed correctly.  In other words, you need help fixing your Emacs configuration, which I can't provide here.  Please seek help in an appropriate forum, like reddit.com/r/emacs, #emacs:matrix.org, etc.
