### ISSUE TITLE
question on using org-ql 

### ISSUE THREAD

**Issue by pcompassion** [alphapapa/org-super-agenda#249]
I wanted to keep the questions short. 
I'm asking anyway because it shows where I have trouble understanding.   
I'm not expecting to get answers to all the questions.

1. is it possible to use org-ql query with org-super-agenda ?
org-super-agenda seem to use different syntax (or different framework of selecting items) than org-ql 

2. There is agenda-like-view and it uses org-ql,
https://github.com/alphapapa/org-ql/blob/master/examples.org#agenda-like-view
and org-super-agenda is agenda-view (not agenda-like-view) and org-ql is not allowed? 

3. meaning of 'selector' and 'group' 

> ‘:todo’
>      Group items that match any of the given TODO keywords.  Argument
>      may be a string or list of strings, or ‘t’ to match any keyword, or
>      ‘nil’ to match only non-todo items.

Does `Group` mean `select`? 

> ‘:auto-parent’
>      This automatically groups items by their parent heading.

Here, it seems to suggest `Group` means `Group`

> ‘:time-grid’
>      Group items that appear on the time grid.

Here, I can't tell what it means. (I dont know what time grid is)

> ‘:pred’
>      Group items if any of the given predicate functions return non-nil
>      when called with each item as a string from the agenda buffer ().

I can't tell whether `Group` here means `Select` or `Group`

here's my guess answer to my questions.

1. org-ql is possible (if used in `:pred`) but not advised 

2. org-ql-search is a view and org-super-agenda is an agenda view and they are different

(not sure if I can use org-ql-search view as a source for org-super-agenda, but i guess not)

3. select / group

My guess is that, in org-super-agenda, each block shows an item only once.   
And when an item is matched (selected) by selectors (such as `:todo`) , it is consumed
so this model is not compatible with `org-ql` where matching item can appear multiple times.

and there's Grouping (such as `:auto-todo`, and this is not selector (which selects items))

 Each selector is combined with `or` , which means item is consumed with each selector
So

>  :date today
>  :deadline today

:deadline is not meaningful, because `:date today` already selected all items `:deadline today` would

If I want to apply `and` so that conditions get `and-ed` I would combine everything in a single `:and` otherwise implicit `:or` would defeat the `:and`

**Comment by alphapapa** [comment]
I'm afraid I don't really have time to answer so many questions at once.  As well, this issue tracker is for tracking bug reports and feature requests, not for support questions.  Please ask on a more appropriate forum, like https://old.reddit.com/r/orgmode/ or https://old.reddit.com/r/emacs/ or https://matrix.to/#/#org-mode:matrix.org or https://lists.gnu.org/archive/html/emacs-orgmode/

Regarding the use of `org-ql` with `org-super-agenda`, it's designed to work the other way: see https://github.com/alphapapa/org-ql/blob/master/examples.org#agenda-like-view

**Comment by pcompassion** [comment]
I totally understand, will try to sort this out and try to help documenting somewhere maybe.

Yes I saw https://github.com/alphapapa/org-ql/blob/master/examples.org#agenda-like-view

I'll try that example, then probably many things will be clearer
