### ISSUE TITLE
is there a way to sort the "Other" group by timestamp ? 

### ISSUE THREAD

**Issue by maxandersen** [alphapapa/org-super-agenda#25]
I'm probably missing something obvious but is it somehow possible to have the "Other items" sorted by the timestamp in them (newest first) and optimally showing how "old" they are ?

Right now it seem to just sort alphabetically by the file name they are in.

**Comment by alphapapa** [comment]
Hi,

This package doesn't change the sort order, it just groups items that have already been put into the agenda.  To change the sort order, use the built-in agenda sorting.

**Comment by maxandersen** [comment]
yeah, I just realized setting `org-agenda-sorting-strategy` helps here. thanks for that ;)
