### ISSUE TITLE
Why does an agenda window automatically open every time I start emacs after installing the plug-in "org-super-agenda"? How can I prevent this behavior?

### ISSUE THREAD

**Issue by arstum** [alphapapa/org-super-agenda#252]
Why does an agenda window automatically open every time I start emacs after installing the plug-in "org-super-agenda"? How can I prevent this behavior?

**Comment by arstum** [comment]
(setq org-super-agenda-show-message nil) no effect

**Comment by alphapapa** [comment]
There is no code in `org-super-agenda` to that effect.  You have a configuration problem.  Please use an appropriate forum to ask for help with that problem.
