### ISSUE TITLE
Sort order within a group: "Wrong type argument: sequencep, :auto-ts"

### ISSUE THREAD

**Issue by novoid** [alphapapa/org-super-agenda#256]
Org mode version 9.6.12
org-super-agenda 1.4-pre
Latest NixOS

I'm trying to modify the sort order of items within a group. Currently, [with my config](https://github.com/novoid/dot-emacs/blob/master/config.org) my agenda is shown like that:

![image](https://github.com/alphapapa/org-super-agenda/assets/727493/abe09774-5fc6-4096-8dfd-fb0b207f95a2)

I'd prefer the sort order of those overdue items reversed: first, the scheduled for today items, then the 24x, then the 36x and so forth until the last one: 351x in this case.

For that, I actually only found one potential candidate `:auto-ts` and so I played around by modifying this working line:

```
(:name "Started"
 :and (:todo "STARTED" :not (:tag "someday") :not (:priority "C") :not (:priority "B") ) 
 :order 10)
```

... to that:

```
(:name "Started" 
 :and (:todo "STARTED" :not (:tag "someday") :not (:priority "C") :not (:priority "B") )
 :order 10
 :auto-ts)
```

... or:

```
(:name "Started"
 :and (:todo "STARTED" :not (:tag "someday") :not (:priority "C") :not (:priority "B") )
 :order 10
 :auto-ts "reverse")
```

Which causes in both cases:

```
if: Wrong type argument: sequencep, :auto-ts
```

What is my error here? I do seem to use it in a wrong way.

**Comment by alphapapa** [comment]
Hi Karl,

The auto selectors can't be combined with other selectors using `:and` like that.  The auto selectors make their own groups based solely on the values they find.

Note as well that org-super-agenda does not control the order in which items are sorted.  The `reverse` argument to `:auto-ts` controls the order of the groups, not the items.

**Comment by novoid** [comment]
Okay, then I did get it totally wrong, as it seems. You may as well close the issue then.

When you say that org-super-agenda doesn't handle the order of items within a group: do you have a hint how I may influence that order with a different approach?

Thanks.

**Comment by alphapapa** [comment]
> When you say that org-super-agenda doesn't handle the order of items within a group: do you have a hint how I may influence that order with a different approach?

If you're using `org-agenda` commands, then with the standard Org Agenda sorting controls.  If you're using `org-ql`, with its `:sort` argument.

**Comment by novoid** [comment]
I see. I really have to think of switching to org-ql based agenda. Thanks for clarification and throwing me in the right direction.

**Comment by alphapapa** [comment]
You're welcome.
