### ISSUE TITLE
Root items of outline-path look like they're part of the previous group

### ISSUE THREAD

**Issue by gsingh93** [alphapapa/org-super-agenda#258]
I have a file that looks like this:
```
* Heading 1
** TODO [#A] Item 1
* Heading 2
** TODO Item 2
* TODO Heading 3
```

I have `org-super-agenda-groups` set like this:
```elisp
(setq org-super-agenda-groups
      '((:priority "A")
        (:auto-outline-path t)))
```

The agenda output looks like this:
```
 Priority A items
  org-super-agenda-test:TODO [#A] Item 1
  org-super-agenda-test:TODO Heading 3

 Heading 2
  org-super-agenda-test:TODO Item 2
```

It visually looks like "Heading 3" is part of the Priority A group, which is a bit confusing. Ideally, it would be nice if there was some name for the root heading instead of it being blank, i.e.:
```
 Priority A items
  org-super-agenda-test:TODO [#A] Item 1
  
 <ROOT>  
  org-super-agenda-test:TODO Heading 3

 Heading 2
  org-super-agenda-test:TODO Item 2
```
And maybe there's a better default heading than `<ROOT>`, I don't know or have a strong preference.

A less ideal alternative would be if there was just a bit of extra blank space between the outline-path group and the previous group.

**Comment by alphapapa** [comment]
Thanks for reporting this.  I think the visual problem was caused by the top-level heading being sorted in an unexpected way.  Now the top-level headings will be placed into their own group.  See https://github.com/alphapapa/org-super-agenda/commit/17954dc4b064d7fb09719222045d31feae8aa923
