### ISSUE TITLE
Habits not see (

### ISSUE THREAD

**Issue by bimawa** [alphapapa/org-super-agenda#26]
Hi guys why my habits not work? i catch that error: 
``` 
(Spacemacs) Error in dotspacemacs/user-config: Invalid org-agenda-super-groups selector: :habit

```

**Comment by alphapapa** [comment]
Try this:
```el
(:name "Personal" :habit t)
```

**Comment by bimawa** [comment]
No, it's not helping. Still apear error.

**Comment by fuxialexander** [comment]
`org-agenda-super-groups`?

Shouldn't that be `org-super-agenda-groups`?

**Comment by bimawa** [comment]
Yes, other fields work fine. Maybe I configure habits in org mode wrong?

**Comment by alphapapa** [comment]
Here are some suggestions:

* Use `toggle-debug-on-error` and post a backtrace.
* Post your org-super-agenda configuration.
* Try using the example configuration in the readme.
* Post the versions of Emacs, org-mode, and org-super-agenda that you have.
* Post a minimal Org file that doesn't work properly.  For example:
```org
* Habit 1
:PROPERTIES:
:STYLE: habit
:END
```
See if that minimal file works correctly by setting the agenda restriction to that file and opening the agenda view on it.
* Try to reproduce with `emacs -q`, i.e. run `emacs -q`, load the package system, load `org`, load `org-super-agenda`, and see if it works.  If it does, you'll know it's a problem with your config.

**Comment by bimawa** [comment]
(use-package org-super-agenda :config (org-super-agenda-mode))
    (setq org-super-agenda-groups '((:log t) 
                                  (:name "Personal"
                                         :habit t)
                                  (:name "Schedule"
                                         :time-grid t)
                                  (:name "Today"
                                         :scheduled today)
                                  (:name "Due today"
                                         :deadline today)
                                  (:name "Overdue"
                                         :deadline past)
                                  (:name "Due soon"
                                         :deadline future)
                                  (:name "Unimportant"
                                         :todo ("SOMEDAY" "MAYBE" "CHECK" "TO-READ" "TO-WATCH")
                                         :order 100)
                                  (:name "Waiting..."
                                         :todo "WAITING"
                                         :order 98)
                                  (:name "Scheduled earlier"
                                         :scheduled past)))
     (org-agenda-list)



its my groups;
This error appears on any org file. if it's empty too.

>Use toggle-debug-on-error and post a backtrace.

nothing change in message layer i receive same:

     org-super-agenda-mode enabled.
     Appointment reminders enabled (no diary file found)
     Added 10 events for today
     (Spacemacs) Error in dotspacemacs/user-config: Invalid org-agenda-super-groups selector: 
     :habit

    Done.
    Press key for agenda command (unrestricted):
    user-error: Invalid org-agenda-super-groups selector: :habit
    Quit

>Post the versions of Emacs, org-mode, and org-super-agenda that you have.
 
i'm user spacemacs with emacs Version 25.3 (9.0)
org-mode version 9.0.1 elpa
org-super-agenda verstion i'm not found. But it's installed from elpa

**Comment by alphapapa** [comment]
I can't explain why that would happen.  Please post the value of the variable `org-super-agenda-group-types`.

**Comment by bimawa** [comment]
Guys found why its not work, i'm not set `org-modules` variable. Found instruction [here](http://pages.sachachua.com/.emacs.d/Sacha.html)

    (setq org-modules '(org-bbdb
                      org-gnus
                      org-drill
                      org-info
                      org-jsinfo
                      org-habit
                      org-irc
                      org-mouse
                      org-protocol
                      org-annotate-file
                      org-eval
                      org-expiry
                      org-interactive-query
                      org-man
                      org-collector
                      org-panel
                      org-screen
                      org-toc))
     (eval-after-load 'org
     '(org-load-modules-maybe t))

**Comment by alphapapa** [comment]
Ok, that explains it, because that selector is only defined when `org-habit` is actually loaded:

```el
(with-eval-after-load 'org-habit
  (org-super-agenda--defgroup habit
    "Group habit items.
Habit items have a \"STYLE: habit\" Org property."
    :section-name "Habits"
    :test (org-is-habit-p (org-super-agenda--get-marker item))))
```

**Comment by bimawa** [comment]
Yeah going the same way, thanks a lot for advices!
