### ISSUE TITLE
Items not showing on time grid as expected

### ISSUE THREAD

**Issue by floli** [alphapapa/org-super-agenda#261]
Hello,
I am using the "Agenda and all TODOs" as my primary view to interact with the agenda. However, I struggle to configure it with org-super-agenda.

My current config is
```
(setq org-super-agenda-groups
      '(
        (:name "In Progress"
               :todo "INPR" )
        (:name "Todo"
               :todo "TODO" )
        (:name "Waiting"
               :todo "WAIT" )))
```

which displays the undated TODOs nicely below the time grid, grouped by their state. But the items with a date associated are not displayed correctly:

![grafik](https://github.com/alphapapa/org-super-agenda/assets/1028028/ff5db535-b296-4a39-8db4-491eb64b95d1)

Enhancing my groups definition by a `time-grid` selector:

```
(setq org-super-agenda-groups
      '(
        (:time-grid t)
        (:name "In Progress"
               :todo "INPR" )
        (:name "Todo"
               :todo "TODO" )
        (:name "Waiting"
               :todo "WAIT" )))
```

fixes the agenda view but makes the "Global list of TODO items" printed ungrouped.

How can I have both, a time-grid with correctly placed icons for icons that have a date and a grouped global TODO list?

Thanks a lot and all the best!

**Comment by alphapapa** [comment]
Hi Florian,

I'm glad to hear that org-super-agenda may be helpful for you.  Unfortunately, I don't have enough time to offer one-on-one tutorial support on GitHub.  Instead, here's what I recommend:

1. See the FAQ to be sure that what it explains is understood: https://github.com/alphapapa/org-super-agenda?tab=readme-ov-file#faq
2. If that isn't enough, then I'd suggest asking for help on an appropriate forum, like https://old.reddit.com/r/orgmode/ where other users can offer help and benefit from the answers.  As well, make use of the search tools, as this kind of question has been asked many times before (here on this tracker, and on Reddit).  Also, the Web is full of blog posts where people show their org-super-agenda setups.

Thanks.
