### ISSUE TITLE
Entries without a timestamp can have a `dotime` text property and get pulled into `:time-grid` groups

### ISSUE THREAD

**Issue by floli** [alphapapa/org-super-agenda#264]
### OS/platform

Linux

### Emacs version and provenance

`GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.42, cairo version 1.18.0)`
Arch Binary Packages

### Emacs command

/usr/bin/emacs --init-directory=$PWD

### Org version and provenance

`Org mode version 9.7.6 (9.7.6-7a4527 @ /home/florian/Cloud.XGM/super-agenda/elpa/org-9.7.6/)`

### org-super-agenda package version and provenance

`org-super-agenda-20240630.18` installed via `package-install`

### Actions taken

`M-x org-agenda t`

### Observed results

```
Global list of TODO items of type: ALL
Press ‘N r’ (e.g. ‘0 r’) to search again: (0)[ALL] (1)DONE (2)TODO

 time-grid
  test:       TODO dated item
  test:       TODO undated item
```

### Expected results

I do not expect `undated item` to show up in section `time-grid`

### Etc.

Complete `init.el`:

```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(setq package-check-signature nil)

(setq org-directory "/home/florian/Cloud.XGM/super-agenda")
(setq org-agenda-files (list org-directory))


(use-package org-super-agenda
  :ensure t
  :config (progn
            (org-super-agenda-mode t)
            
            (setq org-super-agenda-groups
                  '(
                    (:name "time-grid"
                     :time-grid t)
                    (:name "Todo"
                           :todo "TODO" )
                    (:name "catch-all"
                           :anything t)
                    
                    )                  
                  )))
```

Example org-file:
```
* TODO dated item
SCHEDULED: <2024-07-04 Do 14:00>
* TODO undated item
```

Related discussion: https://www.reddit.com/r/orgmode/comments/1du90tx/superagenda_items_not_showing_on_time_grid_as/

**Comment by alphapapa** [comment]
Thanks.  Note that Org 9.6.15 is the version included with Emacs and is now well-outdated.  Please install the latest version of Org from GNU ELPA, restart Emacs, ensure that the newer version is loaded, and then see if this problem persists.

**Comment by floli** [comment]
Updated the original posting accordingly. The results did not change.

**Comment by alphapapa** [comment]
Thanks.

This appears to be a bug in Org Agenda's code.  As you can see here: https://github.com/alphapapa/org-super-agenda/blob/17954dc4b064d7fb09719222045d31feae8aa923/org-super-agenda.el#L455-L471 the `:time-grid` selector in org-super-agenda checks to see whether the line in the Agenda buffer has a `dotime` text property that is not an empty string.  

However, in the example you provided, when I press `C-u C-x =` on the `undated item` line in the Agenda buffer, I see that it has the `dotime` text property with the value `t`, the same as the `dated item`.  That appears to be incorrect, since the item has no "do time" (no timestamp at all, in fact).

**Comment by floli** [comment]
Great find! Do you take it to upstream or should I?

**Comment by alphapapa** [comment]
My time is very limited for these projects, so I'd appreciate it if you would.  I'd suggest asking on the Org mailing list.  Be advised that they might not consider this a bug, as here the implementation is the specification, and org-super-agenda isn't part of it.  The question is how we can determine whether a line is supposed to be on the time grid via the text properties, and AFAIK this used to work.

**Comment by yantar92** [comment]
> However, in the example you provided, when I press C-u C-x = on the undated item line in the Agenda buffer, I see that it has the dotime text property with the value t, the same as the dated item. That appears to be incorrect, since the item has no "do time" (no timestamp at all, in fact).

You are not right. DOTIME is simply storing the corresponding argument to the `org-agenda-format-item`. When it is something like `t' (or other non-string, non-nil value), it means that `org-agenda-format-entry` should search for time specification in the heading title. If org-super-agenda is expecting DOTIME to be a string or nil, its expectation is erroneous. 

I advice using `time-of-day` property instead.

Of course, all these things are undocumented, as it usually goes with the agenda.

**Comment by alphapapa** [comment]
@yantar92 Thanks.  Yes, it was all trial-and-error back when I was originally developing these features.  I don't know what changed between now and then, but at least it seems to work now (or we'll see what bug reports come in after this change).

@floli Please let me know if it works for you now.

**Comment by yantar92** [comment]
> I don't know what changed between now and then...
AFAIK, nothing changed. But `dotime` may have non-string values for certain types of agendas - ones you may not see frequently.

I am now rewriting that part of agenda. I hope to come up with something a bit more consistent. Or at least to document these things.

**Comment by alphapapa** [comment]
> I am now rewriting that part of agenda. I hope to come up with something a bit more consistent. Or at least to document these things.

Do you intend to make the rewrite backward-compatible with `org-super-agenda`?  I would not relish having to maintain a completely different set of selectors for different Org versions.

**Comment by yantar92** [comment]
I will deprecate some properties and remove them eventually (+1 major release after deprecation).

Below if WIP analysis on what is need and what is not needed. Things that are "unused" will be deprecated. Other things may also be deprecated after I look into rewriting the functions that use the relevant properties. Sometimes, properties are there for a single user function.

	      - [-] go through every text property and make sure that nothing is broken
		- [ ] org-heading
		  - somewhat similar to txt - use to extract title for comparison
		  - also used to highlight todo
		- [ ] txt
		  - used, need to review further
		- [X] format
		  - unsed
		- [X] time-of-day
		  - used when sorting
		- [ ] time
		  - [ ] Used in ~org-agenda-add-entry-to-org-agenda-diary-file~, which should be fixed anyway
		- [X] duration
		  - Used by ~org-columns--collect-values~
		- [ ] extra-space
		- [X] org-category
		  - used when sorting
		- [ ] tags
		  - set separately, for the whole buffer; ??? Potential problem
		- [ ] org-priority-highest
		- [ ] org-priority-lowest
		  - [ ] can get rid by rewriting fontification
		- [X] breadcrumbs
		  - unused
		- [ ] level
		  - org-agenda-do-in-region
		- [X] extra
		  - unused
		- [X] dotime
		  - unused
		- [X] org-marker
		  - used everywhere
		- [X] org-hd-marker
		  - used everywhere
		- [X] todo-state
		  - used for sorting
		- [X] ts-date
		  - used for sorting
		- [X] priority
		  - used for sorting
		- [ ] type
		  - used in org-cmp-ts
		  - also used by ~org-agenda-kill~ (why??)
		- [X] effort
		  - unused
		- [X] effort-minutes
		  - used for comparison
		- [X] urgency
		  - used for comparison
		- [ ] warntime
		  - used by ~org-agenda-to-appt~
		  - [ ] single user - may potentially query there
		- [ ] date
		  - [ ] org-fix-agenda-info need to study
		- [ ] undone-face
		- [ ] done-face
		  - both used in a single function ~org-agenda-change-all-lines~
		    - [ ] may it be factored out?
		- [X] org-habit-p
		  - used for comparison
		  - used by agenda habit integration
		- [ ] org-not-done-regexp
		  - [ ] only used by org-agenda-to-appt
		- [ ] org-todo-regexp
		  - used by org-agenda-to-appt
		  - [ ] org-fix-agenda-info (check what it does)
		  - [ ] org-agenda-highlight-todo
		  - [ ] used to compare heading titles, alphabetically ~org-cmp-alpha~
		- [X] org-complex-heading-regexp
		  - unused
		- [X] org-agenda-diary-link
		  - used to mark diary entries

**Comment by floli** [comment]
> @floli Please let me know if it works for you now.

I think so.

given the org file:
```
* TODO dated and timed item
SCHEDULED: <2024-07-16 Di 14:00>
* TODO dated item
<2024-07-16 So>
* TODO undated item
```

`time-grid` catches item that are to appear on the time-grid in the current view, i.e. using `org-agenda t` it catches no items at all, as there is no time grid. On `org-agenda a` it catches the `dated and timed item`, but not the `dated item`.

If that is the intended behavior, it works for me.

I will check if it fixed my original problem (see my original posting at reddit), but for that specific bug, it is fixed.

Best Thanks!

**Comment by Zweihander-Main** [comment]
FYI for others who might stumble on this:
The [commit fixing this issue](https://github.com/alphapapa/org-super-agenda/commit/05a710065af5ee4b3982f9619f864f7af12ca1d3) created what I initially thought was a regression but has actually stopped an unintended behavior. 

I have recurring all-day timestamp only items intended to only be seen once a week. Using the following custom command: 
``` elisp
  (add-to-list 'org-agenda-custom-commands
               `("1" "Agenda"
                 ((agenda ""
                          ((org-agenda-span 1)
                           (org-agenda-start-day "+0d")
                           (org-deadline-warning-days 365)
                           (org-super-agenda-groups
                            '((:name ""
                               :time-grid t)
                              (:name ""
                               :deadline past)
                              (:name ""
                               :deadline today)
                              (:name ""
                               :and (:deadline future
                                     :scheduled nil))
                              (:name ""
                               :scheduled past)
                              (:name ""
                               :scheduled today)
                              (:discard (:anything t)))))))))
``` 
and org items:
``` org-mode
* TODO [#A] This will come up on Mondays
<2024-09-02 Mon ++1w>
* TODO [#A] This will come up on Tuesdays
<2024-09-03 Tue ++1w>
```
Before the fix, one of those items would come up on the corresponding day through the `time-grid` and sit above the all-day scheduled/deadline items. After the fix, it's being discarded. 

Based on the above comments, this is the correct behaviour now given the items don't have a time of day. I can recreate what I previously had by changing the appropriate lines to: 
```elisp
                              (:name ""
                               :time-grid t)
                              ;; Adding the below
                              (:name ""
                               :not (:deadline t
                                     :scheduled t))

```
