### ISSUE TITLE
Make name of agenda-group property customisable

### ISSUE THREAD

**Issue by hmw42** [alphapapa/org-super-agenda#27]
Hi,

I already have Org's CATEGORY property set on some items. It has basically the same meaning: grouping child items together. It would be nice to re-use that (or any other property) for super agenda. I would like to have the name 'agenda-group' customisable instead of being hard coded.

Regards
hmw

**Comment by alphapapa** [comment]
Hi,

I'm not sure exactly what you mean.  I think what you're asking for is already provided by this:

> :auto-group This selects items that have the agenda-group Org property set. By setting this property for a subtree, every item in it will be sorted into an agenda group by that name and placed into the agenda where the :auto-group selector is

So you can have an Org file like this:

```org
* Heading
:PROPERTIES:
:agenda-group: foo
:END:
```
Then if you use the `:auto-group` selector, that subtree will appear in a `foo` group.

**Comment by hmw42** [comment]
Hello,

that's what I'm using, yes. But the name of the property ('agenda-group') is hard coded. I want it to be customisable. With the following Org file (and a customised group property name) I want to gain the same result as with the snippet you posted:

```
* Heading
:PROPERTIES:
:foobar: foo
:END:
```
With the patch attached I had to (setq org-super-agenda-group-property-name "foobar") and be ready to go. The reason that I want this is that I already have properties named foobar all over my Org files which hold a string that can act as a group name in super agenda. Just duplicating and renaming them to 'agenda-group' doesn't sound too appealing to me ;).

Regards
hmw


[customisable-group-property-name.patch.txt](https://github.com/alphapapa/org-super-agenda/files/1713345/customisable-group-property-name.patch.txt)

**Comment by alphapapa** [comment]
Ah, now I understand.  That seems like a good idea.  Would you be willing to send the patch as a PR that includes documentation and a changelog entry in the readme?

**Comment by hmw42** [comment]
Hello,
yes, I will do that next week.

Thank you
hmw
