### ISSUE TITLE
Can't combine auto-* selector with normal selectors.

### ISSUE THREAD

**Issue by mtbar131** [alphapapa/org-super-agenda#271]
### OS/platform

Ubuntu 22.04.4

### Emacs version and provenance

27.1

### Emacs command

emacs

### Org version and provenance

9.3 (installed with MELPA)

### org-super-agenda package version and provenance

20240916.1753

### Actions taken

Create a group config like below:

```
(setq org-super-agenda-groups '(
				(:and (:auto-property "PROJECT_ID"
				      :todo "TODO"))))
```

### Observed results

`org-todo-list` fails with `s-join: Wrong type argument: sequencep, :auto-property` error.

### Expected results

Expected behavior is to group tasks based on "PROJECT_ID" and the TODO state.

**Comment by alphapapa** [comment]
Hello,

I'm afraid there is a misunderstanding here.  The auto selectors cannot be combined with other selectors, because they create an undefined number of groups at runtime.  This is simply a limitation of the design.  Someday, my `taxy` library may provide an alternative implementation that would remove this restriction.

**Comment by mtbar131** [comment]
I see. Currently is there any way to group elements by the name of the top level headline that it is under? 

I want to group items based on the project that they are in. Every project is top level headline and it has multiple tasks and subtasks as the second or third level headlines. In my org agenda view I want to group the tasks that are all a part of the same top level headline, only select those tasks that are in the "TODO" state and limit to top 3 tasks in each group. 
`auto-parent` / `auto-outline-path` can kind of do this right now but then I am not able to filter based on the state of the task. I am fairly new to org-mode and org-super-agenda so I might have missed something.

Thanks for your help!

**Comment by alphapapa** [comment]
Please see the `:ancestor-with-todo` selector.
