### ISSUE TITLE
org-agenda-show-log-scoped

### ISSUE THREAD

**Issue by jave** [alphapapa/org-super-agenda#3]
I cant seem to find org-agenda-show-log-scoped. Where should it be defined?

**Comment by alphapapa** [comment]
Hi Joakim,

Sorry, I don't understand.  That variable is bound in `org-super-agenda` (which is a copy of `org-agenda-list` from Org 9): https://github.com/alphapapa/org-super-agenda/blob/master/org-super-agenda.el#L298

**Comment by alphapapa** [comment]
I think I found the problem you were having.  I've changed the way the package works under the hood and how it's loaded.  Please update it and check the updated instructions in the readme (it's simpler now).  It should also be in MELPA in a few hours.  Thanks.

**Comment by jave** [comment]
Thanks, I got something working now!

I did the melpa install this time.
