### ISSUE TITLE
How to invoke super agenda?

### ISSUE THREAD

**Issue by olegbc1** [alphapapa/org-super-agenda#30]
My super agenda setup is pretty simple -

```
  (let ((org-super-agenda-groups 
	   '(;; Each group has an implicit boolean OR operator between its selectors.
		(:name "IMPORTANT"  ; Optionally specify section name
			   :tag "important"
			   :todo ("TODO" "STARTED"))
		(:name "WORK"
			   :tag "work"
			   :todo ("TODO" "STARTED"))
		(:name "PERSONAL"
			   :tag "personal"
			   :todo ("TODO" "STARTED"))			   
		)))
		(org-agenda nil "a"))



```
I am dumb, but I can't figure out how to actually see this view... The standard `org-agenda a` produces a default looking agenda...

**Comment by alphapapa** [comment]
Hi,

Did you see the instructions in the readme?

> After installing, run the command org-super-agenda-mode, then set the variable org-super-agenda-groups as desired. The variable should be a list of groups. Then run an agenda command, and the entries will be grouped!

**Comment by olegbc1** [comment]
@alphapapa thanks for response - yep, I enable `org-super-agenda-mode` in my init file and set the `org-super-agenda-groups` as per code posted above without an effect on my agenda view if used `org-agenda a`

**Comment by alphapapa** [comment]
There must be something wrong with your configuration.

**Comment by styrmis** [comment]
@olegbc1 I was having a similar issue (using Emacs 25.3 with Spacemacs and the instructions in the README).

Setting the super agenda configuration within a custom agenda command (as described in [this closed issue](https://github.com/alphapapa/org-super-agenda/issues/6#issuecomment-319672659) allows super agenda to work for me (via a custom agenda view, not the main `a` agenda view).

**Comment by alphapapa** [comment]
@olegbc1 I'm going to close this now.  Feel free to comment if you need anything else.  Thanks.
