### ISSUE TITLE
Sorting in autogroups

### ISSUE THREAD

**Issue by akirak** [alphapapa/org-super-agenda#31]
This relates to #25, but I didn't find an exact solution to my problem. 

I want to sort items by schedule and then group them using `:auto-group`. Items in explicit groups seem to be reversed, while the order in "other items" seems to be retained, so I cannot sort items in a consistent way when I use auto groups. 

I've found [a FIXME comment](https://github.com/alphapapa/org-super-agenda/blob/master/org-super-agenda.el#L654) apparently related to this issue, but do you plan on implementing it?

**Comment by alphapapa** [comment]
Hi,

Thanks for reporting this.  I don't use auto-groups myself, so they are probably not as well-tested.

I pushed a commit that reverses auto-grouped items to this branch: https://github.com/alphapapa/org-super-agenda/tree/reverse-auto-group-items  Please test it and let me know if it fixes the problem.

**Comment by akirak** [comment]
Thanks! It seems to be working.

**Comment by alphapapa** [comment]
Thanks, I'll push it to master soon.

**Comment by alphapapa** [comment]
Thanks for your patience.  It should be fixed in `master` now.  Please let me know if you find any other problems.
