### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by ayrat555** [alphapapa/org-super-agenda#32]
Error message:
> Package 'org-9.0' is unavailable

Although my org-mode has 9.1.7 version

**Comment by akirak** [comment]
Have you checked the version using `M-x org-version`?

**Comment by alphapapa** [comment]
@ayrat555 This is a bug in your Emacs config, not this package, so I'm going to close this issue, but feel free to continue discussing it here.  Maybe we can help you fix it.

@akirak Thanks!

**Comment by ayrat555** [comment]
@akirak @alphapapa yeah, as described in https://orgmode.org/elpa.html, I added ```(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)``` and the package was installed fine.
