### ISSUE TITLE
Improve docs on initial setup

### ISSUE THREAD

**Issue by vmalloc** [alphapapa/org-super-agenda#34]
When making changes to agenda items it is very common to press `g` to refresh the current view. However when using `org-super-agenda` one loses his or her groups when doing that...

Is there any convenient workaround for this?

**Comment by vmalloc** [comment]
Oh, good to know. `g` is more natural since it refreshes in other contexts as well (e.g. in magit)

**Comment by vmalloc** [comment]
BTW - just checked on my end and `r` doesn't work either...

**Comment by oldenough** [comment]
r just "rebuilds agenda buffer" for me, but only works if I am in the agenda window.  I confirmed that it isn't something I have set in my config, but that doesn't mean that some package I have installed is doing the work.  Perhaps someone else will have an idea.

**Comment by alphapapa** [comment]
This is a configuration problem, specifically that `org-super-agenda-groups` is not set globally in the Emacs instance.  Maybe you are using a custom agenda command, in which case that variable does not persist after the agenda is first built.  If you use `(setq org-super-agenda-groups ...)` in the global scope, the groups will persist when the agenda is refreshed.

**Comment by vmalloc** [comment]
@alphapapa oh ok. I just copy-pasted the example on the README so I guess that's it. Could be a good idea to have a "getting started" section that demonstrates a proper (persistent) configuration.

Thanks!

**Comment by alphapapa** [comment]
Thanks, that's a good idea.

**Comment by vmalloc** [comment]
@alphapapa Looks good! Thanks!
