### ISSUE TITLE
Symbol's function definition is void: use-package

### ISSUE THREAD

**Issue by fshapps** [alphapapa/org-super-agenda#37]
Hi - I'm trying to get org-super-agenda working. Per the documentation I've added the following to my init.el file:

```
(use-package org-super-agenda :config (org-super-agenda-mode))
(let ((org-super-agenda-groups
       '((:auto-group t))))
  (org-agenda-list))
```

This generates the following error when starting emacs:

> Symbol's function definition is void: use-package
> 
> To ensure normal operation, you should investigate and remove the
> cause of the error in your initialization file.  Start Emacs with
> the ‘--debug-init’ option to view a complete error backtrace.

A reasonably thorough Google search didn't yield any answers. Help!

**Comment by alphapapa** [comment]
> A reasonably thorough Google search didn't yield any answers. Help!

Well, when I google for the title of this issue, I get lots of results about installing `use-package`.  Did you do that?  :)

**Comment by fshapps** [comment]
Ah. I see. My initial searches were too narrowly defined. A more general search reveals "use-package" is a [separate package](https://github.com/jwiegley/use-package) which must be manually installed.

I installed use-package via MELP and added the following to my init.el:

```
(use-package org-super-agenda :config (org-super-agenda-mode))
(let ((org-super-agenda-groups
       '((:auto-category t))))
  (org-agenda-list))
```
Thanks for the gentle hint. Please consider adding use-package as a requirement in the docs. Perhaps add to the Manual Installation section for us noobs?

**Comment by alphapapa** [comment]
Thanks for the suggestion.  I've updated the installation and usage instructions.  Please let me know what you think.

**Comment by fshapps** [comment]
Looks good. Thanks!
