### ISSUE TITLE
how to filter range of priorities?

### ISSUE THREAD

**Issue by jave** [alphapapa/org-super-agenda#4]
So, I have lots of more priority levels than is usual in org. 

like this:
  (defun jv-org-priorities ()
    (setq org-highest-priority 48 ;; 64 @ 48 0
          org-lowest-priority  75 ;; E
          org-default-priority 66 ;; B
          org-priority-regexp ".*?\\(\\[#\\([;:<=>?@A-Z0-9]\\)\\] ?\\)"
     ))

Anyway, my question is how can I filter priorities using "more than A" rather than just distinct priority cookies?

**Comment by alphapapa** [comment]
Hi Joakim,

That's very cool!  I've never seen anyone use more than the default set of priorities before.  If you have any non-sensitive data like that, would you mind sharing a sample of it?  I'd like to see how you use it, maybe give it a try myself.

This is an interesting idea.  I hadn't thought about selecting priorities like that.  So I guess what you need is something like:
```el
(:priority (> "A"))
```
And that would select items whose numeric priority is greater than the numeric value of A, right?  Or maybe something like:
```el
(:priority> "A")
```
What do you think?  I think the second would be easier to implement.  I think that won't be too difficult.

**Comment by alphapapa** [comment]
I think this should do it!  Please let me know what you think.  :)

**Comment by jave** [comment]
Thanks, I'll try your solution!

The reason I have so many priority levels is because the way I work with org. I write down every idea I have and I have many ideas. I wont find time to do most of them, but if I write them down I can postpone ideas with peace of mind. atm I have 1300 open TODO:s. Of course this becomes unmanageable, so I sift TODO:s upwards in priority until I actually do them. That means priority A is mostly not high enough to be done immediately. As an aside, since priorities above A arent intuitive, because you have to know ascii by heart, I have also colorcoded the priority cookies to make them more readable.

Anyway, thanks for your work on org!

**Comment by alphapapa** [comment]
>  As an aside, since priorities above A arent intuitive, because you have to know ascii by heart, I have also colorcoded the priority cookies to make them more readable.

That sounds really interesting!  Would you mind sharing the code that does that?

**Comment by jave** [comment]
the colors arent the best, but this is how you can do it:

  (defun jv-org-faces ()
    (setq org-priority-faces 
          `(
            (59 .  (:foreground ,(color-lighten-name "Red" 10) :background ,(color-lighten-name "Red" 10) :weight bold :underline t))
            (60 .  (:foreground "White" :background "Red" :weight bold :underline t))
            (61 .  (:foreground "White" :background "DarkRed" :weight bold :underline t))
            (62 .  (:foreground "White" :background ,(color-darken-name "DarkRed" 10) :weight bold :underline t))
            (63 . (:foreground "White" :background ,(color-darken-name "DarkRed" -10) :weight bold :underline t))
            (64 . (:foreground ,(color-lighten-name "Yellow" 0) :background ,(color-lighten-name "Yellow" -10)  ))
            (65 . "DeepPink")
            (66 . "firebrick")
            (67 . "tomato"))
          ))

**Comment by alphapapa** [comment]
Thanks!
