### ISSUE TITLE
Invalid org-super-agenda-groups selector: :habit

### ISSUE THREAD

**Issue by emacsomancer** [alphapapa/org-super-agenda#40]
When I try out the example under "Usage", I get an error:

`Invalid org-super-agenda-groups selector: :habit`

and my agenda appears empty.

**Comment by emacsomancer** [comment]
Ah. I think I'm getting it working. This seems like it could be such a useful package (I'm working on an [assigned] five-year plan and that's put me in the mind to actually start using org-agenda properly for things other than just meetings and teaching schedule), and it was a bit frustrating not to be able to get it to work.

Maybe it would be useful to have a recipe like (it still assumes `use-package`, but...) in the README before/around the space/shopping intown example:
```

(use-package org-super-agenda
  :ensure t
  :config
  (require 'org-habit)
  (org-super-agenda-mode))
```
And a link to [the relevant test file)[https://github.com/alphapapa/org-super-agenda/blob/master/test/test.org] (though I suppose one would still have to update the dates....)

**Comment by emacsomancer** [comment]
Thanks, @alphapapa . For the readme and test file - I was trying to think of some way to give users some sort of ready-made set of things to play with, since it does take a bit to wrap one's head round `org-super-agenda`. Maybe even a mini `.emacs`(/`init.el`) and `test.org` (the one you already have)? [I'm not sure exactly how to implement that - does emacs allow for setting an internal date differing from system date?]

In any case, it's a great package. After spending some time configuring it, it is extremely useful to me. I had given up trying to do anything beyond fixed meeting in terms of scheduling in orgmode because I ended up too large and unorganised lists of tasks, but your package certainly alleviates some of those issues.

**Comment by alphapapa** [comment]
> some way to give users some sort of ready-made set of things to play with

Well, that's what the big example in the readme is supposed to be.  It's a big `let` form that calls `org-agenda`, and users can evaluate it directly to see how it works.  Maybe I'm misunderstanding what you mean...

> I'm not sure exactly how to implement that - does emacs allow for setting an internal date differing from system date?

Haha, well, being a lisp machine, Emacs allows almost anything.  In fact, I already do this in a macro in the tests (otherwise the test results would change every day).

> In any case, it's a great package. After spending some time configuring it, it is extremely useful to me. I had given up trying to do anything beyond fixed meeting in terms of scheduling in orgmode because I ended up too large and unorganised lists of tasks, but your package certainly alleviates some of those issues.

I'm very glad to hear that!  :)  Please let me know if you have any other ideas or feedback.
