### ISSUE TITLE
":priority" not working correctly

### ISSUE THREAD

**Issue by SvenBre** [alphapapa/org-super-agenda#45]
The org-super-agenda selector ":priority" matches no entries except those that have a deadline.

Example:

 (setq org-agenda-custom-commands
       (quote (
         (" " "Super Agenda View" (
           (agenda "" ((org-agenda-span 'day)
             (org-super-agenda-groups
                '((:name "Today "
                   :time-grid t
                   :date today
                   :scheduled today
                   :order 1)
                  (:name "Important "
                   :priority "A"
                   :order 2)
                   )))) <---- more to follow

The 2nd block should match every item with "A" priority. Instead, of the
group:

* TODO [#A] Test 1
  DEADLINE: <2018-07-23 Mo>
* TODO [#A] Test 2
  SCHEDULED: <2018-07-20 Fr>
* TODO [#A] Test 3
* TODO [#B] Test 4
  DEADLINE: <2018-07-21 Sa>

... only the first item (Test 1) is displayed.

Bug or weird feature? Todos having top priority without having a
deadline is a common use case, right?

Emacs 26.1 (Arch Linux), orgmode 9.1.13 (org-plus-contrib), org-super-agenda 20180714.1348 (melpa)

**Comment by alphapapa** [comment]
This does not appear to be the case to me.  See the priority tests defined in `test/test.el`.  Items with a scheduled date but no deadline appear in the proper groups.  I just re-ran the tests with Cask, using Org 9.1.13, and all the tests pass.

Can you reproduce this with `emacs -q`?

**Comment by SvenBre** [comment]
Same result with Emacs downgraded to 25.3.

Sven

**Comment by SvenBre** [comment]
Got it. The problem is that the priority block is under an agenda command. It's working under an alltodo command. My bad.

**Comment by alphapapa** [comment]
Yes, `org-super-agenda` only groups items *after* Org Agenda collects them, and those items were not collected by it.
