### ISSUE TITLE
super-agenda and diary

### ISSUE THREAD

**Issue by mclearc** [alphapapa/org-super-agenda#46]
I'm trying to integrate my calendar entries into agenda and I've hit the following issue. On loading org-super-agenda I go into the today view, which displays fine. However, if I want to switch to week or month view I get the following:

```emacs-lisp
Preparing diary...done.
org-super-agenda--group-dispatch: Wrong type argument: stringp, nil
```

Which is weird, since I have the right diary files and settings. What's weirder is that if I call a function get all my ical data and resync my diary entries and then try and redisply week or month view in agenda everything works. So I'm wondering what's loading incorrectly on the first go-round. Below are those functions for syncing diary:

```emacs-lisp
  (defun getcal (url file)
    "Download ics file and add it to file"
    (let ((tmpfile (url-file-local-copy url)))
      (icalendar-import-file tmpfile file)
      (kill-buffer (car (last (split-string tmpfile "/"))))))

  (defun cpm/getcals ()
    "Load a set of ics calendars into emacs diary files"
    (interactive)
    (mapcar #'(lambda (x)
                (let ((file (concat diary-location (car x)))
                      (url (cdr x)))
                  (message (concat "Loading " url " into " file))
                  (find-file file)
                  ;; (flush-lines "^[& ]") ;; if you import ical as non marking
                  (erase-buffer) ;; to avoid duplicating events
                  (getcal url file)
                  ))
            calendars))

```

Any ideas?

**Comment by alphapapa** [comment]
I've never used the Diary, only Org. I know that Org has some features to
interact with it, but I don't know how they work.  There are probably some
metadata or text properties that are missing from Diary entries which this
package needs or expects.

Someone would have to dig into the Org and Diary code and figure out what's
missing.  Or you might be able to use describe-text-properties in an Agenda
view to compare Org and Diary entries and figure out what the difference
is. Maybe it wouldn't require much to handle the Diary entries.

**Comment by mclearc** [comment]
thanks - it can't be the case that org-super-agenda can't display the diary entries, because it does just that once I've executed the functions I put above. The weird thing is that the agenda throws the above error (for week or month views anyway) *until* I do that.

**Comment by alphapapa** [comment]
I guess that means that the Agenda is producing different results after you
run your functions. Try comparing the Agenda views before and after running
your functions, without super-agenda, including comparing the text
properties. It would probably be easiest to read each buffer into a string,
then split into lines, then print with pp. Then you might even be able to
use diff to compare them.

**Comment by mclearc** [comment]
So the problem turned out to be that my diary file, which just included:

```emacs-lisp
#include "cal1"
#include "cal2"
#include "cal3"
```

wasn't being read properly, because `diary-include-other-diary-files` (see [the manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Fancy-Diary-Display.html#Fancy-Diary-Display) for discussion) wasn't being loaded. I couldn't figure out how to get that latter function to work, so I've changed the `cpm/getcals` function above to include a call to shell to `cat` the various cal files into `diary`. That seems to work well. So it turns out nothing wrong with org-super-agenda at all (no surprise with that really :)) Thanks for your help!

**Comment by alphapapa** [comment]
Glad you figured it out. FYI, you don't need to use shell commands to
insert file contents into buffers. IIRC there's even an
insert-file-contents function, although I might be thinking of something
else (not in front of Emacs at the moment).
