### ISSUE TITLE
:file group selector

### ISSUE THREAD

**Issue by jave** [alphapapa/org-super-agenda#47]
It would be useful to have a :file selector, like :tag, but matching all todos in a particular file.

Perhaps this is already possible somehow?

**Comment by jave** [comment]
okay, is the :category selector. Sorry for the noise!

**Comment by alphapapa** [comment]
No problem.  Yeah, the :category selector should work by default.  IIRC that can be configured differently, so a :file selector might be useful someday.

Please feel free to let me know if you have any other ideas!
