### ISSUE TITLE
Todo filter does not work if item has no deadline

### ISSUE THREAD

**Issue by bilalshaikh42** [alphapapa/org-super-agenda#48]
A filter for a todo item of a certain state does not appear on the agenda unless there is an associated deadline. Is this intended behavior? I am trying to set a category for items that do not have deadlines. 
The line that is not working is the "Self Paced" category below. 
I have the following configuration:
```emacs-lisp
(use-package org-super-agenda
  :ensure t
  :defer t
  :config
  (setq org-super-agenda-groups
	'((:log t
		:order 0)
	  
	  (:habit t
		  :order 6)
	  
	  (:name "Self-paced"
		 :todo ("SOMEDAY" "TO-READ")
		 :order 7)
	  
	  (:name "Overdue!!"
		 :deadline past
		 :order 2)

	  (:name "Missed!"
		 :scheduled past
		 :order 3)
	 
	  (:name "Today"
		 :scheduled today
		 :deadline today
		 :order 4)
	

	  (:name "Schedule"
		 :time-grid t
		 :order 1)
	  ))
  :hook (org-agenda org-super-agenda-mode))
```

**Comment by alphapapa** [comment]
Hi,

This seems to be a fairly common misunderstanding.  `org-super-agenda` only post-processes the results from Org Agenda commands.  If an item does not appear in the Org Agenda buffer when `org-super-agenda-mode` is disabled, it will not appear when it is enabled.  The standard Org Agenda command only shows items that belong in the Agenda view, which requires an active timestamp or planning line on the day in question.  If you want to see to-do items without deadlines, use another command, like `org-todo-list`.

**Comment by bilalshaikh42** [comment]
Ah that clarifies a lot. Thank you very much!!
