### ISSUE TITLE
More control over 'date' selectors rather than t, nil and today

### ISSUE THREAD

**Issue by d12frosted** [alphapapa/org-super-agenda#5]
It would be nice to have more control over date selectors like `date`, `scheduled` and `deadline`. They accept `t`, `nil`, and `today`, but it would be nice to compare dates.

I suggest following values:

- `before-today` (useful for scheduled)
- `after-today` (useful for deadline)
- `before DATE`
- `after DATE`

---

Use case: `(:name "Missed tasks" :deadline before-today)`. This should show all deadlined tasks that are deadlined to date before today.

**Comment by d12frosted** [comment]
P. S. Very interesting project. Giving it a try to improve a bit my huge list of custom agenda commands 😸

**Comment by alphapapa** [comment]
Hi Boris,

Actually, I already did that!  But...I forgot to update the descriptions in the readme.  D:

```el
(org-super-agenda--defgroup deadline
  "Group items that have a deadline.
Argument can be `t' (to match items with any deadline),
`nil' (to match items that have no deadline), or `today' to
match items whose deadline is today."
  :section-name "Deadline items"
  :test (when-with-marker-buffer (org-super-agenda--get-marker item)
          (when-let ((time (org-entry-get (point) "DEADLINE")))
            (pcase (car args)
              ('t  ;; Check for any deadline info
               t)
              ((pred not)  ;; Has no deadline info
               (not time))
              ('past  ;; Deadline before today
               (< (org-time-string-to-absolute time) (org-today)))
              ('today  ;; Deadline for today
               (= (org-today) (org-time-string-to-absolute time)))
              ('future  ;; Deadline in the future
               (< (org-today) (org-time-string-to-absolute time)))))))

(org-super-agenda--defgroup scheduled
  "Group items that are scheduled.
Argument can be `t' (to match items with any scheduled time),
`nil' (to match items that have no scheduled time), or `today' to
match items that are scheduled for today."
  :section-name "Scheduled items"
  :test (when-with-marker-buffer (org-super-agenda--get-marker item)
          (when-let ((time (org-entry-get (point) "SCHEDULED")))
            (pcase (car args)
              ('t  ;; Check for any scheduled info
               t)
              ((pred not)  ;; Has no scheduled info
               (not time))
              ('past  ;; Scheduled before today
               (< (org-time-string-to-absolute time) (org-today)))
              ('today  ;; Scheduled for today
               (= (org-today) (org-time-string-to-absolute time)))
              ('future  ;; Scheduled in the future
               (< (org-today) (org-time-string-to-absolute time)))))))
```

So you can use them like this:

```el
(let ((org-super-agenda-groups
         '((:name "Schedule"
                  :time t)
           (:name "Today"
                  :scheduled today)
           (:name "Habits"
                  :habit t)
           (:name "Due today"
                  :deadline today)
           (:name "Overdue"
                  :deadline past)
           (:name "Due soon"
                  :deadline future)
           (:name "Unimportant"
                  :todo ("SOMEDAY" "MAYBE" "CHECK" "TO-READ" "TO-WATCH")
                  :order 100)
           (:name "Waiting..."
                  :todo "WAITING"
                  :order 98)
           (:name "Scheduled earlier"
                  :scheduled past))))
    (org-agenda-list))
```
I did put that in the examples file, at least, haha.  

I'll update the readme now.  Thanks for reminding me!

Oh, you also asked for `before/after DATE`.  I think I can do that, although I'm not sure if that would be useful in an agenda view, since it already does date-based selection of entries.  Maybe it would be more useful in the non-daily/weekly agenda commands, like `org-tags-view`, `org-todo-list`, etc?  What do you think?  Do you have any use cases in mind for that?

Thanks.

**Comment by d12frosted** [comment]
@alphapapa 

That's very kind of you to implement beforehand 😸 💯 

I was going to take a look at examples, but... Somehow I was happy enough with documentation, since you did a good job at it. 😸 

Regarding before and after date values. Indeed, `past` and `future` are obvious in terms of use cases. Most obvious use case for `before date` is archiving section. Some people tend to move things older than week or month to archive. And this selector would be helpful. Sure you can implement that using `org-agenda-skip-function`, but it's not that intuitive as your selectors.

**Comment by alphapapa** [comment]
> I was going to take a look at examples, but... Somehow I was happy enough with documentation, since you did a good job at it.

Thanks for saying that.  I've wondered if I put up too much documentation, but even I sometimes get confused when I'm testing, so more is probably better.

Ok, I think this will do it.  Please give it a try and let me know how it works.  :)  

BTW, if you could contribute any examples for the examples file, I'd really appreciate it!

**Comment by d12frosted** [comment]
I've tried only `future` and `past` - works nicely and just as I wanted 😸

> BTW, if you could contribute any examples for the examples file, I'd really appreciate it!

Roger that! 😸

Though I am in a middle of rewriting my custom agendas, so it might take a while. 

Anyways, thank you for that commit! I'll take a look.

**Comment by alphapapa** [comment]
Great, thanks.
