### ISSUE TITLE
time-grid entries from multiple days under one heading?

### ISSUE THREAD

**Issue by unhammer** [alphapapa/org-super-agenda#52]
Is it possible to get several days under one section? E.g.
```
*Agenda*
Friday: 
  22:00............ Last night on earth party
Saturday: 
  06:00.............Take-off

*TODO's*
Sched.506x: TODO [#A] check that crack in the helmet

*Priority <= B*
Sched.987x: TODO [#C] read the manual   :reading:spaceship:
```

instead of e.g. a two-day agenda with

```
Friday: 
*Agenda*
  22:00............ Last night on earth party

Saturday: 
*Agenda*
  06:00.............Take-off

*TODO's*
Sched.506x: TODO [#A] check that crack in the helmet

*Priority <= B*
Sched.987x: TODO [#C] read the manual   :reading:spaceship:
```

**Comment by alphapapa** [comment]
No, `org-super-agenda` has no concept of time, it simply post-processes what's passed to `org-agenda-finalize-entries`.  In the case of agendas spanning multiple days, Org calls that multiple times, once for each day.  Combining entries from multiple days into a single group would require a different approach.  

Essentially what you're asking for is a new, custom Agenda command (and I don't mean "custom Agenda command" in the sense that Org Agenda uses it; rather, I mean code that constructs the equivalent of an Agenda view from scratch, according to your needs).

Now having said that, it wouldn't be terribly difficult to build such a command using `org-ql` and `org-ql-agenda`.  The key would be gathering all of the time-log entries and passing them to a custom grouping/formatting function that would group them by day and format all the day-groups into a single string.

BTW, I like the pretend events you used in the example.  :)

**Comment by unhammer** [comment]
I figured there was a theme in your readme ;)

`org-ql-agenda` looks quite interesting! (I couldn't get the example to run though, I guess `if-let*` is from a newer Emacs than I have.) Anyway, I suppose this should be closed then, if it's outside super-agenda's scope and possible with org-ql once I upgrade.

**Comment by alphapapa** [comment]
Yes, very unfortunately, Emacs 26 decided to obsolete `if-let` with `if-let*`, so if I use the former, it will show a warning, and if I use the latter, Emacs 25 users will get a failure.  Very frustrating.  You can simply rename `if-let*` to `if-let` or `-if-let*` and it should work.  And Emacs 26 isn't hard to install manually if you need to.
