### ISSUE TITLE
is it possible to have different super agenda settings for week agenda and todo list?

### ISSUE THREAD

**Issue by jave** [alphapapa/org-super-agenda#58]
is it possible to have different super agenda settings for the week agenda and the todo list?

I like a complex list of todo items, but not in the agenda view, where id like less structure.

**Comment by alphapapa** [comment]
Sure, just `let`-bind `org-super-agenda-groups` and call `org-agenda` (or another agenda command) from within the `let`.

Maybe I should make a function or macro that accepts the groups as an argument and calls an agenda command, to make it easier to use than `let`-binding.
