### ISSUE TITLE
Relative dates for deadline

### ISSUE THREAD

**Issue by igoralmeida** [alphapapa/org-super-agenda#59]
Hi all,
This is somewhat related to #5, but it's probably best not to bump that.

I'm trying to add a group using `:deadline` to see only TODOs for the next 20 days, but I'm not sure it works how I want it to.
In my spacemacs config, I have this:

```
(setq org-super-agenda-groups
    `(
       (:name "SomeGroup" :deadline
          (before ,(org-read-date nil nil "+20d")))))
```

My lisp-fu is close to zero, but IIUC this means the 20-day-ahead date is evaluated only once (at the time of setting org-super-agenda-groups, i.e. when spacemacs opens). But if i just remove the comma I get a `stringp` error.
So how should I do this?

This issue may also turn into a request for more ways to specify dates when defining groups. Let's see.

**Comment by alphapapa** [comment]
You could do it in a command, like this:
```el
(defun ia/org-agenda-+20d ()
  (interactive)
  (let ((org-super-agenda-groups
         `((:name "SomeGroup"
                  :deadline (before ,(org-read-date nil nil "+20d"))))))
    (org-agenda-list)))
```

**Comment by igoralmeida** [comment]
Thanks, it does work, but I think this solution implies several calls, i.e. I'd open different agenda views depending on what I'm looking for.

I was thinking more like a sort of permanent 'dashboard' with interesting groups, and for example calling `org-agenda-redo` to update the moving window of days. Would the `,(org-read-date...)` thingy work (i.e. would it update with new TODO items that have entered the moving window)?

... or should I try to create a [block agenda](https://orgmode.org/manual/Block-agenda.html#Block-agenda)? In this case, could org-super-agenda be configured to postprocess each block individually?

**Comment by alphapapa** [comment]
> Would the `,(org-read-date...)` thingy work (i.e. would it update with new TODO items that have entered the moving window)?

It happens every time the function is called.

> ... or should I try to create a block agenda? In this case, could org-super-agenda be configured to postprocess each block individually?

That should be possible.  It would require some work, understanding how Org constructs composite agenda buffers (see e.g. `org-agenda-forward-block`), and writing code to handle that case.  It might be as simple as detecting whether there are multiple structural headers in an agenda buffer, and if so, splitting the buffer on those headings and processing each block separately.  This isn't a feature I would use much myself, so I don't know if I will implement it myself, but I'd be glad to consider patches.

**Comment by igoralmeida** [comment]
Okay, I guess I have some more reading to do. Let's close this until I can try your suggestions.
Thanks a lot!

**Comment by lkmokadam** [comment]
@igoralmeida can you share your solution?

**Comment by igoralmeida** [comment]
Sorry @lkmokadam, I have not yet dedicated time to make this work.
As a stop-gap solution, recently in spacemacs I have been using `, / d` to generate a sparse tree of items in the current org file having deadlines within the next 14 days. I don't know if this is the default behavior.

It's not everything I wanted, but covers SOME use cases.

**Comment by midas0441** [comment]
I am running into the same issue, and I don't understand why the following doesn't work:

`(before ,(org-read-date nil nil "+20d"))`

I've tried it without the comma, with the comma, and even with a single quote.
I end up with the error:

`org-time-string-to-absolute: Wrong type argument: stringp, '(org-read-date nil nil "+7d")` if I use a quote.

or 

`org-time-string-to-absolute: Wrong type argument: stringp, (\, (org-read-date nil nil "+7d"))` if I use a comma.

Any help please?

**Comment by alphapapa** [comment]
@midas0441 Please consult the Elisp manual section regarding quoting, backquoting, and splicing of lists.
