### ISSUE TITLE
:files selector

### ISSUE THREAD

**Issue by dustinlacewell** [alphapapa/org-super-agenda#60]
I keep all my projects in `~/src/$PROJECT_NAME/` and I have various org files within those top-level directories. I would like to get an agenda going where I have sections for each project.

I think that a `:files` selector could work for this. By globbing my filesystem and finding all of the org-files that belong to a project - I can generate the super-agenda groups needed. One for each project, setting the `:name` and `:files` for each.

**Comment by alphapapa** [comment]
Please try the WIP branch at https://github.com/alphapapa/org-super-agenda/tree/pred-and-file-path.  See the tests:

```el
(ert-deftest org-super-agenda--test-pred ()
  (should (org-super-agenda--test-run
           :groups '((:pred ((lambda (item)
                               (s-matches? "Skype" item))
                             (lambda (item)
                               (s-matches? "pizza" item))))))))

(ert-deftest org-super-agenda--test-file-path ()
  (should (org-super-agenda--test-run
           :groups '((:file-path "super")))))
```
