### ISSUE TITLE
Is it possible to add new line or separator after "Other items" ?

### ISSUE THREAD

**Issue by kr63** [alphapapa/org-super-agenda#62]
Hello!
I've setup org-super-agenda and it works fine. My agenda after applying corresponding filters looks like as the following (e.g.):

Tuesday 25 December 20118
    ...
    Other items
        Something: TODO Do something
Wednesday 26 December 2018

There is no new line or separator between next day (Wednesday) and the last other item.

Will you please to implement an option like org-super-agenda-header-separator, which could add an empty string or separation string after other items?

**Comment by alphapapa** [comment]
Hi, I think that's probably a good idea, but would you mind showing me a screenshot so I can see exactly what you see?  (You can edit out the names of items, of course.)

**Comment by kr63** [comment]
> Hi, I think that's probably a good idea, but would you mind showing me a screenshot so I can see exactly what you see? (You can edit out the names of items, of course.)

![screenshot_2019-01-17_12-47-14](https://user-images.githubusercontent.com/22182929/51306705-76da3680-1a57-11e9-871e-bdd1b97d9287.png)

**Comment by alphapapa** [comment]
Thanks.  Shouldn't be hard to add.

**Comment by alphapapa** [comment]
As mentioned in #74, this would be better solved in `org-agenda.el` so it would be available to all Org users.  This package only affects items within each day's items, so adding a separator is rightfully outside its scope.  Having realized that, I probably won't add this feature to this package.

It would be a simple addition to Org Agenda, so please consider mentioning it on the Org mailing list.
