### ISSUE TITLE
Make name of "Other items" group customizable

### ISSUE THREAD

**Issue by m-cat** [alphapapa/org-super-agenda#65]
Hi pops,

I'd surely like to change the name of the Other group. I noticed that it's built into the code and not customizable:

```
finally do (setq non-matching (list :name "Other items"
```

I can, of course, modify the source code, but would like to be able to change the name just by setting a variable (or however you deem it fit to customize this bad boy).

Whaddya think?

**Comment by alphapapa** [comment]
Seems like a good idea to me...son...?  :)

**Comment by m-cat** [comment]
It will be surely a monumental task.

I'll tackle this head-on. I shall raise a PR once I have time.

I've always wanted to get my feet wet with Emacs Package Development (EPD). (Although I generally dislike wet feet).

Let's brainstorm names for the new variable. I propose `org-super-agenda-unmatched-name` (similar to `org-super-agenda-unmatched-order`).

**Comment by alphapapa** [comment]
Should be very simple: just make a new `(defcustom org-super-agenda-unmatched-name ...` and replace `"Other items"` with `org-super-agenda-unmatched-name`.
