### ISSUE TITLE
:scheduled but only for items without time

### ISSUE THREAD

**Issue by Fuco1** [alphapapa/org-super-agenda#69]
I would like to pull all scheduled tasks into a group, but only those which do not have explicit time.  If they have a time (i.e. `10:00`) I want to display them in the timeline.  Is this somehow possible?

**Comment by alphapapa** [comment]
If I understand you correctly, this should be simple, something like:

`'((:time-grid t) (:scheduled t))`

Note that it may not work for all agenda-like commands, as it depends on the text properties that are set on the items to distinguish which ones have a time.

Alternatively, it wouldn't be too difficult to either modify the `:scheduled` selector to have an option like `with-time`, or you could use the new `:pred` selector with a custom predicate that would check whether the item's scheduled timestamp includes a time.

**Comment by Fuco1** [comment]
What I actually wanted was

```elisp
:and (:habit t
      :not (:time-grid))
```

So habits but not those which would appear on the grid (same for scheduled items).

Thanks for pointing me to the `:time-grid` selector!

This package is awesome.
