### ISSUE TITLE
No effect on agenda

### ISSUE THREAD

**Issue by novoid** [alphapapa/org-super-agenda#7]
Hi!

Thanks for this awesome package!

My issue is, that I can't make it work since I get my normal agenda, without anything different than usual.

I cloned your code from GitHub (since I got only stable MELPA which does not feature org-super-agenda) and ran following code:

```
(defun my-load-local-el (part)
  "load lisp file and warn if not found"
  (let ((fullname (concat my-user-emacs-directory part)))
    (if (file-exists-p fullname)
	(load fullname)
      (message (format "Loading %s (source)...failed" fullname)))))

(my-load-local-el "contrib/org-super-agenda/org-super-agenda.el");; this works definitely

  (let ((org-super-agenda-groups
	 '(;; Each group has an implicit boolean OR operator between its selectors.
	   (:name "Today"  ; Optionally specify section name
		  :time-grid t  ; Items that appear on the time grid
		  ;; :todo "TODAY"  ; Items that have this TODO keyword
		  )
	   (:name "Important"
		  ;; Single arguments given alone
		  ;;:tag "bills"
		  :priority "A")
	   ;; Set order of multiple groups at once
	   (:order-multi (2 (:name "Shopping"
				   :tab "Besorgung"
				   ;; Boolean AND group matches items that match all subgroups
				   ;;:and (:tag "shopping" :tag "@town")
				   )
			    (:name "Started"
				   :todo "STARTED")
			    ;;(:name "Food-related"
			    ;;       ;; Multiple args given in list with implicit OR
			    ;;       :tag ("food" "dinner"))
			    ;;(:name "Personal"
			    ;;       :habit t
			    ;;       :tag "personal")
			    (:name "Habits"
				   :habit t)
			    (:name "BWG"
				   :tag "@BWG")
			    (:name "read"
				   :tag "2read")
			    (:name "reward"
				   :tag ("reward" "lp"))
			    ;;(:name "Space-related (non-moon-or-planet-related)"
			    ;;       ;; Regexps match case-insensitively on the entire entry
			    ;;       :and (:regexp ("space" "NASA")
			    ;;                     ;; Boolean NOT also has implicit OR between selectors
			    ;;                     :not (:regexp "moon" :tag "planet")))
						 ))
	   ;; Groups supply their own section names when none are given
	   (:todo "WAITING" :order 8)  ; Set order of this section
	   (:todo ("SOMEDAY" "WATCHING")
		  ;; Show this group at the end of the agenda (since it has the
		  ;; highest number). If you specified this group last, items
		  ;; with these todo keywords that e.g. have priority A would be
		  ;; displayed in that group instead, because items are grouped
		  ;; out in the order the groups are listed.
		  :order 9)
	   (:priority<= "B"
			;; Show this section after "Today" and "Important", because
			;; their order is unspecified, defaulting to 0. Sections
			;; are displayed lowest-number-first.
			:order 1)
	   ;; After the last group, the agenda will display items that didn't
	   ;; match any of these groups, with the default order position of 99
	   )))
    (org-agenda nil "a"))
```

This code does generate my usual agenda and nothing is logged in the *Messages* buffer.

What is my error?

**Comment by alphapapa** [comment]
Did you activate `org-super-agenda-mode`?

**Comment by novoid** [comment]
Of course NOT ;-)
I had it in my use-package code when I realized that I don't get org-super-agenda via my ELPA config. Then I switched to my-load-local-el without activating the mode.

Silly me.

Now it seems to do something different because I get "if: Symbol's function definition is void: when-let". This seems to be not related to *loading* org-super-agenda in the first place.

Thanks for your help!

**Comment by alphapapa** [comment]
Are you on Emacs 24?  `when-let` is in Emacs 25.  If you install through MELPA, it will warn you about the missing dependency, but since you installed it manually...  :)

**Comment by novoid** [comment]
You're right for a second time: I thought I had upgraded to Emacs 25 a time ago. I'll try again after updating my Debian oldstable to the new stable which comes with Emacs 25.

Thanks!

**Comment by alphapapa** [comment]
Yeah, I had to build and install Emacs 25 on my machines too.  It wasn't as bad as I was afraid of, I just used the Emacs 25 packages from Debian and they built on Ubuntu and my old Debian version.  However, somehow I managed to not get the Emacs and Org info files installed with them, and I do miss those...but not enough to figure out why they didn't get installed, haha.  ;)
