### ISSUE TITLE
How to add a separator line between days? 

### ISSUE THREAD

**Issue by lkmokadam** [alphapapa/org-super-agenda#74]
My org-super -agenda seems like messy. In order to differentiate between the days easily, how can I add separator line between days in agenda mode?

**Comment by lkmokadam** [comment]
Found solution.

(setq org-super-agenda-header-separator "\n###################################################################################\n")

**Comment by alphapapa** [comment]
That is not a function of this package but of Org Agenda itself.  When displaying a multi-day agenda, this package only affects the items within each day, not across days.

**Comment by alglez** [comment]
If I'm not wrong this is probably related to this other question https://github.com/alphapapa/org-super-agenda/issues/62#issuecomment-455093229  .

Actually I manage to add line breaks between days modifying `org-agenda` after `org-agenda-finalize-entries` but my solution is far from being elegant or practical as I am not an elisp expert. Probably the best way to achieve, even though still far from perfect, is using advice.

**Comment by alphapapa** [comment]
It would be possible to add a separator after all items (adding a separator after just `Other items` wouldn't work in the case that there is no `Other items` group).

However, the better way to solve this would be to do it in `org-agenda.el` so it would be available to all Org users.  I'm guessing that the Org maintainers would be happy to accept a simple patch adding this feature.

@alglez is right in that it could probably also be done with advice to `org-agenda-finalize-entries`.

**Comment by mgpanpan** [comment]
I think a possible solution might be changing the variable `org-agenda-format-date`, it could be modified to be a formated date with a line of separator inserted ahead.

Here's my solution:
```
(defun pmg/org-agenda-format-date-aligned (date)
  "Format a DATE string for display in the daily/weekly agenda.
This function makes sure that dates are aligned for easy reading."
  (require 'cal-iso)
  (let* ((dayname (calendar-day-name date))
	 (day (cadr date))
	 (day-of-week (calendar-day-of-week date))
	 (month (car date))
	 (monthname (calendar-month-name month))
	 (year (nth 2 date))
	 (iso-week (org-days-to-iso-week
		    (calendar-absolute-from-gregorian date)))
	 (weekyear (cond ((and (= month 1) (>= iso-week 52))
			  (1- year))
			 ((and (= month 12) (<= iso-week 1))
			  (1+ year))
			 (t year)))
	 (weekstring (if (= day-of-week 1)
			 (format " W%02d" iso-week)
		       "")))
    (concat (make-string (window-width) 9472)
            "\n"
            (format "%-10s %2d %s %4d%s    "
                    dayname day monthname year weekstring)
            )))

(setq org-agenda-format-date 'pmg/org-agenda-format-date-aligned)
```

![image](https://user-images.githubusercontent.com/4384206/69860234-be189100-12d0-11ea-86eb-ff584b5817fc.png)

Reference:
[https://lists.gnu.org/archive/html/emacs-orgmode/2010-05/msg00388.html](https://lists.gnu.org/archive/html/emacs-orgmode/2010-05/msg00388.html)

**Comment by alphapapa** [comment]
@mgpanpan Yes, and you could do that with function advice that simply concats the separator string onto the result of the function, rather than copying the function and altering it.

**Comment by mgpanpan** [comment]
@alphapapa Yes, Thank you for the advice!

**Comment by alphapapa** [comment]
@mgpanpan That would be a good candidate for a blog post or sharing on /r/emacs and /r/orgmode.  I'm sure lots of other users would like to add a separator line or other customization like that.

**Comment by mgpanpan** [comment]
@alphapapa Thank you very much for your advice! I've simplified the configuration code to:

```
(setq org-agenda-format-date (lambda (date) (concat "\n"
                                                    (make-string (window-width) 9472)
                                                    "\n"
                                                    (org-agenda-format-date-aligned date))))
```
I'm quit a newbie in Emacs Elisp. Maybe there were nicer solutions.

Also a post has been established in reddit r/orgmode. Hope it helpful!
