### ISSUE TITLE
Request: Navigating sections

### ISSUE THREAD

**Issue by haji-ali** [alphapapa/org-super-agenda#78]
I use org-agenda to group my tasks by category. I would like to be able to jump between categories. I thought I could use `M-{` and `M-}` which calls `org-agenda-backward-block` and `org-agenda-forward-block`. However, the point jumps to the next _section_ (i.e., agenda/todo) but the next _group_ (categories in my case). 
I think by setting the property `org-agenda-structural-header`, the navigation could be made to work for groups in `org-super-agenda`.

**Comment by haji-ali** [comment]
This seems to work for me. But I would rather not distinguish `org-super-agenda` headers with their `face` property. Maybe they should have some custom property?

```
  (defun private/org-super-agenda-make-header ()
    (let (begin end)
      (save-excursion
	  (goto-char (point-min))
	  (while (equal (forward-line) 0)
		(when (and (string= (get-text-property (point) 'face) 'org-super-agenda-header))
          (beginning-of-line)
          (setq begin (point))
          (end-of-line)
          (setq end (point))
          (add-text-properties begin end
                               '(org-agenda-structural-header t)))))))

  (add-hook 'org-agenda-finalize-hook #'private/org-super-agenda-make-header)
```

**Comment by alphapapa** [comment]
Hi,

> But I would rather not distinguish org-super-agenda headers with their face property. 

Why not?  :)  Anyway, #77 adds a text property.  I'll try to get to it soon.

> I think by setting the property org-agenda-structural-header, the navigation could be made to work for groups in org-super-agenda.

That seems like a good idea.  I think it would be best to make it optional, in case someone wants to distinguish them from the Org Agenda headers, but we could probably enable it by default.

Would you be interested in sending a PR?  (Apologies in advance if you do and I don't get to it for a while.  ;)

**Comment by haji-ali** [comment]
The pull request #80 implements using a new variable that contains the extra properties. #77 Could also use this variable to add the new text property `org-super-agenda-header t`.
