### ISSUE TITLE
closed items break agenda

### ISSUE THREAD

**Issue by Sermak-GIT** [alphapapa/org-super-agenda#79]
Whenever I have a file containing a closed item (i.e. the line `CLOSED: [2019-04-22 Mon 13:19])` and start my agenda, it opens up completely empty and I get the message `setq: Wrong type argument: listp, "----------------------"`. My config is very similar to the "super zaen view", so I don't see a need to post it here.
Adding a `(:discard :todo "DONE")` at the beginning had no effect

**Comment by alphapapa** [comment]
> My config is very similar to the "super zaen view", so I don't see a need to post it here.

I can't help you if you won't provide the details necessary to reproduce the problem.  For example, search for "ECM" on this page: https://orgmode.org/worg/org-faq.html
