### ISSUE TITLE
Magit/Org  like folding?

### ISSUE THREAD

**Issue by fuxialexander** [alphapapa/org-super-agenda#8]
I think it would be great if the section can be folded with <TAB> like the commits in Magit, or a ORG heading.

**Comment by alphapapa** [comment]
That's a very cool idea, thanks.  I'll think about it.

**Comment by alphapapa** [comment]
Good news, you can already do this!  :)  Just install `origami` and run `origami-mode`, then you can use the show/close-node commands.  It works based on the indentation, and all the items in the agenda are indented compared to the headers.  So all you need to do is bind a key to, e.g. `origami-toggle-node` and you're done.

**Comment by novoid** [comment]
Remark: yafolding mode provides the same feature (folding based on indentation level) as configured in [my configuration](https://github.com/novoid/dot-emacs/blob/master/config.org#yafolding---folding-based-on-identation--m-ret-c-tab).

**Comment by alphapapa** [comment]
Thanks, Karl!
