### ISSUE TITLE
Does auto-* selectors work with other selectors?

### ISSUE THREAD

**Issue by DSMasterson** [alphapapa/org-super-agenda#82]
Tried setting the following groups, but only the first three seemed to show up in my agenda.  However, if I comment out the first three, then the auto-category starts working.  Am I doing something wrong?

;; Org Super Agenda Groups
(setq org-super-agenda-groups
      '(
	 (:name "Today"
	        :time-grid t
	        :order 0)
	 (:name "Next"
	        :todo "NEXT"
	        :order 1)
	 (:name "Deadline"
	        :deadline t
	        :order 2)
	(:name "Categories"
	       :auto-category t
	       :order 9)
	))

**Comment by alphapapa** [comment]
Remember this note from the readme, which I'm guessing explains what's happening to you:

> A group selector creates a section in the agenda containing the items it matches, and any items it doesn’t match are passed to the next group selector.

**Comment by DSMasterson** [comment]
Ahh.  A different way of thinking about it...
