### ISSUE TITLE
Question on Zaen323 example ?

### ISSUE THREAD

**Issue by DSMasterson** [alphapapa/org-super-agenda#84]
I am attempting to use pretty much the zaen323 example as is.  I left off the "discard" at the end and various other groups that don't apply to my data, but the basic structure is the same.  As I understand it, the zaen323 setup has two sections -- (1) a "time-grid" section and (2) a series of other interesting TODO groups.  The example screenshot shows it nicely compacted and I understand it.  The confusing part for me is that, with my data, I get an "Other Items" at the end of each section.  Can you explain that?

1. I assume that the "Other Items" are items not caught by the previous rules of the section.  However, the "Other Items" of section 1 are *not* ALL the other items in my data set.  What are these "Other Items"?

2. I would've thought, given the setup of zaen323, that any items not caught by the rule in section 1 would've flowed through into section 2.  Is that wrong?

3. If I put a "discard" at the end of section 1, would I be losing things from section 2?  Why?

Perhaps this explanation should be added to the documentation?

**Comment by alphapapa** [comment]
His example is complicated.  You would have to give me an ECM in order for me to help you.  Probably the best way to learn about it is to experiment, starting with simpler examples and building up to what you want.

**Comment by DSMasterson** [comment]
Ah.  That's the key I wasn't catching -- it is a composite.  So, the agenda output from section 1 has no relation to the agenda output by section 2 -- they are just concatenated together.

I'll experiment more with the example by turning off sections and see what the output looks like.  It's not easy to build up a simple example that continue to fits my data, so I'll try building down.

**Comment by alphapapa** [comment]
Thanks.  Feel free to submit an example of your own config when you're satisfied.
