### ISSUE TITLE
Request: Allow passing a lambda to auto-group settings for :header-form

### ISSUE THREAD

**Issue by fabrik42** [alphapapa/org-super-agenda#86]
Hi!

Thank you for this great extension. I am currently in the process of setting it up and I am using categories a lot in my org setup.

So naturally I am a big fan of the `:auto-category` feature.

Right now, [the generated header is hardcoded](https://github.com/alphapapa/org-super-agenda/blob/master/org-super-agenda.el#L843) with `Category: <category name>`.

I am far from being an elisp expert, but what I would love to do is to pass a custom lambda into the setting to change the heading during runtime.

```elisp
(:auto-category t :header-form (lambda(category) (concat "My prefix: " category)))
```

This would also allow more interesting approaches, like adding emojis as prefixes to the header based on the category name.

Let me know what you think!

**Comment by alphapapa** [comment]
Hi Christian,

Thanks for the kind words.  Glad you're finding it useful.

That's an interesting idea.  I suppose it could be made to work something like:
```
(:auto-category (:header (lambda (category) ...)))
```
The lambda would need to be an argument to the `:auto-category` selector; in your example, it's in the place of a selector.

If you like, try evaluating this:
```el
(org-super-agenda--def-auto-group fabrik-category "their org-category property"
  :key-form (org-super-agenda--when-with-marker-buffer (org-super-agenda--get-marker item)
              (org-get-category))
  :header-form (funcall (plist-get args :header-fn) key))
```
Then try using this selector:
```el
(:auto-category (:header-fn (lambda (category)
                              (concat "My prefix: " category))))
```
I haven't tested it, but I think that will work.  You can adjust the lambda as desired.

If it works well, it might be worth adding to other selectors also.

Thanks.

**Comment by fabrik42** [comment]
Thank you for your explanation! I think the macro would generate a filter called `auto-fabrik-category`. I'll give it a try later.

**Comment by alphapapa** [comment]
Yes, you're right.  Thanks.

**Comment by fabrik42** [comment]
I am happy with my current setup, so I am closing the ticket. Thank you for your support!
