### ISSUE TITLE
Option to add birthdays?

### ISSUE THREAD

**Issue by alexmascension** [alphapapa/org-super-agenda#92]
Hi!

I find org-super-agenda really interesting to manage some of my tasks better. I've recently come up with the idea of adding certain dates, like birthdays, holidays, or landmarks, and I wanted them to fulfill 3 properties:

- They have a specific set of tags ("birthday" "holiday" "landmark")
- They are periodic (once a year, for example)
- I want them to appear on the agenda not only "today", but two or three days before. Once the landmark day has passed, they should disappear from the agenda view.

I came across the option of adding a recurrent task with "+1y" in SCHEDULED option from org-mode; but I can't create a group on the agenda which fulfills the three points.

My current setup is this

```
(org-super-agenda-mode t)


(with-eval-after-load 'org (setq org-super-agenda-groups
                                 '( ;; Each group has an implicit boolean OR operator between its selectors.
  (:name "NEXT" 
         :todo "NEXT"
         :order 2
         :face (:foreground "CornflowerBlue"))
  (:name "TODAY"
         :deadline today
         :scheduled today
         :order 3
         :face (:foreground "LimeGreen"))
  (:name "DEADLINED"
         :deadline past
         :scheduled past
         :order 5
         :face (:foreground "brown")) 
  (:name "NEAR DEADLINE"
         :deadline future
         :scheduled future
         :order 15
         :face (:foreground "PaleVioletRed")) 
        (:name "IMPORTANT"
               :priority "A"
               :order 8)
        (:name "MID PRIORITY"
               :priority "B"
               :order 10)
        (:name "LOW PRIORITY"
               :priority "C"
               :order 90)
        (:name "Baúl de los recuerdos"
               :todo "RECOVERABLE"
               :order 100
               :face (:foreground "SlateGrey"))
        (:name "Emacs Stuff"
               :tag "emacs"
               :order 30)
         ;; After the last group, the agenda will display items that didn't
         ;; match any of these groups, with the default order position of 99
         )))
```

I don't know to what extent org-super-agenda is able to cope with these requirements; or if any other package is required or more suitable to do it. My main problem is that I would like something like this:
```
(:name "BIRTHDAYS / HOLIDAYS / LANDMARKS"
    :and (
        :todo "TODO"
        :tag ("holiday" "birthday" "landmark")
        :order 1
        :not ( :deadline ( before -3d ))
))
```
Even though this doesn't even work (before -3d is not correct) it doesn't solve the second problem: the rest of holidays will leak onto the rest of categories. I can even solve it with something like that
```
(:name "UNIMPORTANT BIRTHDAYS / HOLIDAYS / LANDMARKS"
    :and (
        :tag ("holiday" "birthday" "landmark")
))
```
But I don't want to show this group in the agenda.

Hope there is any way to work around this.

Thanks in advance!

**Comment by alphapapa** [comment]
Hi,

This is a common issue for Org users.  You should probably review the documentation here: https://orgmode.org/manual/Deadlines-and-scheduling.html  Note the differences between DEADLINE, SCHEDULED, and plain timestamps.

If a date is important enough, you should probably use a TODO item with a DEADLINE with warning days.  Otherwise, SCHEDULED and plain timestamps will show up in agenda views for future days, e.g. weekly agenda views.

In this package, you may also find the `:discard` selector useful.

Other than the default agenda, you may find `org-ql` useful for writing your own, custom agenda-like views.

**Comment by alexmascension** [comment]
Hi,

Thanks, I will try to see if org-ql does the trick.

**Comment by alphapapa** [comment]
Did that work for you?  Can this issue be closed now?  :)

**Comment by alexmascension** [comment]
I'm still working on it, but if I see I need some help I will reopen the issue. 

Thanks

**Comment by alphapapa** [comment]
Okay.  If you need more help, please post on /r/emacs or /r/orgmode, and you can mention /u/github-alphapapa if you want.
