### ISSUE TITLE
Can I match match todo:s with no priority cookie?

### ISSUE THREAD

**Issue by jave** [alphapapa/org-super-agenda#94]
Hello,

I have a lot of todo:s, and a lot of super agenda categories. 

Sometimes I forget to set a priority cookie, and then I forget about it altogether.

I would like to be able to have unprioritized todos go to the top so I see them and then set prio cookie.

Atm I have (setq org-super-agenda-unmatched-order 0) 
but this only works for todo:s not matched by any other rule.

**Comment by alphapapa** [comment]
Did you try `(:not (:priority))`?  See also variable `org-default-priority`.

**Comment by jave** [comment]
(:name "fix"                                                                                                                                                                   
                      ;; Single arguments given alone                                                                                                                                         
                      (:not (:priority))                                                                                                                                                      
                      :order 0                                                                                                                                                                
                      )     

I get:

user-error: Invalid org-super-agenda-groups selector: (:not (:priority))

**Comment by alphapapa** [comment]
That's not valid syntax.  Pay careful attention to the fact that it's a plist, and to the parentheses.    Try this:
```el
(setq org-super-agenda-groups
      '((:name "Unprioritized"
               :not (:priority>= "C"))))
```

**Comment by jave** [comment]
thanks, the last one worked!
